Cargo.lock, Cargo.toml, src/moonlink/Cargo.toml, src/moonlink/src/storage/index/persisted_bucket_hash_map.rs, src/moonlink/src/storage/mooncake_table/shared_array.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs, src/moonlink/src/table_handler.rs, src/moonlink/src/union_read/table_metadata.rs
Use `assert_` macros, which is strictly better than the current `assert!` macro, since it prints out lhs / rhs when assertion failure. The introduced third-party dependency is a pretty lightweight one.
Closes https://github.com/Mooncake-Labs/moonlink/issues/344
=> Use comparison macros

src/moonlink/src/storage/iceberg/deletion_vector.rs, src/moonlink/src/storage/iceberg/iceberg_table_manager.rs, src/moonlink/src/storage/iceberg/test_utils.rs, src/moonlink/src/storage/mooncake_table/test_utils.rs, src/moonlink/src/table_handler/test_utils.rs
Batch deletion vector is the in-memory format for iceberg deletion vector.
Similar to https://github.com/Mooncake-Labs/moonlink/pull/345, we should record max number of rows for batch deletion vector somewhere (aka, persistence), so it could be loaded at recovery.
The codepath (aka, recording and loading max number of rows) has been executed almost in most unit tests.
Closes https://github.com/Mooncake-Labs/moonlink/issues/376
=> [storage] Fix deletion vector rows

src/moonlink_connectors/src/replication_connection.rs
We shouldn't panic on connection errors. Currently, when the connection closes on the pg_mooncake side, when we restart moonlink will panic. Instead we log a message. 
Also removed `unwraps` and added proper errors. 
- 
- 
-
=> Don't panic on disconnection

README.md
This patch fix a dead link in README also fix some link for markdown
update: dead link seems fixed, this patch only fix the lint
=> doc: fix wrong link in README also with some lint

src/moonlink/src/storage/iceberg/test_utils.rs
This patch fix flaky test on mac os
error:
```cli
---- storage::iceberg::tests::test_async_iceberg_snapshot stdout ----
thread 'storage::iceberg::tests::test_async_iceberg_snapshot' panicked at src/moonlink/src/storage/iceberg/test_utils.rs:76:9:
assertion failed: cur_disk_pathbuf.starts_with(&warehouse_directory)
---- storage::iceberg::tests::test_filesystem_sync_snapshots stdout ----
thread 'storage::iceberg::tests::test_filesystem_sync_snapshots' panicked at src/moonlink/src/storage/iceberg/test_utils.rs:76:9:
assertion failed: cur_disk_pathbuf.starts_with(&warehouse_directory)
---- storage::iceberg::tests::test_small_batch_size_and_large_parquet_size stdout ----
thread 'storage::iceberg::tests::test_small_batch_size_and_large_parquet_size' panicked at …
```
=> fix: flaky test on macOS

src/moonlink/src/storage/iceberg/iceberg_table_manager.rs, src/moonlink/src/storage/iceberg/puffin_writer_proxy.rs, src/moonlink/src/storage/index/persisted_bucket_hash_map.rs, src/moonlink/src/storage/storage_utils.rs
I'm checking ducklake code, and they're using UUIDv7, instead of UUIDv4, to fill in filenames.
The benefit of which is to provide rough order of file generation.
Discussion reference: https://github.com/duckdb/ducklake/discussions/142#discussioncomment-13370086
Code reference: https://github.com/duckdb/ducklake/blob/d4e144737bc3f88aef1d8768cb2ef162b0db9f09/src/storage/ducklake_insert.cpp#L362-L378
UUID is used here:
- I don't see iceberg spec to require filename format
- Avoid filename duplication
- UUID as prefix to avoid hotspotting on object storage (whose metadata is backed by spanner/dynamo/etc)
=> [storage] Use uuidv7 to generate filenames

src/moonlink_connectors/src/pg_replicate/postgres_source.rs, src/moonlink_connectors/src/replication_connection.rs
Currently we never remove the table schemas from the stream. When the table is dropped, we should remove the schema from the stream as well as the sink. This is symmetric to add table. 
- 
- 
-
=> Drop table bug fix

src/moonlink/src/storage/iceberg/iceberg_table_manager.rs, src/moonlink/src/storage/iceberg/tests.rs, src/moonlink/src/storage/mooncake_table/test_utils.rs
The invariant check is wrong: it's possible to remove all data files and file indices when nothing left after compaction (aka, all rows found deleted).
=> [storage] Fix iceberg import invariant check

src/moonlink/src/storage/compaction/compactor.rs, src/moonlink/src/storage/compaction/table_compaction.rs, src/moonlink/src/storage/iceberg/iceberg_table_manager.rs, src/moonlink/src/storage/iceberg/test_utils.rs, src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/disk_slice.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs, src/moonlink/src/storage/mooncake_table/transaction_stream.rs, src/moonlink/src/table_handler/test_utils.rs
To enable file-sized based compaction, we need to record file size.
Closes https://github.com/Mooncake-Labs/moonlink/issues/414
=> [storage] Record file size for disk file

src/moonlink/src/storage/iceberg/compaction_tests.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs
This PR enables file-sized based compaction (the initial version only compacts those with deleted rows), add related state-based tests.
Closes https://github.com/Mooncake-Labs/moonlink/issues/413
=> [storage] Enable file-size-based compaction

src/moonlink/src/storage/iceberg/iceberg_table_manager.rs, src/moonlink/src/storage/iceberg/index.rs, src/moonlink_backend/tests/test_backend.rs
This PR fixes file id assignment at recovery, which requires to be unique (per mooncake table).
Closes https://github.com/Mooncake-Labs/moonlink/issues/430
=> [storage] Fix file id assignment at recovery

src/moonlink_connectors/src/pg_replicate/moonlink_sink.rs
Temporary change to provide most up to date LSN to postgres, mostly in the interest of keeping replication happy. This is temporary and not safe to recover from, but it keeps postgres up to date and allows prompt recycling of WAL and correct stream restart. 
- 
- 
-
=> Update lsn on commit

src/moonlink/src/storage/iceberg/compaction_tests.rs, src/moonlink/src/storage/iceberg/state_tests.rs, src/moonlink/src/storage/iceberg/test_utils.rs, src/moonlink/src/storage/iceberg/tests.rs
A no-op change, simply add missing validation for persisted iceberg snapshot, to make sure everything in iceberg (data files, deletion vectors, file indices) points to remote filepath instead of local ones.
=> [minor] Validate persisted iceberg snapshot

src/moonlink/src/storage/mooncake_table.rs
After each mooncake snapshot, I have a check to validate whether mooncake snapshot is at a consistent state.
https://github.com/Mooncake-Labs/moonlink/blob/fcba6451c6afac04e3f7f4d127a7c4ba186f4bde/src/moonlink/src/storage/mooncake_table/snapshot.rs#L939-L943
=> [minor] Add additional assertion in test utils

Cargo.lock, src/moonlink/Cargo.toml, src/moonlink/benches/bench_write.rs, src/moonlink/benches/microbench_index_stress.rs, src/moonlink/src/lib.rs, src/moonlink/src/storage.rs, src/moonlink/src/storage/compaction/test_utils.rs, src/moonlink/src/storage/index/hash_index.rs, src/moonlink/src/storage/index/persisted_bucket_hash_map.rs, src/moonlink/src/storage/mooncake_table/disk_slice.rs
Improve index scan to avoid any n^2 lookups.
For each index scan, we will scan each bucket at most once.
- 
- 
-
=> index perf improvement

src/moonlink/src/storage/cache/object_storage/base_cache.rs, src/moonlink/src/storage/cache/object_storage/cache_handle.rs, src/moonlink/src/storage/cache/object_storage/object_storage_cache.rs, src/moonlink/src/storage/cache/object_storage/state_tests.rs, src/moonlink/src/storage/cache/object_storage/test_utils.rs
- Simplify cache handle state to only two: (1) has pinned cache handle, and (2) no pinned cache handle, including no cache
+ from mooncake table's perspective, "no cache" vs "no pinned cache" has no difference
- Add a new state into cache, which is "attempt cache but not sufficient space"
+ I planned to handle it as a special case, but found it an important state from mooncake table disk file's perspective.
=> [storage] Simplify cache output state and consider insufficient disk space

src/moonlink/src/storage/compaction/compactor.rs, src/moonlink/src/storage/iceberg/table_property.rs, src/moonlink/src/storage/mooncake_table/disk_slice.rs
This PR enables ZSTD level 5 to compress data files inline.
The consideration for compression level is 
(1) overhead for small files, not a big concern here, since we only have small files for last streaming writes
(2) tradeoff between IO/storage and CPU overhead
I used ZSTD for a few years, and level 5 is the default I used.
I tested by writing a few parquet files, and confirm file size does change.
Also checked with pg_mooncake, and confirm zstd compression is already handled (by duckdb parquet reader).
```sql
pg_mooncake (pid: 5837) =# DROP EXTENSION IF EXISTS pg_mooncake CASCADE;
INSERT INTO r SELECT a, 'val_' || a FROM generate_series(1, 250000) AS …
```
=> [storage] ZSTD compress parquet data file

.github/workflows/ci.yml
I have a PR with unit test running ~1 hour and keeps running, which wastes resource and burns our bill.
This PR sets a timeout to testing stage.
Reference CI run: https://github.com/Mooncake-Labs/moonlink/actions/runs/15688369501/job/44197204808?pr=470
Timeout change test PR: https://github.com/Mooncake-Labs/moonlink/actions/runs/15689748769/job/44201810050?pr=474
=> [CI] Add timeout to test CI

src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/snapshot_read_output.rs, src/moonlink/src/storage/mooncake_table/state_tests.rs, src/moonlink/src/table_handler.rs, src/moonlink/src/table_notify.rs
This PR passes evicted data files to main eventloop at table handler, and spawn a detached task to delete them all.
Closes https://github.com/Mooncake-Labs/moonlink/issues/477
=> [storage] Delete cache-evicted data files

src/moonlink_connectors/src/replication_connection.rs, src/moonlink_connectors/src/replication_manager.rs
For now we should only support explicitly adding tables via `create_table`, so don't discover any tables on replication start. 
In this case, switch the order so that we start the replication before explicit add. 
- 
- 
-
=> Fix add order

src/moonlink/src/storage/cache/object_storage/object_storage_cache.rs, src/moonlink/src/storage/cache/object_storage/state_tests.rs, src/moonlink/src/storage/compaction/compactor.rs, src/moonlink/src/storage/compaction/table_compaction.rs, src/moonlink/src/storage/compaction/tests.rs, src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs, src/moonlink/src/storage/mooncake_table/snapshot_read_output.rs, src/moonlink/src/storage/mooncake_table/state_tests.rs, src/moonlink/src/storage/mooncake_table/transaction_stream.rs, src/moonlink/src/table_handler.rs, src/moonlink/src/table_notify.rs, src/moonlink/src/union_read/read_state.rs, src/moonlink_backend/src/lib.rs, src/moonlink_connectors/src/pg_replicate/table_init.rs, src/moonlink_connectors/src/replication_connection.rs, src/moonlink_connectors/src/replication_manager.rs
This PR does a no-op rename globally, to update naming `data_file_cache` to `object_storage_cache`;
I plan to leverage the same infra for all object storage files, including data files, puffin blobs, and file indices.
=> [minor] Rename data file cache to object storage cache

src/moonlink/src/union_read/read_state_manager.rs
Invalidates the cache as soon as the table advances, fixing stale reads for new sessions that have a low LSN while retaining fast-path hits when data is unchanged.
- 
- 
-
=> Add cache invalidation check

Cargo.lock, Cargo.toml, src/moonlink/Cargo.toml, src/moonlink/src/storage/mooncake_table/transaction_stream.rs
In streaming xact, when processing deletion,
we need to do a index lookup in foreground on everything in current transaction, both in-memory and flushed rows (since they are not visible to snapshot thread yet).
Index lookup is async function that may involve file IO, so it is relatively costly.
But it is very unlikely a row in current transaction is deleted, so most of the check is indeed wasted.
Fix it by adding a bloomfliter.
- 
- 
-
=> fix streaming update perf

src/moonlink/src/storage/iceberg/iceberg_table_manager.rs, src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs, src/moonlink/src/storage/mooncake_table/transaction_stream.rs
I made a bad decision in compaction, which is to store bimap between data file and file index.
Data compaction decides which data files to compact based on their file size, then file indices based on the data files to compact.
The motivation at that time is to get file indices to compact in O(1); but seems one extra O(N) iteration is enough.
Bimap is bad:
- It makes code messy, every time a data file / file index updates, two places will be updated in-sync;
- It makes file index reference count harder, see attached issue. 
There's no behavior change, so no unit test or state machine change;
extra assertion is added to assert mooncake snapshot consistent.
Closes https://github.com/Mooncake-Labs/moonlink/issues/524
=> [storage] Rework data file <-> file index mapping

src/moonlink/src/storage/cache/object_storage/base_cache.rs, src/moonlink/src/storage/cache/object_storage/cache_handle.rs, src/moonlink/src/storage/cache/object_storage/object_storage_cache.rs, src/moonlink/src/storage/cache/object_storage/state_tests.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs
When I'm working on cache integration, I found most of the deletion cases are unreference + delete, so simply provide an extra unreference interface to save a function call and mutex acquisition/release.
Closes https://github.com/Mooncake-Labs/moonlink/issues/537
=> [storage] Combine cache handle unreference and delete

src/moonlink/src/storage/iceberg/compaction_tests.rs, src/moonlink/src/storage/iceberg/iceberg_table_manager.rs, src/moonlink/src/storage/iceberg/index.rs, src/moonlink/src/storage/iceberg/state_tests.rs, src/moonlink/src/storage/iceberg/table_manager.rs, src/moonlink/src/storage/iceberg/tests.rs, src/moonlink/src/storage/mooncake_table/deletion_vector_puffin_state_tests.rs, src/moonlink/src/storage/mooncake_table/file_index_state_tests.rs, src/moonlink/src/table_handler/tests.rs
When recovery from iceberg snapshot, each file has assign its own file id; which should be passed to mooncake table for continued usage.
Closes https://github.com/Mooncake-Labs/moonlink/issues/514
=> [storage] Return next file id on recovery

src/moonlink/src/row/moonlink_row.rs, src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/data_batches.rs, src/moonlink/src/storage/mooncake_table/test_utils.rs
The code was calling equals_record_batch_at_offset with a different input 
(the function is expecting full row and caller calls with extracted values).
Fix the mismatch.
Also fix a small perf inefficiency (we don't need to read record batch when the key is stored in memory)
Also modified test config so we will hit the case.
- 
- 
-
=> fix multi column key

src/moonlink_backend/src/lib.rs, src/moonlink_connectors/src/replication_connection.rs, src/moonlink_connectors/src/replication_manager.rs
This PR does two things
1) It avoids crashing when unsubscribing from a table that has already been dropped
2) It avoids the deadlock when we drop the rowstore and columnstore tables together e.g (`DROP r, c;`)
In order to avoid the deadlock, we first attempt the drop with a lock timeout. In the even that we can't obtain a lock within the specified timeout, we spawn the same query as its own task with its own pg client and store the handle in the replication connection. 
In the event that the replication connection needs to shutdown and has pending `retry_handles`, we await the pending handles in another task and store a handle in the replication manager. 
Closes https://github.com/Mooncake-Labs/moonlink/issues/547
- Continue on drop for non-existent table
- Add timeout and retry logic …
=> Improve handling of async drop events

src/moonlink/src/storage.rs, src/moonlink/src/storage/cache/object_storage.rs, src/moonlink/src/storage/cache/object_storage/cache_config.rs, src/moonlink/src/storage/cache/object_storage/cache_handle.rs, src/moonlink/src/storage/cache/object_storage/local_file_optimization_state_tests.rs, src/moonlink/src/storage/cache/object_storage/object_storage_cache.rs, src/moonlink/src/storage/cache/object_storage/state_tests.rs, src/moonlink/src/storage/cache/object_storage/test_utils.rs, src/moonlink/src/storage/mooncake_table/data_file_state_tests.rs, src/moonlink/src/storage/mooncake_table/deletion_vector_puffin_state_tests.rs, src/moonlink/src/storage/mooncake_table/file_index_state_tests.rs, src/moonlink/src/storage/path_utils.rs, src/moonlink_backend/src/lib.rs
This PR is the first one to implement local filesystem file storage/cache optimization, to avoid double storage.
The overall design is:
- Optimization lies in caching layer, to avoid "check and optimize" logic scattered everywhere
- Optimization happens at import and fetch cache entries
One design design decision I made is:
- The ideal scenario is to add another pending state to replace local file cache with remote one, but that complicates state machine a lot, for example, we need to handle concurrent deletion and usage
- So for simplicity, the replacement only attempts once
- Extra local files could be deleted via compaction and cache eviction, so local filesystem is still shrinkable
I tested with pg_mooncake regression test:
```sh
PASS setup 28ms …
```
=> [storage] [1/N] Object storage cache support local filesystem optimization

src/moonlink_backend/src/lib.rs
After this PR, this temporary and cache directory are placed under `PGDATA/mooncake` directory.
```sh
vscode ➜ /workspaces/pg_mooncake/moonlink (main) $ ls -l /home/vscode/.pgrx/data-17/mooncake/
total 16
drwx------ 2 vscode vscode 4096 Jun 24 07:13 moonlink_cache_file
drwx------ 2 vscode vscode 4096 Jun 24 07:13 moonlink_temp_file
drwx------ 3 vscode vscode 4096 Jun 24 06:16 public
drwx------ 2 vscode vscode 4096 Jun 24 06:44 public.r
vscode ➜ /workspaces/pg_mooncake/moonlink (main) $ ls -l /home/vscode/.pgrx/data-17/mooncake/moonlink_temp_file/inmemory_public.r_66125_475506632.parquet 
-rw------- 1 vscode vscode 2121 Jun 24 07:17 /home/vscode/.pgrx/data-17/mooncake/moonlink_temp_file/inmemory_public.r_66125_475506632.parquet
```
Tested with regression test:
```sh
--- beginning …
```
=> [storage] Update cache and temp file directory

src/moonlink_backend/src/lib.rs
Followup for https://github.com/Mooncake-Labs/moonlink/pull/571, need to give the correct cache directory.
Tested with integration test
```sh
running 7 tests
test tests::test_bulk_insert_one_million_rows ... ok
test tests::test_recreate_directory ... ok
test tests::test_moonlink_service ... ok
test tests::test_replication_connection_cleanup ... ok
test tests::test_scan_returns_inserted_rows ... ok
test tests::test_create_iceberg_snapshot ... ok
test tests::test_scan_table_with_lsn ... ok
```
Tested with pg_mooncake:
```sql
pg_mooncake (pid: 159950) =# DROP EXTENSION IF EXISTS pg_mooncake CASCADE;
INSERT INTO r SELECT a, 'val_' || a FROM generate_series(1, …
```
=> [storage] Use absolute path for statvfs

src/moonlink_backend/src/lib.rs, src/moonlink_connectors/src/pg_replicate/table_init.rs, src/moonlink_connectors/src/replication_connection.rs, src/moonlink_connectors/src/replication_manager.rs
Use fully-qualified column storage table id as mooncake table path.
How I tested:
- I update pg_mooncake `TableId` to implement the format trait
- Mooncake table files do create under the correct directory
diff:
```sh
diff --git a/moonlink b/moonlink
index 940e57b..77670ab 160000
--- a/moonlink
+++ b/moonlink
@@ -1 +1 @@
-Subproject commit 940e57b7411680baa9e02aa45e18e2f75c8cd76d
+Subproject commit 77670ab37fae4aa437111c00a2ecb21068f82afd-dirty
diff --git a/pg_duckdb b/pg_duckdb
index bd3c5a0..90ef7eb 160000
--- a/pg_duckdb
+++ b/pg_duckdb
@@ -1 +1 @@
-Subproject commit bd3c5a0fffe187358a7d66c888bf0ea2e5afb8a1
+Subproject commit 90ef7ebc820cb0ca9c085a26b73553c607aaf04e
diff --git a/src/pgmoonlink/common.rs b/src/pgmoonlink/common.rs
index e22e3a4..28bbf01 100644
--- …
```
=> [storage] Use stringified table id as mooncake table path

src/moonlink_backend/src/lib.rs
- Rename temporary files and read-through cache directories, so that namespace "mooncake" is not repeated
- Rename whole moonlink directory from "mooncake" to "pg_mooncake" to better conform the subdirectory naming practice
How I tested, after this change, the directory hierarchy looks like
```sh
vscode ➜ /workspaces/pg_mooncake/moonlink (hjiang/rename-moonlink-directory) $ ls /home/vscode/.pgrx/data-17/pg_mooncake/
public.r  read_through_cache  temp
```
Closes https://github.com/Mooncake-Labs/moonlink/issues/582
=> [storage] Rename moonlink directory

src/moonlink/src/storage/mooncake_table/data_file_state_tests.rs, src/moonlink/src/storage/mooncake_table/deletion_vector_puffin_state_tests.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs, src/moonlink/src/storage/mooncake_table/state_test_utils.rs
pg_mooncake regression tests pass
```sh
PASS setup 23ms
PASS partitioned_table 605ms
PASS sanity 574ms
```
pg_mooncake sql:
```sql
pg_mooncake (pid: 33138) =# DROP EXTENSION IF EXISTS pg_mooncake CASCADE;
INSERT INTO r SELECT a, 'val_' || a FROM generate_series(1, 1000000) AS a;
SELECT count(*) FROM c;
DELETE FROM r WHERE a % 2 = 0;
SELECT * FROM c LIMIT 10;
NOTICE:  drop cascades to table c
DROP EXTENSION
DROP TABLE
CREATE TABLE
CALL
INSERT 0 1000000
count  
---------
1000000
(1 row)
DELETE 500000
a    |     b      
--------+------------
267265 | val_267265
267267 | val_267267 …
```
=> [storage] [3/N] Integrate data file storage with local filesystem optimization

.devcontainer/setup.sh
Somehow our current `psql` command is broken.
I don't have concern to bake password in setup script as it's only for devcontainer.
Manual check:
```sh
[/workspaces/moonlink] (hjiang/fix-psql) 
vscode@0b962e1e6dd9$ psql
psql (17.5 (Debian 17.5-1.pgdg120+1))
Type "help" for help.
postgres=# 
```
=> Fix psql command at devcontainer startup

src/moonlink/src/storage/iceberg/iceberg_table_event_manager.rs, src/moonlink/src/table_handler.rs, src/moonlink/src/table_handler/test_utils.rs, src/moonlink/src/table_handler/tests.rs, src/moonlink_connectors/src/pg_replicate/table_init.rs, src/moonlink_connectors/src/replication_connection.rs
This PR uses oneshot channel for drop table synchronization, instead of mpsc of size 1
Test statements with pg_mooncake
```sql
pg_mooncake (pid: 5932) =# DROP TABLE IF EXISTS r;                                                         
NOTICE:  table "r" does not exist, skipping
DROP TABLE
DROP EXTENSION
CREATE TABLE
CALL
pg_mooncake (pid: 5932) =# INSERT INTO r VALUES (1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e'), (6, 'f');
CALL mooncake.create_snapshot('c');
UPDATE r SET b = a + 1 WHERE a = 3 or a = 5;
CALL mooncake.create_snapshot('c');
SELECT * FROM c;
INSERT 0 6
CALL
UPDATE 2
CALL
a | b 
---+---
3 | 4
5 | 6
1 | a
2 | b …
```
=> [storage] Use oneshot channel for drop table synchronization

src/moonlink/src/storage/iceberg/iceberg_table_event_manager.rs, src/moonlink/src/table_handler/test_utils.rs, src/moonlink/src/table_handler/tests.rs, src/moonlink_connectors/src/replication_connection.rs
Current test implementation is intrinsically flaky:
- At test environment destruction, read state manager is destructed before table handler
- At read state manager destruction, it destructs the cached read state, if any, which spawns a task to send notification to table handler
+ This is to workaround the limitation that drop trait has to be sync
- If we're lucky, when send happens table handler is still alive, otherwise sending to a closed channel panics
No real good way except introducing complicated synchronization logic, this PR simply adds sleep in between.
Closes https://github.com/Mooncake-Labs/moonlink/issues/636
=> [storage] Reduce flakiness for table hander test

src/moonlink/src/storage/iceberg/iceberg_table_manager.rs, src/moonlink/src/storage/iceberg/table_manager.rs, src/moonlink/src/storage/iceberg/test_utils.rs, src/moonlink/src/storage/iceberg/tests.rs, src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/state_test_utils.rs, src/moonlink/src/storage/mooncake_table/table_snapshot.rs, src/moonlink/src/storage/storage_utils.rs
This PR fixes unique file id assignment at iceberg persistence.
Current buggy implementation uses the same table auto increment id for all deletion vector files, which limits max file number  to be 100.
Closes https://github.com/Mooncake-Labs/moonlink/issues/642
=> [storage] Fix unique file id assignment at iceberg persistence

src/moonlink/src/storage/compaction/compactor.rs, src/moonlink/src/storage/compaction/table_compaction.rs, src/moonlink/src/storage/compaction/tests.rs, src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/storage_utils.rs
Current implementation assigns only one table id to compactor, which limits overall data files to compact 100.
This PR assigns a range of table ids, according to the compaction payload.
Closes https://github.com/Mooncake-Labs/moonlink/issues/641
=> [storage] Allow excessive number of data files to compact

Cargo.lock, src/moonlink/src/union_read/read_state_manager.rs, src/moonlink_backend/src/lib.rs, src/moonlink_backend/tests/test_backend.rs, src/moonlink_connectors/src/replication_connection.rs, src/moonlink_connectors/src/replication_manager.rs, src/moonlink_metadata_store/Cargo.toml, src/moonlink_metadata_store/src/base_metadata_store.rs, src/moonlink_metadata_store/src/postgres/pg_metadata_store.rs, src/moonlink_metadata_store/tests/test_pg_metadata_store.rs
This PR is the first PR to integrate recovery with moonlink backend.
Disclaimer:
- This is only the first part of the recovery logic, and it hasn't been integrated with pg_mooncake
- cdc publish and subscribe part hasn't been integrated, I will followup with another PR
- This PR is supposed to be a no-op change
Did some testing on pg_mooncake side to make sure it doesn't affect production.
regression test:
```sh
PASS setup 25ms
PASS partitioned_table 717ms
PASS sanity 726ms
```
pg_mooncake SQL statements
```sql
pg_mooncake (pid: 102224) =# DROP TABLE IF EXISTS r;
INSERT INTO r VALUES (1, …
```
=> [storage] [1/N] Integrate table recovery with backend initialization

src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/test_utils.rs, src/moonlink/src/storage/mooncake_table/tests.rs
Flush LSN is recorded in the mooncake table for force snapshot usage.
This PR correctly populates its value at recovery.
=> [storage] Assign table flush lsn after recovery

src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/union_read/read_state_manager.rs
I did a bad special handle to read snapshot: when there's no valid LSN (aka, everything 0), we perform a snapshot read instead of relying on cache.
A second thought, a better way is to notify current snapshot LSN after recovery, thus no special handle needed.
Existing test cases already cover the change.
=> [storage] Remove special handle to read snapshot

src/moonlink_backend/src/lib.rs, src/moonlink_backend/tests/test_backend.rs, src/moonlink_metadata_store/src/base_metadata_store.rs, src/moonlink_metadata_store/src/error.rs, src/moonlink_metadata_store/src/metadata_store_utils.rs, src/moonlink_metadata_store/src/postgres.rs, src/moonlink_metadata_store/src/postgres/pg_client_wrapper.rs, src/moonlink_metadata_store/src/postgres/pg_metadata_store.rs, src/moonlink_metadata_store/src/postgres/sql/create_tables.sql, src/moonlink_metadata_store/src/postgres/utils.rs, src/moonlink_metadata_store/tests/common/test_environment.rs, src/moonlink_metadata_store/tests/test_pg_metadata_store.rs, src/moonlink_metadata_store/tests/test_pg_metadata_store_utils.rs
This PR updates metadata access to:
recovery:
- if schema not exist, skip
- if metadata table not exist, skip
- load metadata table, and perform recovery
create table:
- if schema not exist, abort
- if metadata table not exist, create
- store metadata row
drop table:
- if schema not exist, abort
- if metadata table not exist, abort
- delete metadata row
Tested with pg_mooncake regression tests:
```sh
PASS setup 24ms
PASS partitioned_table 712ms
PASS sanity 701ms
```
Tested with pg_mooncake sql statements:
```sql
pg_mooncake (pid: 245014) =# DROP TABLE r;
INSERT INTO r VALUES (1, 'a'), …
```
=> [storage] Fix metadata access for mooncake tables

src/moonlink/src/table_handler.rs, src/moonlink_connectors/src/pg_replicate/clients/postgres.rs, src/moonlink_connectors/src/pg_replicate/postgres_source.rs, src/moonlink_connectors/src/replication_connection.rs, src/moonlink_connectors/src/replication_manager.rs
Use `debug` instead of `info` so we only get verbose logging when `RUST_LOG=debug` is set.
Closes https://github.com/Mooncake-Labs/moonlink/issues/660
- 
- 
-
=> Use debug instead of info

src/moonlink/src/storage.rs, src/moonlink/src/storage/iceberg/table_manager.rs, src/moonlink/src/storage/index.rs, src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/table_handler.rs, src/moonlink/src/table_handler/test_utils.rs, src/moonlink/src/table_handler/tests.rs, src/moonlink/src/table_notify.rs
Moonlink sends back persisted flush LSN to pg, so WAL could be recycled.
However, chances are that before pg handles confirmed LSN, moonlink / pg_mooncake already crashes.
After load snapshot from iceberg table, we are able to recover up to flush LSN, but due to the situation described above, pg's still possible to resent persisted content which we need to handle.
In this PR, I discard already persisted content by checking LSN for 
- LSN for non-streaming writes in begin message
- LSN for stream write in stream commit message
Testing doc: https://docs.google.com/document/d/1Go02j9Nv2HrhABM-GBpBA4lPACJG3twC58J8pnKHAmA/edit?usp=sharing
Closes https://github.com/Mooncake-Labs/moonlink/issues/686
=> [storage] Discard already persisted content after recovery

src/moonlink_connectors/src/pg_replicate/conversions/cdc_event.rs, src/moonlink_connectors/src/pg_replicate/moonlink_sink.rs, src/moonlink_connectors/src/pg_replicate/postgres_source.rs
As described at https://github.com/Mooncake-Labs/moonlink/issues/695, we currently suffer race condition on recovery (or moonlink restart). In short words, cdc events could be emitted before table schema has been set, leading to missing schema error.
This PR handles certain case with buffering replication messages in a buffer, and emit when corresponding schema arrives.
I tested manually with pg_mooncake:
- Write a few rows to mooncake table, and don't trigger iceberg snapshot, so everything's unconfirmed
- Shutdown everything, make sure all rows are replayed and inserted into the mooncake table
Closes https://github.com/Mooncake-Labs/moonlink/issues/695
Closes https://github.com/Mooncake-Labs/moonlink/issues/603
=> [postgres] Buffer replication messages when missing table schema

src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs
As of https://github.com/Mooncake-Labs/moonlink/pull/488 we need to support the case where the `flush_lsn` is 0, since at the time of initial copy the table will contain data at LSN 0. There are some assertions that don't currently support this and are causing failures. We should add this special case to their checks.
Closes https://github.com/Mooncake-Labs/moonlink/issues/692
Closes https://github.com/Mooncake-Labs/moonlink/issues/688
- 
- 
-
=> Add checks for special case flush lsn

src/moonlink/src/union_read/read_state_manager.rs
Flip the equality for our cache condition to avoid reading stale cache. 
Closes https://github.com/Mooncake-Labs/moonlink/issues/652
- 
- 
-
=> Fix equality for cache condition

src/moonlink_backend/tests/common.rs
Mooncake schema creation has nothing to do with table, should be initialized at test guard construction.
Closes https://github.com/Mooncake-Labs/moonlink/issues/705
=> Fix integration test TestGuard construction

src/moonlink/benches/microbench_index_stress.rs
This PR adds benchmark to index construction, which is necessary for optimization.
Current result:
```sh
vscode@36b8aa3bdd4e$ cargo bench --features bench --bench microbench_index_stress
index_build/build_index_10m_entries
time:   [1.1969 s 1.2103 s 1.2236 s]
index_query/search_10m_entries
time:   [786.67 ns 817.28 ns 838.35 ns]
```
Related to https://github.com/Mooncake-Labs/moonlink/issues/697
=> [storage] Add benchmark for index build

src/moonlink_backend/tests/common.rs
I changes some params for flush threshold and fails a bunch of unit tests, then I found we only read the first batch in unit tests...
=> Fix id from parquet in tests

src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/transaction_stream.rs, src/moonlink/src/table_handler.rs
This PR removes flush in non-streaming write situations.
There're two invariants for snapshot / table handler:
- Flush when the table is at a clean state
- Flush LSN only progresses and never regresses
Flush operation in the middle of a non-streaming transaction breaks both.
Flush inside of initial copy also breaks, but should be handled differently, because
- Normal non-streaming writes only happens for small volume of updates
- But initial copy could have indefinitely large number of updates, which cannot buffer all of them in memory.
As for initial copy appends, I considered a few possible fixes:
1. Flush LSN affects iceberg snapshot, but not mooncake snapshot; so an easy fix is to explicitly skip iceberg snapshot during initial copy operation. The code change is the least (3 LOC), but …
=> [storage] Fix flush in non-streaming flush

src/moonlink/src/storage/async_bitwriter.rs, src/moonlink/src/storage/index/persisted_bucket_hash_map.rs
This PR integrate self-implemented async index writer to hash index construction.
Check https://github.com/Mooncake-Labs/moonlink/pull/721 for details.
Tested with pg_mooncake
```sh
PASS setup 25ms
PASS partitioned_table 709ms
PASS sanity 696ms
```
Performance improvement metrics (checked for 5 times for each metrics):
- Building index block with 250000 index entries, before change: 329ms, after change: 233ms
- Building index block with 1000000 index entries, before change: 1.35s, after change: 955ms 
Closes https://github.com/Mooncake-Labs/moonlink/issues/697
=> [storage] Integrate async bit writer into index block construction

src/moonlink/src/storage/iceberg/test_utils.rs, src/moonlink/src/storage/iceberg/tests.rs, src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs, src/moonlink/src/storage/mooncake_table/state_test_utils.rs, src/moonlink/src/storage/mooncake_table/test_utils.rs, src/moonlink/src/table_handler.rs
There're 4 invariants I could think of for snapshot / mooncake table:
- There's at most one mooncake snapshot ongoing
- There's at most one iceberg snapshot ongoing
- Flush only happens after commit, when table is at a clean state
- Flush LSN never regresses
But it's broken leading to weird behavior, I think it's better to check invariants at the first place especially in testing, instead of let it happen in a non-deterministic style in production.
This PR adds corresponding invariant check in the code.
Tested with pg_mooncake regression test
```sh
PASS setup 25ms
PASS partitioned_table 756ms
PASS sanity 728ms
```
Tested with pg_mooncake sql
```sql
pg_mooncake (pid: 3855) =# CREATE EXTENSION pg_mooncake;
CREATE TABLE r (a int …
```
=> [storage] Add invariant check

src/moonlink/src/storage/index/persisted_bucket_hash_map.rs
We're now double buffer at index write, one for buffered writer, another within async index writer.
Quoted from doc: https://docs.rs/tokio/latest/tokio/io/struct.BufWriter.html
```
It does not help when writing very large amounts at once, or writing just one or a few times.
```
so basically it's adding potential copies and memory consumption.
After this change, I didn't spot performance change.
Closes https://github.com/Mooncake-Labs/moonlink/issues/727
=> [storage] Avoid double buffer at index write

src/moonlink_connectors/src/pg_replicate/clients/postgres.rs, src/moonlink_connectors/src/replication_manager.rs
On some postgres operations the log would output `WARN: No transaction in progress`. In order to remove this we should first call `rollback txn` rather than `abort`.
Also changes a `warn!` to `debug!` given it occurs quite frequently and is benign. 
Small follow up to https://github.com/Mooncake-Labs/moonlink/issues/660
- rollback txn first
- change warn to debug
-
=> Fix warning

src/moonlink/src/storage/mooncake_table/snapshot.rs, src/moonlink/src/storage/mooncake_table/tests.rs
See inline comments, it's possible to flush with latest commit LSN when table clean.
Closes https://github.com/Mooncake-Labs/moonlink/issues/744
=> [storage] Fix sanity check for force snapshot

src/moonlink/src/storage/iceberg.rs, src/moonlink/src/storage/iceberg/iceberg_table_loader.rs, src/moonlink/src/storage/iceberg/iceberg_table_manager.rs, src/moonlink/src/storage/iceberg/iceberg_table_syncer.rs, src/moonlink/src/storage/iceberg/mod.rs
Iceberg table manager is too large and become harder to read and modify, so I would like to split into two parts: load and sync. Two 400-line files are much easier to read than a huge 900-line file.
This PR is a no-op change to split iceberg table manager; I tried to split it into two structs (syncer & loader), but hard to manage and reason data member ownership (need lifecycle annotation everywhere).
I would like to make the same change for mooncake snapshot also.
=> [minor] Split iceberg table manager

src/moonlink/benches/bench_write.rs, src/moonlink/benches/microbench_write_mooncake_table.rs, src/moonlink/src/lib.rs, src/moonlink/src/storage.rs, src/moonlink/src/storage/filesystem/accessor.rs, src/moonlink/src/storage/filesystem/accessor/base_filesystem_accessor.rs, src/moonlink/src/storage/filesystem/accessor/filesystem_accessor.rs, src/moonlink/src/storage/filesystem/accessor/test_utils.rs, src/moonlink/src/storage/filesystem/gcs.rs, src/moonlink/src/storage/filesystem/gcs/tests.rs, src/moonlink/src/storage/filesystem/s3.rs, src/moonlink/src/storage/filesystem/s3/tests.rs, src/moonlink/src/storage/iceberg/file_catalog.rs, src/moonlink/src/storage/iceberg/iceberg_table_manager.rs, src/moonlink/src/storage/iceberg/mock_filesystem_test.rs, src/moonlink/src/storage/iceberg/tests.rs, src/moonlink/src/storage/iceberg/utils.rs, src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/deletion_vector_puffin_state_tests.rs, src/moonlink/src/storage/mooncake_table/file_index_state_tests.rs, src/moonlink/src/storage/mooncake_table/table_creation_test_utils.rs, src/moonlink/src/storage/mooncake_table/test_utils.rs, src/moonlink/src/storage/mooncake_table/tests.rs, src/moonlink/src/table_handler/test_utils.rs, src/moonlink_connectors/src/pg_replicate/table_init.rs
The minimum object storage feature we need to support is copy local write-through cache to object storage.
I will integrate the API to iceberg table manager in the next PR.
=> [storage] Filesystem accessor support copy

src/moonlink/src/storage/filesystem.rs, src/moonlink/src/storage/filesystem/accessor/base_filesystem_accessor.rs, src/moonlink/src/storage/filesystem/accessor/filesystem_accessor.rs, src/moonlink/src/storage/filesystem/gcs/tests.rs, src/moonlink/src/storage/filesystem/s3/tests.rs, src/moonlink/src/storage/filesystem/utils.rs, src/moonlink/src/storage/filesystem/utils/path_utils.rs, src/moonlink/src/storage/iceberg/file_catalog.rs, src/moonlink/src/storage/iceberg/iceberg_table_manager.rs, src/moonlink/src/storage/iceberg/iceberg_table_syncer.rs, src/moonlink/src/storage/iceberg/index.rs, src/moonlink/src/storage/iceberg/utils.rs
- Migrate local file upload from tokio (which only supports local filesystem) to filesystem accessor (which also supports object storage)
- Handle both absolute path and relative path in the accessor
Closes https://github.com/Mooncake-Labs/moonlink/issues/757
Closes https://github.com/Mooncake-Labs/moonlink/issues/750
=> [storage] Iceberg upload migrate to filesystem accessor

src/moonlink/src/storage/filesystem/accessor/base_filesystem_accessor.rs, src/moonlink/src/storage/filesystem/accessor/filesystem_accessor.rs, src/moonlink/src/storage/filesystem/accessor/test_utils.rs, src/moonlink/src/storage/filesystem/gcs/tests.rs, src/moonlink/src/storage/filesystem/s3/tests.rs, src/moonlink/src/storage/iceberg/file_catalog.rs
It's need for object storage cache on cache miss, and recovery.
=> [storage] [1/N] Copy object from remote to local

src/moonlink/benches/microbench_write_mooncake_table.rs, src/moonlink/src/storage/filesystem/gcs/gcs_test_utils.rs, src/moonlink/src/storage/filesystem/gcs/tests.rs, src/moonlink/src/storage/filesystem/s3/s3_test_utils.rs, src/moonlink/src/storage/filesystem/s3/tests.rs, src/moonlink/src/storage/iceberg/compaction_tests.rs, src/moonlink/src/storage/iceberg/gcs_test_utils.rs, src/moonlink/src/storage/iceberg/iceberg_table_manager.rs, src/moonlink/src/storage/iceberg/s3_test_utils.rs, src/moonlink/src/storage/iceberg/state_tests.rs, src/moonlink/src/storage/iceberg/tests.rs, src/moonlink/src/storage/mooncake_table/deletion_vector_puffin_state_tests.rs, src/moonlink/src/storage/mooncake_table/file_index_state_tests.rs, src/moonlink/src/storage/mooncake_table/table_creation_test_utils.rs, src/moonlink/src/storage/mooncake_table/test_utils.rs, src/moonlink/src/storage/mooncake_table/tests.rs, src/moonlink/src/storage/mooncake_table/validation_test_utils.rs, src/moonlink/src/table_handler/test_utils.rs
IMO, not all test cases need to adapt from local storage to remote storage, for example, state machine based tests is ok with local filesystem iceberg warehouse.
In this PR, I adapt some integration style unit tests to leverage remote object storage, and update a few test cases and utils.
Closes https://github.com/Mooncake-Labs/moonlink/issues/440
=> [storage] [3/N] Adapt iceberg integration to leverage remote storage

src/moonlink/src/storage/filesystem/gcs.rs, src/moonlink/src/storage/filesystem/gcs/gcs_test_utils.rs, src/moonlink/src/storage/filesystem/gcs/test_guard.rs, src/moonlink/src/storage/filesystem/gcs/tests.rs, src/moonlink/src/storage/filesystem/s3.rs, src/moonlink/src/storage/filesystem/s3/s3_test_utils.rs, src/moonlink/src/storage/filesystem/s3/test_guard.rs, src/moonlink/src/storage/filesystem/s3/tests.rs, src/moonlink/src/storage/iceberg/tests.rs
We need RAII-style test guard for object storage, otherwise have to do that manually which is easy to forget.
I tried another way: make deletion operation synchronous, so we could have blocking IO at drop trait, but that changeset is much bigger than this PR.
Closes https://github.com/Mooncake-Labs/moonlink/issues/770
=> [storage] Implement test guard for object storage

.github/workflows/ci.yml, src/moonlink/src/storage/filesystem/s3/s3_test_utils.rs
I have added a few object storage related features into unit tests, which relies on 
(1) local minio server as S3 backend
(2) local fake GCS server as gcs backend.
In this PR, I added both into CI.
There're two concerns and followups left for the PR:
- Triple compilation time and CI execution time, which is hard to avoid (maybe caching on CI?), because different features actually generates different libraries and executables. I could followup with potential caching capability, but haven't seen a quick solution.
+ It's still acceptable CI speed from my perspective, could also try to parallelize GCS/S3/normal testing.
- Another is somewhat repeated unit tests; I don't see cargo solutions to only run unit tests annotated with one specific feature.
+ SO link: …
=> Add storage-gcs and storage-s3 into CI

src/moonlink/src/row/column_array_builder.rs, src/moonlink_connectors/src/pg_replicate/util.rs
There are a few issues with the current implementation. 
When building the Decimal128 type in `column_array_builder` we were silently dropping the precision and scale. It would then use the defaults of `(38, 10)`.
We are applying the scale to the `int_val` from `bigdecimal`, but this is already scaled. We can directly append the `int_val`.
We were using an incorrect mask when parsing `typmod` (although this seemed to have no impact)
We weren't using the scaled value in the `ArrayCell` case. 
Closes https://github.com/Mooncake-Labs/moonlink/issues/789
- Pass precision and scale when building `Decimal128Type
- Avoid double scale
- Fix mask
- Use scaled val in ArrayCell
=> Fix precision and scale for Decimal128

src/moonlink_connectors/src/replication_connection.rs
When replaying from `confirmed_flush_lsn` it's possible and valid to replay events from tables that have since been dropped. We should drop the `warn!` to avoid spamming. 
Closes https://github.com/Mooncake-Labs/moonlink/issues/787
- 
- 
-
=> Remove warn for missing schema

.devcontainer/setup.sh
Git hook is installed at moonlink repo, so it's persisted across devcontainers, if start command doesn't touch it.
In this PR I reinstall everything so installation is hermetic.
Closes https://github.com/Mooncake-Labs/moonlink/issues/810
=> Hermetic git hook installation

src/moonlink/src/storage/iceberg.rs, src/moonlink/src/storage/iceberg/catalog_utils.rs, src/moonlink/src/storage/iceberg/file_catalog.rs, src/moonlink/src/storage/iceberg/file_catalog_test.rs, src/moonlink/src/storage/iceberg/file_catalog_test_utils.rs, src/moonlink/src/storage/iceberg/gcs_test_utils.rs, src/moonlink/src/storage/iceberg/iceberg_table_manager.rs, src/moonlink/src/storage/iceberg/iceberg_table_syncer.rs, src/moonlink/src/storage/iceberg/io_utils.rs, src/moonlink/src/storage/iceberg/s3_test_utils.rs, src/moonlink/src/storage/iceberg/schema_utils.rs, src/moonlink/src/storage/iceberg/tests.rs, src/moonlink/src/storage/iceberg/utils.rs
On iceberg table creation, iceberg-rust somehow reassigns field id, which leads to inconsistency between parquet field id vs iceberg metadata field id, and fails duckdb query.
This PR workaround (before upstream has a better explanation or solution) by overwriting iceberg schema at catalog.
After this PR, duckdb query works for data files:
```sql
[/tmp/duckdb_iceberg] (hjiang/ignore-puffin-blob) 
vscode@54ca2001a79b$ ./build/reldebug/duckdb
DuckDB v1.3.2 (Ossivalis) 0b83e5d2f6
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D SELECT * FROM iceberg_scan('/tmp/.tmpFGSFJd/namespace/test_table/');
┌───────┬─────────┬───────┐
│  id   │  name   │  age  │
│ int32 │ varchar │ int32 │
├───────┼─────────┼───────┤
│ …
```
=> [storage] Overwrite iceberg-rust schema

src/moonlink/src/storage/iceberg/compaction_tests.rs, src/moonlink/src/storage/iceberg/state_tests.rs, src/moonlink/src/storage/iceberg/tests.rs, src/moonlink/src/storage/mooncake_table/data_file_state_tests.rs, src/moonlink/src/storage/mooncake_table/deletion_vector_puffin_state_tests.rs, src/moonlink/src/storage/mooncake_table/file_index_state_tests.rs, src/moonlink/src/storage/mooncake_table/table_operation_test_utils.rs, src/moonlink/src/storage/mooncake_table/test_utils.rs, src/moonlink/src/storage/mooncake_table/tests.rs
This PR adds a new API to flush synchronously, so when flush becomes async, we only have to modify one test util function, but not everywhere.
=> [minor] Provide a sync flush API for testing

src/moonlink/src/storage/iceberg/puffin_writer_proxy.rs
I suffer deletion failure when committing iceberg transaction due to insufficient permission, see https://github.com/Mooncake-Labs/moonlink/issues/840#issuecomment-3066016996
The issue is:
- To add customized puffin blob, I rewrite the existing manifest list file
- Implementation-wise, I did a delete + write, which requires "object deletion" + "object write" permission
- While directly overwrite only requires the later
=> [storage] Overwrite over delete for manifest list

.github/workflows/ci.yml
This PR parallelizes object storage test with normal unit tests, so CI runtime reduces from 6 minutes to 3 minutes.
=> [CI] Parallelize object storage tests

Cargo.lock, Cargo.toml, src/moonlink/src/storage/iceberg/file_catalog.rs, src/moonlink/src/storage/iceberg/iceberg_table_loader.rs, src/moonlink/src/storage/iceberg/iceberg_table_syncer.rs, src/moonlink/src/storage/iceberg/index.rs, src/moonlink/src/storage/iceberg/io_utils.rs, src/moonlink/src/storage/iceberg/table_property.rs, src/moonlink/src/storage/iceberg/utils.rs
iceberg-rust supports transaction retry internally, so I don't need to implement myself.
A few changes in the PR:
- Upgrade iceberg-rust to the latest version
- Update transaction commit logic and discard self-implemented retry
- Explicit propagate iceberg error, instead of using a util function
- Revisit and correctly mark errors as retryable or not
I tested the retry feature manually, and confirmed it works.
It's not easy to add unit tests because IO operations performed by opendal is not easy to mock.
Followup items would be rework on moonlink error type: https://github.com/Mooncake-Labs/moonlink/issues/852
Closes https://github.com/Mooncake-Labs/moonlink/issues/851
=> [storage] Rework retry transaction

src/moonlink/benches/bench_write.rs, src/moonlink/src/storage/iceberg/tests.rs, src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/disk_slice.rs, src/moonlink/src/storage/mooncake_table/table_operation_test_utils.rs, src/moonlink/src/table_handler.rs, src/moonlink/src/table_handler/test_utils.rs, src/moonlink/src/table_handler/tests.rs, src/moonlink/src/table_notify.rs
Spawn table flush as background task and send `TableEvent::FlushResult` on complete. There are some extra edge cases that need to be handled for the streaming case, so this is still handled by `flush_mem_slice`. We will unify these in a follow up PR. 
- Flush non streaming events in background
- Send `TableEvent::FlushResult`
- Add `set_flush_result` to set disk slices on complete
- Remove .await and update callers
=> Async flush non streaming

src/moonlink/src/table_handler.rs
No need to force create a mooncake snapshot, when already an iceberg snapshot ongoing.
Closes https://github.com/Mooncake-Labs/moonlink/issues/860
=> [storage] Avoid mooncake snapshot when iceberg ongoing

src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/table_handler.rs, src/moonlink/src/table_handler/tests.rs
Given flush is now async it's possible for LSNs to complete out of order. This is fine in the mooncake snapshot case but we need to guarantee order when creating iceberg snapshot. 
To do this we maintain a set of pending flush LSNs and only allow iceberg snapshot if there are no pending flush LSNs < requested LSN. 
This needs more integration/unit testing and will be done as part of https://github.com/Mooncake-Labs/moonlink/issues/857, but would like to get in for correctness. 
Closes https://github.com/Mooncake-Labs/moonlink/issues/858
- 
- 
-
=> Async flush snapshot order

src/moonlink/src/error.rs, src/moonlink/src/storage/mooncake_table/disk_slice.rs
We're using `tokio::sync::broadcast` in multiple places for synchronization, for example, index merge command, data compaction command, force snapshot command, etc.
One requirement for the receiver is cloneable type, for us is `moonlink::Result<()>`.
This PR achieves so by wrapping non-cloneable error types with `Arc`; no performance concern since it only happens on error path.
Closes https://github.com/Mooncake-Labs/moonlink/issues/869
=> Make moonlink error cloneable

src/moonlink/src/event_sync.rs, src/moonlink/src/storage/iceberg/table_event_manager.rs, src/moonlink/src/table_handler.rs, src/moonlink/src/table_handler/test_utils.rs, src/moonlink/src/table_handler/tests.rs, src/moonlink_backend/src/lib.rs, src/moonlink_connectors/src/pg_replicate/table_init.rs
This PR should be a noop code cleanup, since we use force table maintenance commands for only testing, debugging, and admin purpose, we don't need to spend effort on supporting concurrent force operations.
This PR further simplifies code, by using one channel for all three types of maintenance commands and completion notifications.
=> [storage] Use single channel for table maintenance

src/moonlink_backend/src/lib.rs, src/moonlink_backend/src/recovery_utils.rs, src/moonlink_backend/tests/common.rs, src/moonlink_backend/tests/test_backend.rs, src/moonlink_metadata_store/src/metadata_store_utils.rs, src/moonlink_metadata_store/src/sqlite/sqlite_metadata_store.rs
This PR is the initial step to integrate sqlite metadata storage into moonlink backend.
There're a lot testing hack in the PR, which I will clean up in the next PR, likely later today.
Related to https://github.com/Mooncake-Labs/moonlink/issues/884
=> [storage] [3/N] Initial sqlite metadata storage integration

Cargo.lock, Cargo.toml, src/moonlink/Cargo.toml, src/moonlink/src/storage/iceberg/file_catalog.rs
Currently s3 dependency is included in library and executable by default, but we only need to include under `storage-s3` feature.
=> Fix opendal s3 dependency

src/moonlink/src/storage/filesystem/accessor.rs, src/moonlink/src/storage/filesystem/accessor/base_filesystem_accessor.rs, src/moonlink/src/storage/filesystem/accessor/base_unbuffered_stream_writer.rs, src/moonlink/src/storage/filesystem/accessor/filesystem_accessor.rs, src/moonlink/src/storage/filesystem/accessor/operator_utils.rs, src/moonlink/src/storage/filesystem/accessor/unbuffered_stream_writer.rs, src/moonlink/src/storage/filesystem/gcs/tests.rs, src/moonlink/src/storage/filesystem/s3/tests.rs, src/moonlink/src/storage/filesystem/test_utils.rs, src/moonlink/src/storage/filesystem/test_utils/object_storage_test_utils.rs, src/moonlink/src/storage/filesystem/test_utils/writer_test_utils.rs
This PR implements stream writer, with no buffer support; mainly for WAL usage. Some key features:
- Append is non-blocking, so it could be used in eventloop
- User needs to explicit flush and close
Closes https://github.com/Mooncake-Labs/moonlink/issues/914
=> [storage] Implement unbuffered stream writer

src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/transaction_stream.rs, src/moonlink/src/table_handler.rs, src/moonlink/src/table_handler/tests.rs, src/moonlink/src/table_notify.rs, src/moonlink_connectors/src/pg_replicate/clients/postgres.rs, src/moonlink_connectors/src/pg_replicate/initial_copy.rs, src/moonlink_connectors/src/pg_replicate/postgres_source.rs, src/moonlink_connectors/src/replication_connection.rs
In order to better coordinate initial copy with incoming CDC events, we
1) Alter the publication with the new table
2) Fetch the `pg_current_wal_lsn` and start the `COPY TO` within the same transaction
3) Discard any events that have LSN < `pg_current_wal_lsn`
Since we add to the publication first and then start the copy we are at risk of having events both in the initial copy and sent as CDC event. We use the current_wal_lsn to dedup as it allows us to determine which events are already included in the initial copy. This was previously done in the reverse order, starting the initial copy and then altering the publication, however there is a window between when the copy starts and when the publication is altered where we may drop events. 
There are some other QOL improvements here such as …
=> Coordinate `pg_current_wal_lsn` with initial copy

src/moonlink/src/storage/iceberg/iceberg_table_loader.rs, src/moonlink/src/storage/iceberg/tests.rs, src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs, src/moonlink/src/storage/mooncake_table/table_snapshot.rs
Followup for https://github.com/Mooncake-Labs/moonlink/pull/943, which sets iceberg persistence results for WAL metadata.
To @lohpaul9 , I think the interface for iceberg persistence on WAL is (mostly) completely, two things you need to do:
- Set WAL metadata after you persist WAL to storage, whether local filesystem or object storage;
- On recovery, WAL metadata will be stored at current snapshot, you need to get it out and replay WAL.
=> [storage] Set wal metadata persistence result

src/moonlink/src/table_handler.rs, src/moonlink_backend/src/lib.rs
This PR canonicalizes relative moolink backend path into absolute path, so all paths built upon will be absolute one.
Likely needs some cleanups for path / pathbuf / string usage, I will followup.
=> [storage] Use absolute path everywhere

src/moonlink_backend/src/lib.rs
Make sure directory exists before canonlicalization.
Tested with pg_mooncake regression test on fresh devcontainer:
```sh
PASS setup 24ms
PASS partitioned_table 716ms
PASS sanity 690ms
passed=3 failed=0
```
=> [storage] Create directory before canonicalization

src/moonlink_backend/src/file_utils.rs
This PR improves subdirectories to be more readable.
Old filepath:
```sh
"/home/vscode/.pgrx/data-17/pg_mooncake/./temp/inmemory_public.r_16401_26574248.parquet"
```
New filepath:
```sh
"/home/vscode/.pgrx/data-17/pg_mooncake/temp/inmemory_public.r_16401_26285024.parquet"
```
Tested with pg_mooncake:
```sql
pg_mooncake (pid: 2724) =# DROP TABLE IF EXISTS c, r;
INSERT INTO r VALUES (1, 'a'), (2, 'b'), (3, 'c');
SELECT * FROM c;
NOTICE:  table "c" does not exist, skipping
NOTICE:  table "r" does not exist, skipping
DROP TABLE
ERROR:  extension "pg_mooncake" does not exist
CREATE TABLE
CALL
INSERT 0 3
a | b 
---+---
1 | a
2 | b
3 …
```
=> [storage] Improve subdirectory pathname

Cargo.lock, src/moonlink_backend/src/lib.rs, src/moonlink_backend/tests/common.rs, src/moonlink_backend/tests/test_backend.rs, src/moonlink_backend/tests/test_initial_copy.rs, src/moonlink_rpc/src/lib.rs, src/moonlink_service/Cargo.toml, src/moonlink_service/src/lib.rs, src/moonlink_service/src/main.rs
Moonlink backend implementation has been adapted in the previous PRs, this PR simply updates the backend interface to take metadata storage accessors from pg_mooncake.
Closes https://github.com/Mooncake-Labs/moonlink/issues/894
=> [storage] [5/N] Adapt moonlink backend interface

src/moonlink/src/storage/iceberg/tests.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs
This PR allows creating iceberg snapshot with only schema change, but no other table writes.
Closes https://github.com/Mooncake-Labs/moonlink/issues/961
=> [storage] Persist iceberg with no data files

src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs, src/moonlink/src/storage/mooncake_table/snapshot_cache_utils.rs, src/moonlink/src/storage/mooncake_table/snapshot_maintenance.rs, src/moonlink/src/storage/mooncake_table/snapshot_persistence.rs, src/moonlink/src/storage/mooncake_table/snapshot_read.rs, src/moonlink/src/storage/mooncake_table/snapshot_validation.rs
This PR is a no-op refactoring PR.
Motivation: I'm trying to do some refactoring on snapshot code, but find it painful to jump between functions (`snapshot.rs` is ~1500LOC).
In this PR, I split snapshot update logic into several parts, like persistence related, table maintenance related, etc.
Each of these split components are roughly 200-300 loc, which is much much easier to read.
I might consider further to split them into separate classes, but the obstacle is several util functions and common functions.
=> [minor] Extract out snapshot related functions

src/moonlink/Cargo.toml, src/moonlink/src/row/moonlink_row.rs, src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/table_creation_test_utils.rs, src/moonlink/src/storage/mooncake_table/table_snapshot.rs, src/moonlink/src/table_handler.rs, src/moonlink/src/table_handler/chaos_test.rs, src/moonlink/src/table_handler/test_utils.rs, src/moonlink/src/table_notify.rs, src/moonlink_connectors/src/pg_replicate/table_init.rs
This PR introduces the very basic chaos test to moonlink eventloop, which is known to lack extensive testing and hard to test due to timing issues.
As of now, it has discovered two bugs with table handler.
A few other things included in the PR:
- Make table events clone-able, so it could be sent to the replay channel;
- Update display formatter, otherwise it's very verbose and spammy to print file index out.
The implementation here is very coarse, quite a few TODO items; I pause it because it doesn't make sense to keep adding new feature when we already detected a few issues.
- Add snapshot read, to check whether read content is correct
- Check iceberg snapshot persistence
- Add streaming events
- Add table maintenance events
- Add chaos test into CI pipeline
Closes …
=> [storage] Add basic chaos test

src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/table_handler.rs, src/moonlink/src/table_handler/table_handler_state.rs, src/moonlink/src/table_handler/test_utils.rs, src/moonlink/src/table_notify.rs
... table only dropped and shutdown when no background task.
I found we only use shutdown in one test, so I remove it directly. We could add it back if necessary.
Also add assertion when we set special table events.
Closes https://github.com/Mooncake-Labs/moonlink/issues/970
=> [storage] Only drop table when no background task

src/moonlink/src/storage/mooncake_table/table_creation_test_utils.rs, src/moonlink/src/table_handler/chaos_test.rs, src/moonlink/src/union_read/read_state.rs
This PR adds snapshot read as a random event. Also a few fixes and refactors:
- Disable flush at commit, otherwise we could have two flushes with the same LSN;
- Replication LSN sender and last commit LSN sender should be kept, otherwise receiver side breaks on reception.
Closes https://github.com/Mooncake-Labs/moonlink/issues/991
=> [chaos] Add snapshot read to chaos test

src/moonlink/src/table_handler.rs, src/moonlink/src/table_handler/table_handler_state.rs, src/moonlink/src/table_handler/tests.rs, src/moonlink/src/table_notify.rs
This PR rework recovery on streaming. 
Current implementation doesn't work for streaming write, whose LSN is only assigned at commit/abort.
This PR keeps everything unchanged for non-streaming write, but not discard streaming write events until commit/abort.
=> [storage] Rework recovery on streaming

src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/batch_id_counter.rs, src/moonlink/src/storage/mooncake_table/data_batches.rs, src/moonlink/src/storage/mooncake_table/disk_slice.rs, src/moonlink/src/storage/mooncake_table/mem_slice.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs, src/moonlink/src/storage/mooncake_table/transaction_stream.rs
In order to support async flush batches from both streaming and non-streaming transactions will need to be added to the snapshot. in order to support this, we must ensure batch ids are globally unique across all transactions. 
Previous behavior would start the `batch_ids` at 0 for each new mem slice. This means streaming transaction batch ids overlap with other streaming transactions and the main table mem slice. 
We do this by splitting the `u64` range in two, assigning streaming transactions the range `[0, 21^63)` and non-streaming `[2^63, 2^64)`. It's important that streaming batch id's are always strictly less than non-streaming batch id's since we use the commit point from the non-streaming mem slice to determine read visibility. As soon as a streaming transaction commits it will …
=> Unique batch id allocations per table

src/moonlink/src/storage/mooncake_table/batch_id_counter.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs
We should use the same initial batch id in `SnapshotTableState` constructor as we do in `MemSlice` constructor to start with a 1-1 mapping. 
Also, during `finalize_batches` we should use the id from the actual incoming batches, not the shared counter since it's possible that the shared counter was further incremented. 
Closes https://github.com/Mooncake-Labs/moonlink/issues/1035
- 
- 
-
=> Coordinate batch id's between mem slice and snapshot 

src/moonlink/src/storage/mooncake_table/batch_id_counter.rs
`more_assertion` logs value on assertion failure.
=> [minor] Use more assertion for comparison

src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/table_creation_test_utils.rs, src/moonlink/src/storage/mooncake_table/table_operation_test_utils.rs
The bug is:
- Completed table maintenance (i.e. index merge and data compaction) triggers iceberg snapshot;
- Chances are that in the same iceberg snapshot persistence, it also contains deleted records. 
Closes https://github.com/Mooncake-Labs/moonlink/issues/1043
=> [storage] Fix flush LSN assertion

.github/workflows/ci.yml, src/moonlink/src/storage/mooncake_table/table_creation_test_utils.rs, src/moonlink/src/table_handler/chaos_test.rs
This PR does a few things:
- Add compaction to current chaos test suite;
- I have fixed all known issues, bump up injected events for better coverage;
- Add compaction to CI pipeline and bump up test timeout.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1022
=> [chaos] Add compaction to chaos test and CI

src/moonlink_metadata_store/src/postgres/sql/create_tables.sql, src/moonlink_metadata_store/src/sqlite/sql/create_tables.sql
This PR removes cardinality from metadata storage table, because moonlink manages metadata storage its own, instead of sharing with pg_mooncake.
**NOTICE:
I directly remove the schema row because moonlink hasn't been released officially.
Changing DB schema requires schema evolution in normal cases.**
=> [storage] Remove cardinality from metadata store

src/moonlink_connectors/src/pg_replicate/table_init.rs
As discussed offline, we don't want to bake source table's information in destination tables.
The impact is: later on iceberg tables will be stored under `<BASE>/default/<db_id.tdl_id>`
=> [storage] Update iceberg tables namespace

src/moonlink/src/storage/mooncake_table/table_creation_test_utils.rs, src/moonlink/src/table_handler/chaos_test.rs
This PR does three things for chaos test:
- Add initial streaming transaction into test suite;
- Increase default test event number from 1000 to 3000, which should finish within ~5 minutes
- Add a new test mode, with no background index merge and data compaction
Closes https://github.com/Mooncake-Labs/moonlink/issues/998
Closes https://github.com/Mooncake-Labs/moonlink/issues/1064
=> [chaos] Add streaming transaction to chaos test

src/moonlink/src/table_handler/chaos_test.rs
Streaming transactions are allowed to delete uncommitted rows, this PR allows certain pattern in chaos test.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1063
=> [chaos] Support deletion within stream txn

src/moonlink/src/storage/mooncake_table/snapshot.rs, src/moonlink/src/storage/mooncake_table/transaction_stream.rs, src/moonlink/src/table_handler/tests.rs
Uncommitted deletion log, though of type `Option`, actually holds the invariant that all records are valid.
So to unset an uncommitted record at abort, we should remove the element out instead of marking it as none.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1071
=> [storage] Fix stream abort

src/moonlink/src/table_handler/chaos_test.rs
This PR fill in the last gap for streaming transaction: abort and flush.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1062
Closes https://github.com/Mooncake-Labs/moonlink/issues/1067
=> [chaos] Add abort and flush to streaming transaction

src/moonlink/src/storage/filesystem/accessor.rs, src/moonlink/src/storage/filesystem/accessor/filesystem_accessor_wrapper.rs
This PR implements a wrapper around filesystem accessor, which provides random injected latency and error status.
I plan to integrate it with chaos test.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1079
=> [storage] Implement filesystem wrapper with error and latency

src/moonlink/src/storage/mooncake_table.rs
`0` is designated as `InvalidTransactionId` in the postgres implementation, so we can be sure this will never collide with a valid transaction id.
https://github.com/postgres/postgres/blob/d5b9b2d40262f57f58322ad49f8928fd4a492adb/src/include/access/transam.h#L31
Closes https://github.com/Mooncake-Labs/moonlink/issues/1088
- 
- 
-
=> Use 0 as sentinel value for `INITIAL_COPY_XACT_ID`

.github/workflows/ci.yml, src/moonlink/src/storage/mooncake_table/table_creation_test_utils.rs, src/moonlink/src/table_handler/chaos_test.rs
This PR adds object storage to chaos test, we need a way to check whether local/remote files are properly handled.
For example, we use `mmap` for index blocks, need to make sure it's on local filesystem.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1102
=> [chaos] Add object storage to chaos test

src/moonlink/src/storage/filesystem/accessor/filesystem_accessor_chaos_wrapper.rs, src/moonlink/src/storage/filesystem/filesystem_config.rs, src/moonlink/src/storage/mooncake_table/table_creation_test_utils.rs
When working on backend config (https://github.com/Mooncake-Labs/moonlink/pull/965), if filesystem config is serializable it would make table creation config much easier.
=> [storage] Update chaos wrapper option

src/moonlink/src/lib.rs, src/moonlink/src/storage.rs, src/moonlink/src/storage/compaction/compaction_config.rs, src/moonlink/src/storage/index/index_merge_config.rs, src/moonlink/src/storage/mooncake_table.rs, src/moonlink_backend/src/lib.rs, src/moonlink_backend/src/recovery_utils.rs, src/moonlink_metadata_store/src/config_utils.rs
This is sth I missed, essentially when store table metadata, we should not only persist iceberg related configs, but also mooncake table related configs.
For example, people won't expect before recovery index merge enabled, but disabled after recovery.
How I tested:
```sql
pg_mooncake (pid: 5983) =# DROP EXTENSION IF EXISTS pg_mooncake CASCADE;
INSERT INTO r SELECT a, 'val_' || a FROM generate_series(1, 250000) AS a;
SELECT count(*) FROM c;
DELETE FROM r WHERE a % 2 = 0;
SELECT count(*) FROM c;
NOTICE:  extension "pg_mooncake" does not exist, skipping
DROP EXTENSION
NOTICE:  table "r" does not exist, skipping
DROP TABLE
CREATE TABLE
CALL …
```
=> [storage] Fix mooncake table config store

src/moonlink/src/storage/mooncake_table/table_operation_test_utils.rs, src/moonlink/src/table_handler.rs, src/moonlink/src/table_notify.rs, src/moonlink/src/union_read/read_state.rs
which prevents chaos test replay system to be too verbose, essentially a no-op change
Closes https://github.com/Mooncake-Labs/moonlink/issues/1123
=> [minor] Update pinned cache handle formatting

src/moonlink/src/storage/compaction/compaction_config.rs, src/moonlink/src/storage/iceberg/compaction_tests.rs, src/moonlink/src/storage/iceberg/tests.rs, src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/snapshot_maintenance.rs, src/moonlink/src/storage/mooncake_table/table_creation_test_utils.rs, src/moonlink/src/table_handler/tests.rs
- enable data compaction by default, which has been verified by chaos test for several days
- set upper limit for data files to compact, to prevent excessively long compaction activities
Closes https://github.com/Mooncake-Labs/moonlink/issues/1069
Closes https://github.com/Mooncake-Labs/moonlink/issues/900
=> [storage] Enable compaction and set max files

src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/data_file_state_tests.rs, src/moonlink/src/storage/mooncake_table/deletion_vector_puffin_state_tests.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs, src/moonlink/src/storage/mooncake_table/snapshot_cache_utils.rs, src/moonlink/src/storage/mooncake_table/snapshot_read.rs, src/moonlink/src/storage/mooncake_table/snapshot_read_output.rs, src/moonlink/src/storage/mooncake_table/table_operation_test_utils.rs, src/moonlink/src/table_handler.rs, src/moonlink/src/table_handler/chaos_test.rs, src/moonlink/src/table_notify.rs, src/moonlink/src/union_read/read_state.rs, src/moonlink/src/union_read/read_state_manager.rs
Error message 
```sh
thread 'tokio-runtime-worker' panicked at src/moonlink/src/union_read/read_state.rs:45:22:
called `Result::unwrap()` on an `Err` value: SendError { .. }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test table_handler::chaos_test::test_chaos_with_data_compaction ... ok
```
Currently the completed read request is sent back to table handler eventloop to unreference cache handles, but it's not synchronized with events like drop table, which leads to sent failure.
A few proposals to resolve:
(1) Read state takes a Arc<Receiver>, so event sending is always valid
The downside is when reading from receiver it requires mutability, so have to play with some rust tricks here.
(2) Put unreference logic in read state destruction, so there's no …
=> [storage] Avoid sync completed read on eventloop

src/moonlink/src/storage/iceberg.rs, src/moonlink/src/storage/iceberg/data_file_manifest_manager.rs, src/moonlink/src/storage/iceberg/deletion_vector_manifest_manager.rs, src/moonlink/src/storage/iceberg/file_catalog.rs, src/moonlink/src/storage/iceberg/file_index_manifest_manager.rs, src/moonlink/src/storage/iceberg/iceberg_table_syncer.rs, src/moonlink/src/storage/iceberg/manifest_utils.rs, src/moonlink/src/storage/iceberg/moonlink_catalog.rs, src/moonlink/src/storage/iceberg/puffin_writer_proxy.rs
All the iceberg hacky operations (which are not supported by iceberg-rust) lives here, current code mixes data file, deletion vector, and file index into a giant function, which makes me hard to read through.
This PR is essentially a no-op change, which splits it into several structs and handle them separately.
Closes https://github.com/Mooncake-Labs/moonlink/issues/814
=> [storage] Refactor manifest write

src/moonlink/src/storage/iceberg/file_catalog.rs, src/moonlink/src/storage/iceberg/file_index_manifest_manager.rs, src/moonlink/src/storage/iceberg/iceberg_table_syncer.rs, src/moonlink/src/storage/iceberg/moonlink_catalog.rs, src/moonlink/src/storage/iceberg/puffin_writer_proxy.rs
Since iceberg-rust doesn't support customized puffin blob and deletion vector for now, the hack I did is manually operate on manifest files before transaction commit.
Current implementation is not ideal, it rewrites deletion vector and file index manifest files, whether or not there're updates.
This PR avoid so if possible, no behavior change.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1158
=> [storage] Avoid unnecessary manifest file rewrite

src/moonlink/src/storage/mooncake_table/persistence_buffer.rs, src/moonlink/src/storage/mooncake_table_config.rs, src/moonlink/src/table_handler/tests.rs
This is a no-op change PR.
Currently iceberg persistence threshold is hard-coded to be 1, I made it a config param so we could tune for perf before release.
=> [storage] Make configurable iceberg persistence threshold

src/moonlink/benches/bench_write.rs, src/moonlink/src/storage/index.rs, src/moonlink/src/storage/mooncake_table/delete_vector.rs, src/moonlink/src/storage/mooncake_table/disk_slice.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs, src/moonlink/src/storage/mooncake_table/tests.rs, src/moonlink/src/storage/mooncake_table/transaction_stream.rs, src/moonlink/src/table_handler.rs
Removes the assumption that flush happens in the foreground. Adds state to `TransactionStreamState` or `next_snapshot_task` to ensure transaction visibility during flush. Note that flush is still done in the foreground here, this will be changed in a future PR.
In general, each time we flush we need to add the current batches and indices to the stream state. When a flush finishes, we remove this state. On commit we move any remaining batches and indices from the `TransactionStreamState` into the snapshot task to ensure it is visible. When the flush finishes, we add its disk slice to the snapshot task. 
Closes https://github.com/Mooncake-Labs/moonlink/issues/1032
- 
- 
-
=> Add stream state to snapshot task

src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/iceberg_persisted_records.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs, src/moonlink/src/storage/mooncake_table/transaction_stream.rs
I met not-easy-to-repro error, which shows less committed records at snapshot read.
This PR adds assertion for mooncake snapshot on expected disk file count.
=> [storage] Validate snapshot disk file count

src/moonlink/src/storage/iceberg/iceberg_table_loader.rs, src/moonlink/src/storage/iceberg/iceberg_table_manager.rs, src/moonlink/src/storage/iceberg/iceberg_table_syncer.rs
`persisted_puffin_blob` field is not used in iceberg table manager, the only deletion records required is batch deletion vector, which for merge operation on each persistence.
It's also bad to hold at iceberg layer, since inside puffin blob ref, there's cached file handle which holds reference counts.
=> [storage] Remove puffin blob from iceberg table manager

Cargo.lock, src/moonlink/Cargo.toml, src/moonlink/src/table_handler/chaos_test.rs
Even if table events are not deterministic, we could still add logging on random seeds so it has better chance to repro.
=> [chaos] Log random seed

Cargo.lock, Cargo.toml
Upgrade the `roaring` version from `0.10` to `0.11` while `0.11.2` is released (see [here](https://github.com/RoaringBitmap/roaring-rs/releases/tag/v0.11.2))
Closes #371
- `roaring` version from `0.10` to `0.11`
=> [Build] upgrade roaring to 0.11

src/moonlink/src/storage/compaction/compaction_config.rs, src/moonlink/src/storage/iceberg/compaction_tests.rs, src/moonlink/src/storage/iceberg/iceberg_table_loader.rs, src/moonlink/src/storage/iceberg/tests.rs, src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs, src/moonlink/src/storage/mooncake_table/snapshot_maintenance.rs, src/moonlink/src/storage/mooncake_table/table_creation_test_utils.rs, src/moonlink/src/storage/mooncake_table/transaction_stream.rs, src/moonlink/src/table_handler/tests.rs, src/moonlink_metadata_store/src/config_utils.rs
Current compaction strategy is bad: for large files (which are over configured size), it still takes part in compaction as long as there're deleted rows.
This PR adds a percentage-based threshold to guard against unnecessary compaction.
Several policies considered:
- File size based: it's hard to calculate the size of deleted or undeleted rows
- Row number based (by absolute value): it treats differently for large objects and small objects
+ For example, for data files with large objects, it could never reach the row number threshold even though half of the storage space could be optimized
- Deletion percentage based: the ideal situation is deletion percentage indicates file size percentage
+ For example, 50% rows deleted indicates >50% of the storage space could be freed after compaction …
=> [storage] Compaction by deleted rows

src/moonlink/src/table_handler/chaos_test.rs
Have a few chaos timeout issues in the past several days, so reduce event counts to make sure it finishes within 10 min.
Testing with no background maintenance is the one who consumes most of the time.
Eg for timeout job: https://github.com/Mooncake-Labs/moonlink/actions/runs/16705140530/job/47282113642
=> [chaos] Reduce event count for chaos test

Cargo.lock, Cargo.toml, deny.toml
As titled, sync iceberg-rust and roaring bitmap dependency, to avoid one crate appearing multiple times.
=> [deps] Sync iceberg-rust and roaring dependency

src/moonlink/src/storage/iceberg/iceberg_table_syncer.rs, src/moonlink/src/storage/iceberg/manifest_utils.rs
I notices chaos test timed out too frequently these days, disable some expensive sanity check which I added recently.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1207
=> [chaos] Disable some sanity iceberg check

src/moonlink/src/storage/iceberg/compaction_tests.rs, src/moonlink/src/storage/iceberg/iceberg_table_loader.rs, src/moonlink/src/storage/iceberg/state_tests.rs, src/moonlink/src/storage/iceberg/tests.rs, src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs, src/moonlink/src/storage/mooncake_table/snapshot_read.rs, src/moonlink/src/storage/mooncake_table/snapshot_validation.rs, src/moonlink/src/table_handler/tests.rs
Rename from `data_file_flush_lsn` to `flush_lsn`; the former is not a correct naming, we also flush with no data file involved when force snapshot.
=> [minor] Rename flush LSN

.dockerignore, Dockerfile, cloud/gcp/moonlink_service.yaml
This PR adds initial dockerfile and kubernetes deployment on GKE.
I have checked: with local postgres, moonlink deployed in the same pod performs normally: able to send events to mooncake table, able to persist to iceberg table.
Commands to create docker image and upload to GAR:
```sh
(myenv) hjiang@hjiangs-MacBook-Pro Downloads % docker build --platform linux/amd64 -t my-rust-cli:latest .
(myenv) hjiang@hjiangs-MacBook-Pro Downloads % docker tag my-rust-cli:latest us-west-1-docker.pkg.dev/coral-ring-465417-r0/moonlink-standalone-experiment/my-rust-cli:latest
(myenv) hjiang@hjiangs-MacBook-Pro Downloads % docker push us-west1-docker.pkg.dev/coral-ring-465417-r0/moonlink-standalone-experiment/my-rust-cli:latest 
```
=> [deploy] Initial deployment for standalone moonlink

src/moonlink/src/storage/mooncake_table/data_batches.rs, src/moonlink/src/storage/mooncake_table/mem_slice.rs
Verb + noun functions should all declare `must_use` otherwise it's easy to forget checking succeed or not.
=> [storage] Mark more fields as must_use

src/moonlink/benches/bench_write.rs, src/moonlink/benches/microbench_write_mooncake_table.rs, src/moonlink/src/storage/filesystem/accessor/filesystem_accessor.rs, src/moonlink/src/storage/filesystem/accessor/filesystem_accessor_chaos_wrapper.rs, src/moonlink/src/storage/filesystem/accessor/operator_utils.rs, src/moonlink/src/storage/filesystem/accessor/unbuffered_stream_writer.rs, src/moonlink/src/storage/filesystem/accessor_config.rs, src/moonlink/src/storage/filesystem/storage_config.rs, src/moonlink/src/storage/iceberg/file_catalog_test.rs, src/moonlink/src/storage/iceberg/file_catalog_test_utils.rs, src/moonlink/src/storage/iceberg/iceberg_table_config.rs, src/moonlink/src/storage/mooncake_table/file_index_state_tests.rs, src/moonlink/src/storage/mooncake_table/table_creation_test_utils.rs, src/moonlink/src/storage/mooncake_table/test_utils.rs, src/moonlink/src/storage/wal.rs, src/moonlink/src/table_handler/chaos_test.rs, src/moonlink/src/table_handler/test_utils.rs, src/moonlink_backend/src/table_config.rs, src/moonlink_backend/tests/common.rs, src/moonlink_metadata_store/src/config_utils.rs, src/moonlink_metadata_store/src/sqlite/tests.rs, src/moonlink_metadata_store/tests/common/test_utils.rs
This PR exposes atomic write option for local filesystem, which WAL might need.
Exposed interface resembles the one by opendal: provide an optional field and by default off.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1235
Closes https://github.com/Mooncake-Labs/moonlink/issues/1234
=> [storage] Provide option for atomic write on local filesystem

src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/delete_vector.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs, src/moonlink/src/storage/mooncake_table/tests.rs, src/moonlink/src/storage/mooncake_table/transaction_stream.rs, src/moonlink/src/table_handler/tests.rs
In the case that a streaming transaction deletes from its own mem slice, we apply the deletion [inline](https://github.com/Mooncake-Labs/moonlink/blob/1f5f369c20e0d587d535eedca379a2385f4fb47b/src/moonlink/src/storage/mooncake_table/transaction_stream.rs#L178) and then filter the batch when preparing the disk slice/commit the transaction.
This is incorrect. We are not able to filter the batches at this point since its possible we have created deletion vectors that depend on the row_ids of these batches. However, we also currently don't persist deletion vector information when adding batches to snapshot task, so if we don't filter the batches we will lose deletion information.
The correct approach is to maintain deletion vector information when adding to snapshot task in the streaming case, …
=> hold deletion vectors for streaming batches in snapshot task

cloud/gcp/deployment/moonlink_deployment.yaml, cloud/gcp/service/moonlink_service.yaml
This PR deploys moonlink service, which exposes data server endpoint.
I checked with curl and confirm it works to access cache files.
```sh
root@moonlink-deployment-75746db7d7-nlnqs:/# ls -lR ls /usr/share/nginx/html
ls: cannot access 'ls': No such file or directory
/usr/share/nginx/html:
total 4
drwxr-xr-x 2 root root 4096 Aug  6 22:57 read_cache
/usr/share/nginx/html/read_cache:
total 4
-rw-r--r-- 1 root root 11 Aug  6 22:57 helloworld
```
curl request and response:
```sh
(myenv) hjiang@hjiangs-MacBook-Pro moonlink % curl http://<IP>:8080/read_cache/helloworld
helloworld
```
Closes https://github.com/Mooncake-Labs/moonlink/issues/1230
Closes https://github.com/Mooncake-Labs/moonlink/issues/1222
=> [deployment] Service for moonlink and data server

src/moonlink/src/row/column_array_builder.rs
Add RowType::Struct to Arrow Struct conversion(currently only support primitive type fields, excluding nested struct and list field)
Closes https://github.com/Mooncake-Labs/moonlink/issues/1227
- src/moonlink/src/row/column_array_builder.rs: add RowType::Struct to Arrow Struct conversion(currently only support primitive type fields, excluding nested struct and list field)
=> [feature] Add support for struct data type in ColumnArrayBuilder - primitive type fields

src/moonlink_service/src/error.rs, src/moonlink_service/src/lib.rs, src/moonlink_service/src/rest_api.rs
Certain things I would like to followup later inside of termination handler, a few examples:
- create iceberg snapshot if possible
- flush stats (after I add observability metrics)
=> [REST] Enable graceful shutdown for REST API server

src/moonlink/benches/bench_write.rs, src/moonlink/src/storage/iceberg/tests.rs, src/moonlink/src/storage/index.rs, src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/batch_id_counter.rs, src/moonlink/src/storage/mooncake_table/data_batches.rs, src/moonlink/src/storage/mooncake_table/data_file_state_tests.rs, src/moonlink/src/storage/mooncake_table/deletion_vector_puffin_state_tests.rs, src/moonlink/src/storage/mooncake_table/disk_slice.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs, src/moonlink/src/storage/mooncake_table/snapshot_validation.rs, src/moonlink/src/storage/mooncake_table/table_creation_test_utils.rs, src/moonlink/src/storage/mooncake_table/table_operation_test_utils.rs, src/moonlink/src/storage/mooncake_table/tests.rs, src/moonlink/src/storage/mooncake_table/transaction_stream.rs, src/moonlink/src/table_handler.rs, src/moonlink/src/table_handler/failure_tests.rs, src/moonlink/src/table_handler/table_handler_state.rs, src/moonlink/src/table_handler/tests.rs, src/moonlink/src/table_notify.rs
Final PR for implementing asynchronous flush events for both streaming and non-streaming transactions.
Previous PRs: 
Use globally unique batch ids: https://github.com/Mooncake-Labs/moonlink/pull/1031
Add streaming and non-streaming state to same snapshot: https://github.com/Mooncake-Labs/moonlink/pull/1100
In this PR, we change all table flush to be asynchronous. We spawn the flush as background task and send `TableEvent::FlushResult` on complete, at which point we apply the results of the flush. Given we may have multiple concurrent flushes at once we track a queue of pending flush LSNs. Before iceberg snapshot we ensure there is no pending LSN less than the LSN we want to persist at. 
Closes https://github.com/Mooncake-Labs/moonlink/issues/234
- 
- 
-
=> [AsyncFlush 3/3] Use asynchronous flush

Dockerfile, cloud/gcp/deployment/moonlink_deployment.yaml, cloud/gcp/service/moonlink_service.yaml, cloud/gcp/service/postgres_service.yaml, src/moonlink_service/examples/rest_api_demo.rs, src/moonlink_service/src/lib.rs, src/moonlink_service/src/main.rs, src/moonlink_service/src/rpc_server.rs
This PR implements an optional TCP server, which allows pg_mooncake to connect to moonlink standalone deployment via TCP request and response, not only unix domain socket.
This PR is a no-op to production env, TCP server is by default disabled.
Initial test setup:
https://docs.google.com/document/d/1h1UUKSJDpsUk6BUbVP9sEAo1x8vwKIgWz9T_glY7M8M/edit?usp=sharing
- I confirmed table creation and snapshot creation works
- Haven't figured out on scan table
=> [deployment] Implement moonlink TCP server

cloud/gcp/deployment/moonlink_deployment.yaml, src/moonlink/src/lib.rs, src/moonlink/src/storage/mooncake_table/data_file_state_tests.rs, src/moonlink/src/storage/mooncake_table/deletion_vector_puffin_state_tests.rs, src/moonlink/src/storage/mooncake_table/snapshot_read_output.rs, src/moonlink/src/storage/mooncake_table/table_operation_test_utils.rs, src/moonlink/src/table_handler/chaos_test.rs, src/moonlink/src/table_handler/test_utils.rs, src/moonlink/src/union_read.rs, src/moonlink/src/union_read/read_state.rs, src/moonlink/src/union_read/read_state_manager.rs, src/moonlink_backend/src/lib.rs, src/moonlink_backend/src/recovery_utils.rs, src/moonlink_backend/tests/common.rs, src/moonlink_backend/tests/test_backend.rs, src/moonlink_connectors/src/pg_replicate.rs, src/moonlink_connectors/src/pg_replicate/table_init.rs, src/moonlink_connectors/src/replication_connection.rs, src/moonlink_connectors/src/replication_manager.rs, src/moonlink_service/examples/rest_api_demo.rs, src/moonlink_service/src/lib.rs, src/moonlink_service/src/main.rs
When moonlink is deployed standalone, all requests are split into two catagories: control plane and data plane.
- control plane requests are served by moonlink server TCP connections
- data plane requests are served by nginx data server via HTTP connections
The roundtrip looks like:
- pg_mooncake asks control plane for table files
- duckdb requests content for these file via data plane
- so all these table files needs to be remapped: (1) with http scheme, so duckdb-httpfs handles certain request; (2) update filepath so data server could access
Standalone testing setup:
- remote postgres deployed at GCP
- remote moonlink and nginx deployment
- local devcontainer postgres with pg_mooncake
Standalone testing result (at pg_mooncake side):
```sh
pg_mooncake (pid: 1547) =# CREATE EXTENSION …
```
=> [storage] Perform filepath remap on read state

src/moonlink/src/table_handler.rs
Replace the loop { tokio::select! { … } } event loop with a single-source receive loop:
Before:
```
loop {
tokio::select! {
// Process events from the queue
Some(event) = event_receiver.recv() => {
```
After: 
```
while let Some(event) = event_receiver.recv().await {
...
}
```
Move the shutdown error handling to the end of the loop:
```
if let Err(e) = table.shutdown().await {
error!(error = %e, "failed to shutdown table");
}
debug!("all event senders dropped, shutting down table handler");
```
=> Simplified event loop

src/moonlink/src/storage/parquet_utils.rs
Configure default Parquet writer settings.
Related https://github.com/Mooncake-Labs/moonlink/issues/525
```
.set_compression(DEFAULT_COMPRESSION)
.set_dictionary_enabled(true)
.set_dictionary_page_size_limit(DEFAULT_ROW_GROUP_SIZE / 100)
// .set_bloom_filter_enabled(true)
// .set_bloom_filter_fpp(0.01)
.set_writer_version(parquet::file::properties::WriterVersion::PARQUET_1_0)
```
Not found in setting options:
```
ZStdFileSystem::DefaultCompressionLevel() /*compression_level*/, 
true /*debug_use_openssl*/,
```
Enables these changes may cause the following integration test error..
```
// .set_bloom_filter_enabled(true)
// .set_bloom_filter_fpp(0.01)
```
```
test storage::iceberg::compaction_tests::test_compaction_1_1_1 ... FAILED
test …
```
=> Configure default Parquet writer settings

cloud/gcp/dev/deployment/moonlink_deployment.yaml, cloud/gcp/dev/service/moonlink_service.yaml, cloud/gcp/prod/deployment/moonlink_deployment.yaml, cloud/gcp/prod/service/moonlink_service.yaml, cloud/gcp/staging/deployment/moonlink_deployment.yaml, cloud/gcp/staging/service/moonlink_service.yaml, src/moonlink_service/src/lib.rs
This PR setups the readiness probe for deployment and expose HTTP endpoint for later uptime check usage.
How I tested:
- I deployed to GKE, deployment startup successfully with no issue
- Checked with exposed HTTP endpoint
```sh
(myenv) hjiang@hjiangs-MacBook-Pro moonlink % curl http://34.168.174.231:5050/ready                                      
ready%      
```
Closes https://github.com/Mooncake-Labs/moonlink/issues/1259
=> [deployment] Setup readiness probe

src/moonlink/src/storage/filesystem/accessor/chaos_generator.rs, src/moonlink/src/storage/filesystem/accessor/filesystem_accessor_chaos_wrapper.rs, src/moonlink/src/storage/filesystem/accessor_config.rs, src/moonlink/src/storage/mooncake_table/table_creation_test_utils.rs, src/moonlink/src/table_handler/chaos_test.rs
This PR fixes a non-deterministic cause of chaos test: filesystem chaos layer is using its own random seed, we should pass the same seed everywhere.
=> [chaos] Fix non-deterministic filesystem accessor chaos

.github/workflows/ci.yml, src/moonlink/src/lib.rs, src/moonlink/src/storage.rs, src/moonlink/src/storage/iceberg/tests.rs, src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/disk_slice.rs, src/moonlink/src/storage/mooncake_table/table_creation_test_utils.rs, src/moonlink/src/storage/mooncake_table/transaction_stream.rs, src/moonlink/src/storage/mooncake_table_config.rs, src/moonlink/src/table_handler/chaos_test.rs, src/moonlink/src/table_handler/tests.rs, src/moonlink_metadata_store/src/config_utils.rs
This PR adds intentional random timeout to disk slice write, so we could trigger late-arriving completed disk write easier.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1326
=> [chaos] Add chaos config for disk slice writer

src/moonlink_connectors/src/rest_ingest/json_converter.rs
Support bool/i64/f32/f64 for JsonToMooklinkConverter
ref https://github.com/Mooncake-Labs/moonlink/issues/1282
- Add type conversion for those data types.
- Update test case to reflect the changes.
Not sure if this works end-to-end; would be great if there's some pointer on where I can find e2e tests for those ingestions.
=> more data types on json ingestion

src/moonlink/src/row/moonlink_type.rs
Add comment to clarify timestamp types -> int types conversion, a few key points:
- For timestamp types, which timezone do we convert to?
- For all time/timestamp types, which time unit do we use?
The comment illustrates the implementation at https://github.com/Mooncake-Labs/moonlink/blob/70f102a173cbf8cc536d7d8acfac3e0126ad614a/src/moonlink_connectors/src/pg_replicate/util.rs#L260-L285, so we could have a unified definition across the codebase.
=> Add comment on timestamp type conversion

.pre-commit-config.yaml
I searched for repositories such as **datafusion-ray** and **arrow-rs** and found that most of them don’t use the `--fix` option. Removing it can save us around 12 seconds during Clippy checks.
The total time for the Clippy check is about 120 seconds, with the bottleneck being dependency build time (~100 seconds).  
By removing `--all-targets --all-features`, the total time is reduced to about 43 seconds. (This is the approach used by **arrow-rs**.)  I’ll leave the decision on this change to the repository owner.
Related: https://github.com/Mooncake-Labs/moonlink/issues/1304
- Remove Clippy `--fix` from pre-commit hook
=> Remove clippy fix

src/moonlink/src/storage/cache/object_storage/base_cache.rs, src/moonlink/src/storage/cache/object_storage/cache_handle.rs, src/moonlink/src/storage/cache/object_storage/object_storage_cache.rs
Previously, Moonlink used raw SmallVec<[String; 1]> to represent paths scheduled for deletion, which wasn’t self-descriptive. This change introduces a type EvictedFiles = SmallVec<[String; INLINE_FILE_SLOTS]>; alias and applies it throughout the codebase for clearer intent and easier future capacity tuning.
Closes #1312
- alias smallvec to evict files
=> chore: alias smallvec to evict files

src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/replay.rs, src/moonlink/src/storage/mooncake_table/replay/event_id_assigner.rs, src/moonlink/src/storage/mooncake_table/replay/replay_events.rs, src/moonlink/src/storage/storage_utils.rs
This PR is the first part to reproducible mooncake table operations.
Context:
- We decide to record events at mooncake table layer, instead of table handler layer due to higher ROI
+ Table handler layer has much more concurrency issues to handle, it's much easier for mooncake table
- To persist and replay table events, this PR defines corresponding structs for serde
Disclaimer: this PR is a no-op change, I will followup with another one to integrate with mooncake table.
Send out a PR simply to avoid giant PR, which is hard for (self) review.
=> [storage] Define serializable replay table event

Cargo.lock, src/moonlink_connectors/Cargo.toml, src/moonlink_connectors/src/rest_ingest.rs, src/moonlink_connectors/src/rest_ingest/datetime_utils.rs, src/moonlink_connectors/src/rest_ingest/json_converter.rs
Type support for timestamp in json to moonlink row converter
Closes https://github.com/Mooncake-Labs/moonlink/issues/1284
- Add a datatime_utils file with different time string parsing and basic timestamp testing
- make json converter to support Date32, Time64 and Timetamp and add some edge case testing
=> feat: type support for timestamp in json to moonlink row converter

.github/workflows/ci.yml
moonlink-datafusion is taking 5min to build on CI, which exceeds all others crate's build + tests.
Currently the crate doesn't contain ANY unit test, we could add it back when the author adds any.
=> [CI] Split CI crate test

.github/workflows/ci.yml
This PR uses mold as the default linker on CI, and enable rust-cache for all rust-based tests.
Some benchmarks for mold, 10% improvement for build stage
- the most stable part in CI is unit test, all others are built based on random events
- prev-1: 2m 38s
+ https://github.com/Mooncake-Labs/moonlink/actions/runs/16907359960/job/47900133709
- prev-2: 2m 36s
+ https://github.com/Mooncake-Labs/moonlink/actions/runs/16905391171/job/47893853718
- prev-3: 2m 44s
+ https://github.com/Mooncake-Labs/moonlink/actions/runs/16904814138/job/47892007192
- now-1: 2m 19s
+ https://github.com/Mooncake-Labs/moonlink/actions/runs/16917421042/job/47934749480?pr=1389
- now-2: 2m 21s
+ https://github.com/Mooncake-Labs/moonlink/actions/runs/16917421042/job/47935555770
=> [CI] Use mold and cache

src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/transaction_stream.rs, src/moonlink/src/table_handler/chaos_test.rs
Found I missed flush for stream one, add it in the PR.
Also checked flush initiation # == flush completion #
=> [chaos] Add flush table event for stream transaction

src/moonlink/src/table_handler/chaos_test.rs
This PR allows repeated update for the same row in the streaming transaction.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1399
=> [chaos] Allow repeated update in streaming transaction

src/moonlink/src/storage/mooncake_table/snapshot.rs
We are incorrectly assuming that `committed_deletion_log` is LSN ordered. We now have multiple producers appending to this log (streaming and non-streaming transactions) therefore we cannot assume it is by default ordered by increasing LSN.
When computing the cut point we should iterate the entire log and filter rows that don't meet the condition rather than scanning for some partition point.
- 
- 
-
=> Fix remap partition

src/moonlink/src/table_handler/chaos_test.rs
This PR allows chaos test to delete updated rows, if they're not deleted yet.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1400
=> [chaos] Streaming transaction allow delete updated rows

src/moonlink/src/table_handler.rs
The table handler’s event queue is a bounded `mpsc::channel` with capacity `100`. If the handler processes events slower than pg produces them, the replication sink must `.await` available capacity, stalling ingestion. When considering 100M inserts our current channel size is extremely small. 
Did some very rough testing and the max ingest rate I saw during 100M insert was around 0.7M events/s. At channel size of `2^15` that should absorb ~47ms of stall time on the moonlink side, which should be more than enough while still keeping the in-memory footprint reasonable in the event that the queue fills (it should really never). 
- 
- 
-
=> Increase mpsc channel size

src/moonlink_backend/tests/test_initial_copy.rs
Fixed failing test:
```
vscode ➜ /workspaces/moonlink (ba3267d ✗) $ RUST_BACKTRACE='1' cargo test --package moonlink_backend --test test_initial_copy -- tests::test_initial_copy_handles_inserts_during_copy --exact --show-output 
Finished `test` profile [unoptimized + debuginfo] target(s) in 0.34s
Running tests/test_initial_copy.rs (target/debug/deps/test_initial_copy-4974a560a7f54ba6)
running 1 test
thread 'tests::test_initial_copy_handles_inserts_during_copy' panicked at src/moonlink_backend/tests/test_initial_copy.rs:210:18:
called `Result::unwrap()` on an `Err` value: MoonlinkConnectorError { source: TableNotFound("5.0") }
stack backtrace:
```
Closes #920
=> fixed initial copy insert test

src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/table_operation_test_utils.rs, src/moonlink/src/storage/mooncake_table/test_utils_commons.rs, src/moonlink/src/storage/mooncake_table/tests.rs, src/moonlink/src/storage/mooncake_table/transaction_stream.rs, src/moonlink/src/table_handler.rs, src/moonlink/src/table_handler/chaos_replay.rs
All events recording should happen at mooncake table level, instead of in the background threads, otherwise it's still non-deterministic.
Also remove the event recording for empty flush, which doesn't do any updates to mooncake table.
Issue created to add a unit test for replay program: https://github.com/Mooncake-Labs/moonlink/issues/1448
=> [chaos] Move table events record to mooncake table

src/moonlink/src/storage/compaction/compactor.rs, src/moonlink/src/storage/compaction/table_compaction.rs, src/moonlink/src/storage/compaction/tests.rs, src/moonlink/src/storage/iceberg/state_tests.rs, src/moonlink/src/storage/iceberg/tests.rs, src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/replay/event_id_assigner.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs, src/moonlink/src/storage/mooncake_table/snapshot_maintenance.rs, src/moonlink/src/storage/mooncake_table/table_operation_test_utils.rs, src/moonlink/src/storage/mooncake_table/table_snapshot.rs, src/moonlink/src/storage/mooncake_table/tests.rs, src/moonlink/src/storage/snapshot_options.rs, src/moonlink/src/table_handler.rs, src/moonlink/src/table_handler/chaos_replay.rs, src/moonlink/src/table_handler/table_handler_state.rs, src/moonlink/src/table_notify.rs
If event completion is reported in background threads, we could have race between different threads, so replay system is still not deterministic.
This PR should be a no-op refactor to production.
=> [storage] Move event replay to table main thread

src/moonlink/src/storage/wal.rs, src/moonlink/src/storage/wal/tests.rs
Previously, we track every the file range for every single main transaction, so as to know whether or not we can keep a WAL file after iceberg snapshot. This can grow very large for metadata tracking. 
We actually only need to track the highest main transaction completely contained in each file, as well as the highest main transaction contained in this file which continued from the file before, instead of every transaction. This change is reflected in this PR. 
closes #1397
=> Compress wal main xact

src/moonlink/src/storage/wal.rs, src/moonlink/src/storage/wal/test_utils.rs, src/moonlink/src/storage/wal/tests.rs, src/moonlink/src/table_handler/test_utils.rs, src/moonlink/src/table_handler/tests.rs
Closes #1387 
This PR fixes a possible duplication issue during recovery - currently, during recovery we read in ascending file order until a WAL file no longer exists.  We then use the metadata file 'highest confirmed lsn' to filter out any events from postgres so we do not replay them. However, it is possible that we persisted a WAL file but crashed before persisting the metadata file, resulting in us applying events from both the latest WAL file and postgres. 
The latest metadata file should be the single source of truth. Therefore, we should only read from the file range stored in the metadata file, and not read in ascending WAL file number until a file no longer exists. This change is reflected in this PR.
=> Wal recovery reads only files stored in metadata

src/moonlink_connectors/src/pg_replicate.rs, src/moonlink_connectors/src/pg_replicate/postgres_source.rs
Fixes a previous bug that had an assertion that checked that a table did not exist in CdcStream's table schemas when calling add_table_schema, even though this was not true for schema evolution. Added a function called update_table_schema. 
- 
- 
-
=> add update table schema

src/moonlink/src/storage/mooncake_table.rs, src/moonlink_backend/src/lib.rs, src/moonlink_backend/src/recovery_utils.rs, src/moonlink_connectors/src/pg_replicate.rs, src/moonlink_connectors/src/pg_replicate/table_init.rs, src/moonlink_connectors/src/replication_connection.rs, src/moonlink_connectors/src/replication_manager.rs, src/moonlink_connectors/src/rest_ingest.rs
Table id (mooncake table id, the integer part, without database id) is used in a few places:
- It's part of the write cache directory and WAL directory, will replace with schema and table name
- It's used to globally uniquely identify a cache entry, I assign a temporary table id to compensate
+ temporary means it's subject to change after recovery
This PR is supposed to be a no-op change functionality-wise, existing integration tests should be enough.
=> [2/N] Remove table id concepts from connector

src/moonlink_connectors/src/rest_ingest/json_converter.rs
Extend src/moonlink_connectors/src/rest_ingest/json_converter.rs to support list to JSON array conversion
Closes #1285
- Perform element wise type conversion from List to Array recurrsively
- Add test for converting list with different element types and nested list
=> REST: Type support for list

src/moonlink_connectors/src/rest_ingest/decimal_utils.rs, src/moonlink_connectors/src/rest_ingest/json_converter.rs
Improve the error propagation in decimal utils, also improve the error propagation.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1447
- improve error propagation
- assert with error, ensure propagate the correct error, not error msg
=> fix: error propagation in decimal type convertion

src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/wal.rs, src/moonlink/src/storage/wal/test_utils.rs, src/moonlink/src/storage/wal/tests.rs, src/moonlink/src/table_handler/test_utils.rs, src/moonlink/src/table_handler/tests.rs, src/moonlink_connectors/src/pg_replicate/table_init.rs
Refactoring to use WalConfig and to make any reads / writes in testing go through the wal file system accessor instead of directly using the file system.  
#974 
- [X ] Code builds correctly
- [ X] Tests have been added or updated
=> refactor before obj store changes

src/moonlink/src/error.rs, src/moonlink/src/storage/iceberg/mock_filesystem_test.rs, src/moonlink/src/table_handler.rs
This PR fixes error propagation from iceberg errors.
Before:
```sh
called `Result::unwrap()` on an `Err` value, location: Some(Location { file: "src/moonlink/src/storage/mooncake_table.rs", line: 1425, col: 87 }) })
```
After:
```sh
alled `Result::unwrap()` on an `Err` value: IcebergError(ErrorStruct { message: "Iceberg error: DataInvalid => helloworld", status: Permanent, source: Some(DataInvalid => helloworld), location: Some(Location { file: "src/moonlink/src/storage/iceberg/iceberg_table_syncer.rs", line: 529, col: 9 }) })
```
As you could tell, error source location is actually from iceberg syncer.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1487
=> [storage] Fix iceberg error propagation

src/moonlink/src/storage/mooncake_table/data_file_state_tests.rs, src/moonlink/src/storage/mooncake_table/deletion_vector_puffin_state_tests.rs, src/moonlink/src/storage/mooncake_table/snapshot_read_output.rs, src/moonlink/src/union_read/read_state_manager.rs
https://github.com/Mooncake-Labs/moonlink/blob/6437db10c8b191d2b4553fbc5216e1e944c3307f/src/moonlink/src/storage/mooncake_table/snapshot_read_output.rs#L74-L85
Closes https://github.com/Mooncake-Labs/moonlink/issues/1488
- return Result instead of unwrap and panic if IO error happened.
=> snapshot read: avoid unwrap potential IO error

src/moonlink_connectors/src/pg_replicate/util.rs
Add all type coverage to make me sleep better.
Also use arrow int64 to represent u32, otherwise we could suffer overflow.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1496
=> Add missing tests for pg_replication type conversion

src/moonlink_connectors/src/pg_replicate/conversions/text.rs
Change error message format from
`#[error("invalid text conversion")]`
to
`#[error("invalid text conversion, Unsupported type: {0}")]`.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1489
=> Include unsupported type in conversion failure

src/moonlink/src/storage/compaction/compactor.rs, src/moonlink/src/storage/iceberg/compaction_tests.rs, src/moonlink/src/storage/mooncake_table/disk_slice.rs, src/moonlink/src/storage/parquet_utils.rs
- I found bloom filter affect file size A LOT; for example, for file row count <100, file size could increase from 100 byte to 6MB
- Fix estimated size into memory size, I found prev calculation doesn't account for bloom filter size
Closes https://github.com/Mooncake-Labs/moonlink/issues/1435
Closes https://github.com/Mooncake-Labs/moonlink/issues/525
=> [storage] Set storage bloom filter for compacted files

src/moonlink/src/table_handler/chaos_test.rs
Followup for https://github.com/Mooncake-Labs/moonlink/pull/1529, which validate query on empty table has no problem.
=> [chaos] Validate empty table

src/moonlink_backend/src/lib.rs, src/moonlink_backend/src/mooncake_table_id.rs, src/moonlink_backend/src/recovery_utils.rs, src/moonlink_backend/src/table_status.rs, src/moonlink_backend/tests/common.rs, src/moonlink_backend/tests/test_backend.rs, src/moonlink_backend/tests/test_initial_copy.rs, src/moonlink_metadata_store/src/base_metadata_store.rs, src/moonlink_metadata_store/src/postgres/pg_metadata_store.rs, src/moonlink_metadata_store/src/postgres/sql/create_secrets.sql, src/moonlink_metadata_store/src/postgres/sql/create_tables.sql, src/moonlink_metadata_store/src/sqlite/sql/create_secrets.sql, src/moonlink_metadata_store/src/sqlite/sql/create_tables.sql, src/moonlink_metadata_store/src/sqlite/sqlite_metadata_store.rs, src/moonlink_metadata_store/src/sqlite/tests.rs, src/moonlink_metadata_store/tests/test_pg_metadata_store.rs, src/moonlink_rpc/src/lib.rs, src/moonlink_service/examples/rest_api_demo.rs, src/moonlink_service/src/rest_api.rs, src/moonlink_service/src/rpc_server.rs
Current `<schema>.<table>` doesn't uniquely identify a table, since it could duplicate across databases;
this PR updates them to `<database>.<schema.table>`.
This PR is supposed to be a no-op change.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1528
=> [backend] Rename schema / table to database / table

Cargo.lock, src/moonlink_service/Cargo.toml, src/moonlink_service/src/error.rs, src/moonlink_service/src/rpc_server.rs
Apply ErrorStruct to error types in moonlink_service.
Can simply follow what we have done for the src/moonlink_rpc/src/error.rs in PR https://github.com/Mooncake-Labs/moonlink/pull/1422, and apply changes to [src/moonlink_service/src/error.rs](https://github.com/Mooncake-Labs/moonlink/blob/main/src/moonlink_service/src/error.rs?rgh-link-date=2025-08-14T11%3A32%3A12.000Z)
Closes https://github.com/Mooncake-Labs/moonlink/issues/1457
- Apply ErrorStruct to error types in moonlink_service and implement proper error conversion 
- Adapt this new error interface in the rpc_server
=> Refine moonlink_service errors with new Error struct

src/moonlink_backend/src/recovery_utils.rs
When working on standalone deployment, I found recovery on rest-api-created table cannot recovered and crash the whole service.
The reason being not supporting replication
https://github.com/Mooncake-Labs/moonlink/blob/fc14ea782e9535b97590b3bf7640f16b7382a9e5/src/moonlink_connectors/src/replication_connection.rs#L190-L192
Temporarily lock it down to avoid crashing the whole service, will revisit later.
All rest sever part has separate issues to track and someone working on it.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1538
=> Skip recovery for rest created tables

src/moonlink/src/row.rs, src/moonlink/src/row/arrow_converter.rs, src/moonlink/src/row/moonlink_row.rs
For file-based ingestion for rest API, the easiest implementation is load arrow batches to moonlink rows and leverage table handler / mooncake table.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1587
=> [storage] Arrow to moonlink row conversion

Cargo.lock, Cargo.toml, deny.toml
Use new commit for `rust-postgres` to pull changes for 
1) Adding back `postgres-native-tls` 4d613eb696e77372b31aae9838d6434251dd2235
2) Pulling zero copy buffer optimizations for `LogicalReplicationMessage::parse` 4fda9c1bece3b93359ca1eb2779458fc1c080eae
(PR here https://github.com/Mooncake-Labs/rust-postgres/pull/11) 
Reminder to `cargo clean && cargo update` to pull latest changes.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1481
- 
- 
-
=> Bump rust postgres

Cargo.lock, Cargo.toml, src/moonlink/Cargo.toml, src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/batch_ingestion.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs, src/moonlink/src/storage/mooncake_table/snapshot_validation.rs, src/moonlink/src/storage/mooncake_table/transaction_stream.rs, src/moonlink/src/table_handler.rs, src/moonlink/src/table_handler/test_utils.rs, src/moonlink/src/table_handler/tests.rs, src/moonlink/src/table_notify.rs, src/moonlink_connectors/Cargo.toml
This PR is the initial, basic and somewhat hacky implementation for files bulk upload into mooncake table.
Basically these files are stored as streaming state, and push into snapshot buffer then reflected to mooncake snapshot.
In the followup PR, I will focus on two parts:
- Performance: parallelize IO involved
- Integrate with moonlink backend
=> [storage] Basic implementation for bulk ingestion

src/moonlink_connectors/src/lib.rs, src/moonlink_connectors/src/pg_replicate.rs, src/moonlink_connectors/src/pg_replicate/moonlink_sink.rs, src/moonlink_connectors/src/pg_replicate/table_init.rs, src/moonlink_connectors/src/replication_connection.rs, src/moonlink_connectors/src/replication_state.rs, src/moonlink_connectors/src/rest_ingest.rs, src/moonlink_connectors/src/rest_ingest/moonlink_rest_sink.rs, src/moonlink_connectors/src/rest_ingest/rest_source.rs, src/moonlink_service/src/test.rs
Problem statement:
- REST connector creates temporary replication state variable, which means the replication LSN receiver at read state manager listens to a broken (closed) replication sender;
- It leads to a problem, whenever we scan table (block wait) for a non-zero LSN, it crashes
This PR fixes by 
- Extracting replication state out of pg connector
- Send out commit LSN via replication LSN channel
Closes https://github.com/Mooncake-Labs/moonlink/issues/1605
=> [REST] Fix replication state for rest connector

src/moonlink/src/storage/filesystem/accessor/filesystem_accessor.rs, src/moonlink/src/storage/filesystem/gcs/gcs_test_utils.rs, src/moonlink/src/storage/filesystem/storage_config.rs, src/moonlink_backend/src/table_config.rs, src/moonlink_metadata_store/src/config_utils.rs, src/moonlink_metadata_store/src/sqlite/tests.rs
This PR adds default value to write option serde, so we don't have compatibility issues.
Existing unit tests are enough, if options are not set properly GCS tests will fail.
=> [storage] Add serde default for write option

src/moonlink_service/src/rpc_server.rs
Run anything on pg_mooncake that will connect to moonlink, e.g.
```sql
INSERT INTO r VALUES (1, 'a'), (2, 'b'), (3, 'c');
SELECT * FROM c;
```
Now Ctrl-C to close client. In pg log (/home/vscode/.pgrx/17.log), we have
```
thread 'tokio-runtime-worker' panicked at /workspaces/pg_mooncake/moonlink/src/moonlink_service/src/rpc_server.rs:42:27:
Unexpected Unix RPC server error: RPC error (permanent) at /workspaces/pg_mooncake/moonlink/src/moonlink_service/src/rpc_server.rs:80:23, source: IO error (permanent) at /workspaces/pg_mooncake/moonlink/src/moonlink_rpc/src/lib.rs:49:5, source: early eof
stack backtrace:
0: __rustc::rust_begin_unwind
at …
```
=> fix: moonlink_service panics when client closes connection

src/moonlink_backend/tests/test_backend.rs, src/moonlink_connectors/src/replication_connection.rs
As titled, crash on non-existent table is not ideal.
=> No crash on drop non-existent table

src/moonlink_service/src/rest_api.rs
Avoid crashing the REST server when JSON serialization fails by replacing `unwrap()` with proper error handling.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1624
=> add error handling for json fail condition

src/moonlink/src/lib.rs, src/moonlink/src/storage.rs, src/moonlink/src/storage/iceberg.rs, src/moonlink/src/storage/iceberg/base_iceberg_snapshot_fetcher.rs, src/moonlink/src/storage/iceberg/iceberg_snapshot_fetcher.rs, src/moonlink/src/storage/iceberg/snapshot_fetcher_test.rs, src/moonlink_backend/src/lib.rs, src/moonlink_backend/src/recovery_utils.rs, src/moonlink_connectors/src/replication_connection.rs, src/moonlink_connectors/src/replication_manager.rs, src/moonlink_connectors/src/replication_state.rs, src/moonlink_connectors/src/rest_ingest.rs, src/moonlink_connectors/src/rest_ingest/rest_source.rs
Followup PR for https://github.com/Mooncake-Labs/moonlink/pull/1643.
Previous one only handles schema recovery, this PR makes the same decision for replication LSN recovery to use iceberg as persistence layer.
After this PR, we're able to get consistent LSN across moonlink backend crash and recovery, and able to implement LSN-related features for REST API.
=> [storage] Recovery replication LSN for REST

src/moonlink/src/storage/mooncake_table/batch_ingestion.rs, src/moonlink/src/table_handler/test_utils.rs, src/moonlink/src/table_handler/tests.rs
When doing batch ingestion for large dataset, I found it took me >20 minutes to run the batch ingestion function, the reason being large number of parquet files and sequential IO.
IO operation is involved here to get row number and file size.
In this PR, these IO operations are parallelized.
=> [storage] Parallel batch ingest

src/moonlink/src/storage/iceberg/iceberg_table_loader.rs, src/moonlink/src/storage/iceberg/tests.rs
When create iceberg table, version hint with version 0 is written;
when a successful snapshot is made, version hint is updated.
For recovery, we should be able to recover from any possible states; this PR fixes cases when there's only version 0.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1690
=> [storage] Fix iceberg recovery

src/moonlink/src/storage/iceberg/io_utils.rs, src/moonlink/src/storage/iceberg/tests.rs
This PR fixes iceberg data file naming; 
previous the filename could be "aaa.parquet-uuid", after the fix it should be "aaa-uuid.parquet".
=> [storage] Fix iceberg data file naming

src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/table_creation_test_utils.rs, src/moonlink/src/storage/mooncake_table/table_snapshot.rs, src/moonlink/src/table_handler/chaos_test.rs
- Update existing append-only test with append-only tables
- Add invariant validation for table metadata
Closes https://github.com/Mooncake-Labs/moonlink/issues/1699
=> [chaos] Add append-only table test

src/moonlink/benches/bench_write.rs, src/moonlink/src/storage/iceberg/state_tests.rs, src/moonlink/src/storage/iceberg/tests.rs, src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs, src/moonlink/src/storage/mooncake_table/snapshot_maintenance.rs, src/moonlink/src/storage/mooncake_table/snapshot_persistence.rs, src/moonlink/src/storage/mooncake_table/table_operation_test_utils.rs, src/moonlink/src/storage/mooncake_table/tests.rs, src/moonlink/src/storage/mooncake_table/transaction_stream.rs, src/moonlink/src/storage/snapshot_options.rs, src/moonlink/src/table_handler.rs, src/moonlink/src/table_handler/chaos_replay.rs, src/moonlink/src/table_handler/chaos_test.rs, src/moonlink/src/table_handler/table_handler_state.rs, src/moonlink/src/table_notify.rs
This PR fixes non-deterministic event id issue, which is crucial for deterministic reproduction.
So in the past, background events might have their own event id generation; for example, data compaction generates new event id inside of snapshot, which creates non-deterministic replay.
In this PR, I surface all event id into mooncake table interface layer.
=> [chaos] Fix replay event

.github/workflows/ci.yml
I met a CI workflow which got stuck for >10 minutes on S3 server image download, need to set timeout for all operations.
=> [CI] Set timeout for fake gcs and s3 server

src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/replay/replay_events.rs, src/moonlink/src/table_handler/chaos_replay.rs
The issue is, assume such event flow when replay:
- mooncake snapshot begin
- append
- commit
- mooncake snapshot end & validate snapshot
In the current implementation, since we requested for latest commit LSN and all events will be front-end events are blocked, the replay program gets blocked.
=> [chaos] Fix read LSN for snapshot

src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/table_handler.rs, src/moonlink/src/table_handler/test_utils.rs, src/moonlink/src/table_handler/tests.rs
fix https://github.com/Mooncake-Labs/moonlink/issues/1471
during alter table, we buffer the incoming events without writing them to table.
so we shouldn't update any table_lsn.
=> fix alter table 

src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/replay/replay_events.rs, src/moonlink/src/table_handler/chaos_replay.rs
- Add LSN at replay event, which is super useful for debugging by reading dumped json files
- Add iceberg snapshot validation at replay, so we could detect problematic snapshot earlier
=> [chaos] Validate iceberg snapshot at replay

.devcontainer/devcontainer.json, .devcontainer/docker-compose.yml
Add iceberg-rest setup code in docker compose.yaml file.
Already tested using `test_create_table` [here](https://github.com/Mooncake-Labs/moonlink/pull/1725).
Related https://github.com/Mooncake-Labs/moonlink/issues/1617
Closes https://github.com/Mooncake-Labs/moonlink/issues/1615
=> setup iceberg-rest service in dockercompose

src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/table_operation_test_utils.rs, src/moonlink/src/storage/mooncake_table/tests.rs, src/moonlink/src/storage/mooncake_table/transaction_stream.rs, src/moonlink/src/table_handler/tests.rs
Currently we use a set data structure to manage ongoing flush operations: https://github.com/Mooncake-Labs/moonlink/blob/c178bfb7e7d80127eed7fddcb8fd1113e8512b54/src/moonlink/src/storage/mooncake_table.rs#L464-L465
but for streaming transaction we could have multiple flushes in the background.
A detailed example,
- LSN = 13, streaming txn, no commit LSN, issue flush
- LSN = 16, non-streaming txn, issue flush
- LSN = 13, streaming txn, has commit LSN, issue flush
After that we have two ongoing flush LSNs, one for 13, another for 16.
The completion order is as below:
- LSN = 13
- LSN = 16
When the first flush finish, the lowest LSN is 16, which means we set flush LSN to 16 and will dump iceberg with LSN 16.
This PR fixes the issue by use a <LSN, counter> map to record all ongoing flush …
=> [storage] Handle multiple ongoing flushes for streaming transaction

src/moonlink/Cargo.toml, src/moonlink/benches/bench_write.rs, src/moonlink/benches/microbench_write_mooncake_table.rs, src/moonlink/src/lib.rs, src/moonlink/src/storage.rs, src/moonlink/src/storage/iceberg/catalog_utils.rs, src/moonlink/src/storage/iceberg/compaction_tests.rs, src/moonlink/src/storage/iceberg/iceberg_snapshot_fetcher.rs, src/moonlink/src/storage/iceberg/iceberg_table_config.rs, src/moonlink/src/storage/iceberg/iceberg_table_manager.rs, src/moonlink/src/storage/iceberg/state_tests.rs, src/moonlink/src/storage/iceberg/tests.rs, src/moonlink/src/storage/mooncake_table/file_index_state_tests.rs, src/moonlink/src/storage/mooncake_table/table_creation_test_utils.rs, src/moonlink/src/storage/mooncake_table/table_status_reader.rs, src/moonlink/src/storage/mooncake_table/test_utils.rs, src/moonlink/src/table_handler/test_utils.rs, src/moonlink_backend/src/table_config.rs, src/moonlink_connectors/src/pg_replicate/table_init.rs, src/moonlink_metadata_store/src/config_utils.rs, src/moonlink_metadata_store/src/sqlite/tests.rs, src/moonlink_metadata_store/src/test_utils.rs, src/moonlink_metadata_store/tests/common/test_utils.rs
Current iceberg table config only supports file catalog: [main/src/moonlink/src/storage/iceberg/iceberg_table_config.rs](https://github.com/Mooncake-Labs/moonlink/blob/main/src/moonlink/src/storage/iceberg/iceberg_table_config.rs?rgh-link-date=2025-08-24T08%3A46%3A19.000Z)
Closes https://github.com/Mooncake-Labs/moonlink/issues/1691
- Add RestCatalogConfig and GlueCatalogConfig for iceberg-rust CatalogConfig Builders
- [GlueCatalogBuilder](https://github.com/apache/iceberg-rust/blob/4aacad756250a5a1bbc44842ea4b608e3213b641/crates/catalog/rest/src/catalog.rs#L73-L119)
- [RestCatalogBuilder](https://github.com/apache/iceberg-rust/blob/4aacad756250a5a1bbc44842ea4b608e3213b641/crates/catalog/glue/src/catalog.rs#L66-L119)
-
=> Add Rest and Glue iceberg catalog configuration to support multiple catalog

src/moonlink_backend/src/lib.rs, src/moonlink_backend/src/recovery_utils.rs, src/moonlink_connectors/src/replication_connection.rs, src/moonlink_connectors/src/replication_manager.rs
As we move `MooncakeTableId` from backend to moonlink crate, there's no necessity of keeping generic at replication manager and replication connection.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1707
=> Remove replication manager and connection generics

src/moonlink_backend/src/error.rs, src/moonlink_backend/src/table_config.rs, src/moonlink_service/src/test.rs
Followup PR for https://github.com/Mooncake-Labs/moonlink/pull/1758, which adds row identity into table config for creation. There're certain invariants we need to keep, so add a validation function to check and fail if breaks.
=> [storage] Validate table creation config

src/moonlink/src/storage/mooncake_table/batch_id_counter.rs, src/moonlink/src/storage/mooncake_table/data_batches.rs
A minor no-op change, even if I added documentation on function behavior, I still get confused.
This PR rename the function and clearly explains the behavior itself.
=> [minor] Rename batch id next function

src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/table_operation_test_utils.rs, src/moonlink/src/storage/mooncake_table/tests.rs
Suppose we have three ongoing flush operations, two with flush LSN 13, one with flush LSN 16.
If they finish in the order of 13, 16, 13; in the current implementation we will miss LSN 16, see linked issue for example.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1770
=> [storage] Fix missing flush LSN

src/moonlink/src/storage/compaction/test_utils.rs, src/moonlink/src/storage/iceberg/iceberg_table_loader.rs, src/moonlink/src/storage/iceberg/iceberg_table_syncer.rs, src/moonlink/src/storage/iceberg/puffin_utils.rs, src/moonlink/src/storage/mooncake_table/replay/replay_events.rs
Current replay event json file only records puffin blob file id, which is useless for inspect deleted rows or row number.
When debugging chaos test, number of rows is important to check whether compaction outcome is correct or not.
This PR adds number of rows to puffin blob data structure, and update replay events accordingly.
=> [chaos] Record puffin blob deleted rows

src/moonlink/src/storage/iceberg/compaction_tests.rs, src/moonlink/src/storage/index/hash_index.rs, src/moonlink/src/storage/index/mem_index.rs, src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/disk_slice.rs, src/moonlink/src/storage/mooncake_table/mem_slice.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs, src/moonlink/src/storage/mooncake_table/table_creation_test_utils.rs, src/moonlink/src/storage/mooncake_table/tests.rs, src/moonlink/src/storage/mooncake_table/transaction_stream.rs, src/moonlink/src/storage/mooncake_table/validation_test_utils.rs, src/moonlink/src/storage/storage_utils.rs, src/moonlink/src/storage/wal.rs, src/moonlink/src/storage/wal/test_utils.rs, src/moonlink/src/table_handler.rs, src/moonlink/src/table_handler/chaos_test.rs, src/moonlink/src/table_handler/test_utils.rs, src/moonlink/src/table_notify.rs, src/moonlink_connectors/src/pg_replicate/moonlink_sink.rs, src/moonlink_connectors/src/rest_ingest/event_request.rs, src/moonlink_connectors/src/rest_ingest/moonlink_rest_sink.rs, src/moonlink_service/src/rest_api.rs
If the table have primary key,
regular INSERT/ UPDATE/ DELETE could error and event api is usually not designed to handle this kind of failure.
Introducing Upsert /Delete if not exists, which provide simpler semantics and will success in all cases.
Upsert is implemented as append + delete_if_not_exist.
- 
- 
-
=> Implement Upsert/ Delete if exist for event API

src/moonlink_backend/Cargo.toml, src/moonlink_backend/tests/common.rs, src/moonlink_backend/tests/control_plane_retry.rs, src/moonlink_connectors/src/lib.rs, src/moonlink_connectors/src/pg_replicate.rs
Implements reconnection logic for any of the control plane commands we make to PG. Control plane commands are defined as short, one-off DDL/DCL commands we make to Postgres that happen outside of the replication task, and are usually part of some setup/tear down sequence. They are stateless and can be retried. These are in contrast to our data plane PG queries which happen from the replication task, and are usually stateful or depend on a specific sequencing for managing the CDC stream. For these commands we still fail fast, although respawning a failed replication task will be addressed as part of #1780 
We retry on any transport errors and implement a simple linear back-off with `MAX_DELAY` and `MAX_RETRIES`. In order to identify transport errors we look at the `SqlState` code returned. …
=> Control plane retry for transport errors

src/moonlink/src/lib.rs, src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/batch_id_counter.rs, src/moonlink/src/storage/mooncake_table/batch_ingestion.rs, src/moonlink/src/storage/mooncake_table/data_batches.rs, src/moonlink/src/storage/mooncake_table/test_utils.rs, src/moonlink/src/storage/mooncake_table/transaction_stream.rs, src/moonlink/src/storage/parquet_utils.rs, src/moonlink/src/storage/wal.rs, src/moonlink/src/storage/wal/test_utils.rs, src/moonlink/src/table_handler.rs, src/moonlink/src/table_handler/chaos_test.rs, src/moonlink/src/table_handler/table_handler_state.rs, src/moonlink/src/table_handler/test_utils.rs, src/moonlink/src/table_handler/tests.rs, src/moonlink/src/table_notify.rs, src/moonlink_connectors/src/error.rs, src/moonlink_connectors/src/pg_replicate.rs, src/moonlink_connectors/src/pg_replicate/initial_copy.rs, src/moonlink_connectors/src/pg_replicate/initial_copy_writer.rs, src/moonlink_connectors/src/pg_replicate/moonlink_sink.rs, src/moonlink_connectors/src/rest_ingest/moonlink_rest_sink.rs
Instead of sending each row from the initial load through the table handler we can write these directly to parquet and use the batch_ingest API to integrate the files with moonlink.
We consume rows from the initial copy stream and add them to an arrow batch builder. When a new batch is ready, it's sent over an `mpsc` channel to a parquet writer. 
The reason for the `mpsc` channel is two-fold: 
First, it gives us natural backpressure for free. In the event that our copy stream is producing batches much faster than our writer(s) can consume them, the channel will apply back pressure on the copy stream and prevent memory bloat. 
Second, it decouples the producers from the consumers making parallelization easier. We can have a collection of producers appending to the queue, and a pool of …
=> Initial load direct-to-disk optimization

src/moonlink/src/storage/iceberg/iceberg_table_loader.rs, src/moonlink/src/storage/iceberg/iceberg_table_manager.rs, src/moonlink/src/storage/iceberg/iceberg_table_syncer.rs, src/moonlink/src/storage/iceberg/tests.rs
Code change should be straightforward, the uninitialized max row size is not necessary, we could directly get it from iceberg data file attributes.
=> [storage] Remove uninitialized max row size

src/moonlink_connectors/src/pg_replicate/initial_copy.rs, src/moonlink_connectors/src/pg_replicate/initial_copy_writer.rs
Spins up a worker pool of parquet writers to consume batches from the `mpsc` channel and write in parallel. 
Adds concept of `SharedBatchReceiver` which wraps the receiving end of the channel with a Mutex so writers can concurrently `recv` batches to write. 
Starting with arbitrary number of parallel writers (4). We will have a better idea of how to tune this once we start appending batches in parallel. 
As a rough upper bound, perf for 100M initial load goes from 2 minutes -> 24 seconds. 
Closes https://github.com/Mooncake-Labs/moonlink/issues/1240
- Add worker pool of writers
- Concurrently get batches from mpsc channel
- Add unit and integration testing
=> Parallelize initial load parquet writers

src/moonlink_backend/src/config_utils.rs, src/moonlink_backend/src/lib.rs
https://github.com/Mooncake-Labs/moonlink/pull/1800 introduces a weird regression:
- default iceberg warehouse uri (if unspecified) should be placed under `<base>/<database>/<table>`
- but the above PR updates it to `<base>/temp/<database>/<table>`
I manually verifies with pg_mooncake
=> [storage] Revert default iceberg table directory

Cargo.lock, src/moonlink_service/Cargo.toml, src/moonlink_service/src/test.rs
tokio directory deletion doesn't allow content inside, so recursively delete internal files first;
also add type tests for more decimal types that we support.
=> Fix flaky directory deletion

.devcontainer/certs/.gitignore, .gitignore
```sh
vscode ➜ /workspaces/moonlink (hjiang/fix-iceberg-rest ✗) $ git add .devcontainer/
vscode ➜ /workspaces/moonlink (hjiang/fix-iceberg-rest ✗) $ git commit --amend --no-ed
[hjiang/fix-iceberg-rest 78700e67] fix ci
Date: Sat Aug 30 20:36:07 2025 +0000
31 files changed, 91 insertions(+), 78 deletions(-)
create mode 100644 .devcontainer/certs/ca.srl # unintentionally add certificate file into git commit
```
Current certificates are not pushed simply because `.devcontainer` is a hidden directory, not all files are ignored by git.
=> Fix gitignore for certificates

src/moonlink/src/table_handler/chaos_test.rs
Delete if exists semantics is only supported for non-streaming transaction.
Closes https://github.com/Mooncake-Labs/moonlink/pull/1776#discussion_r2312137092
=> [chaos] Fix chaos test precondition for delete if exists

.gitignore
The .gitignore directory is incorrect; it should be `.devcontainer/certs/`.
Related #1819.
=> Fix gitigore for devcontainer certs directory

src/moonlink/src/storage/mooncake_table/snapshot_read_output.rs
The current snapshot reading implementation processes files sequentially, one by one. This can cause performance issues when a file is particularly large, leading to unnecessary delays.
Introduce parallel file reading to reduce total wait time. By downloading and pinning multiple files concurrently, the overall snapshot read process becomes faster and more efficient.
Closes #1310 
- parallelize the download / pin, seq the others
- init the evicted_files_to_delete_on_error size
=> perf: parallelize remote filepath download / pin

.github/workflows/ci.yml, src/moonlink_service/src/rest_api.rs, src/moonlink_service/src/test.rs, src/moonlink_service/src/test_utils.rs
A few changes included in the PR:
- Revert CI changes to wait nginx server ready, which seems to be broken; I will check separately
- Extract into common functions for standalone test
- Improve rest server error propagation
+ For error response, status code and message is enough, `error` field doesn't include extra information
+ I removed the error logging, since propagation back to client-side is already enough
+ Include more information on returned error message, which is useful for client-side for error aggregation (i.e., text search and aggregation)
=> [REST] Improve rest error propagation

src/moonlink/src/storage/iceberg/compaction_tests.rs, src/moonlink/src/storage/iceberg/iceberg_table_loader.rs, src/moonlink/src/storage/iceberg/state_tests.rs, src/moonlink/src/storage/iceberg/tests.rs, src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/batch_ingestion.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs, src/moonlink/src/storage/mooncake_table/snapshot_maintenance.rs, src/moonlink/src/storage/mooncake_table/snapshot_validation.rs, src/moonlink/src/storage/mooncake_table/tests.rs, src/moonlink/src/storage/mooncake_table/transaction_stream.rs, src/moonlink/src/storage/mooncake_table/validation_test_utils.rs, src/moonlink/src/table_handler/tests.rs
This PR is a no-op change, simply renames batch deletion vector to its true meaning: committed deletion vector.
=> [minor] Rename committed deletion vector

src/moonlink_backend/src/lib.rs, src/moonlink_backend/tests/test_backend.rs, src/moonlink_connectors/src/rest_ingest/event_request.rs, src/moonlink_connectors/src/rest_ingest/moonlink_rest_sink.rs, src/moonlink_connectors/src/rest_ingest/rest_event.rs, src/moonlink_connectors/src/rest_ingest/rest_source.rs, src/moonlink_service/src/rest_api.rs, src/moonlink_service/src/test.rs
For more details please see https://github.com/Mooncake-Labs/moonlink/issues/1831#issuecomment-3243112509
TLDR: current implementation doesn't guarantee snapshot creation request is sent after table ingestion at table handler side
I think the semantics for snapshot creation needs to be revisited after our openapi finalized.
=> [REST] Fix flaky recovery test

src/moonlink_backend/src/logging.rs
This PR adds file name and line number to logging, which is the default behavior for glog ([1](https://github.com/google/glog), [2](https://github.com/golang/glog))
I found it super useful for troubleshooting with source code location attached with message.
Effect:
```sh
2025-09-02 04:37:34+00:00  INFO src/moonlink_service/src/lib.rs:142: Moonlink service started successfully
2025-09-02 04:37:34+00:00  INFO src/moonlink_service/src/rpc_server.rs:78: Moonlink RPC server listening on TCP: 0.0.0.0:3031
2025-09-02 04:37:34+00:00  INFO src/moonlink_service/src/rpc_server.rs:57: Moonlink RPC server listening on Unix socket: "/tmp/temp_test_44553/moonlink.sock"
2025-09-02 04:37:34+00:00  INFO src/moonlink_service/src/rest_api.rs:649: Starting REST API server on 0.0.0.0:3030
```
Closes …
=> Add source code location to logging

src/moonlink_backend/src/lib.rs, src/moonlink_connectors/src/pg_replicate.rs, src/moonlink_connectors/src/replication_manager.rs
Currently no coordination between when the schema is actually added to the `CdcStream` and when logical replication events will begin streaming. 
In this PR we add a `oneshot` channel to notify the caller that the table has been added to the stream and its safe to proceed. 
We also do a small refactor to lazily create and start the replication connection as part of add table. Note that we now spawn the replication task first, then add the table. 
Closes https://github.com/Mooncake-Labs/moonlink/issues/1790
- 
- 
-
=> Add table handshake

src/moonlink/src/storage/compaction/table_compaction.rs, src/moonlink/src/storage/iceberg/iceberg_table_syncer.rs, src/moonlink/src/storage/iceberg/table_manager.rs, src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/table_snapshot.rs, src/moonlink/src/table_handler.rs, src/moonlink/src/table_handler/chaos_replay.rs, src/moonlink/src/table_handler/failure_tests.rs
When debugging a file not found error, I found most of the file deletion today inside of moonlink is scattered everywhere.
It's bad for replay system since it makes replay non-deterministic and impossible to stably repro.
This PR is a no-op change, simply move the deletion logic into result and applied in a centralized place table handler.
=> [storage] Move file deletion into file handle

Cargo.lock, Cargo.toml, deny.toml
Pull in changes for: 
https://github.com/Mooncake-Labs/rust-postgres/pull/13
This allows us to compute the `end_lsn` per `XLogData` block, providing more granular level LSN data (e.g no longer have to wait for stream commit for lsn data). 
This will be used in an upcoming change related to respawning the replication task, however I also think there are applications for our WAL writer in that this allows us to store partial transactions/not have to start from the beginning of a streamed transaction in PG during recovery(?) 
Closes http://github.com/Mooncake-Labs/moonlink/issues/1895
- 
- 
-
=> Bump rust-postgres

src/moonlink/src/storage/cache/object_storage/cache_handle.rs, src/moonlink/src/storage/cache/object_storage/local_file_optimization_state_tests.rs, src/moonlink/src/storage/cache/object_storage/state_tests.rs, src/moonlink/src/storage/compaction/compactor.rs, src/moonlink/src/storage/mooncake_table/data_file_state_tests.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs, src/moonlink/src/storage/mooncake_table/snapshot_persistence.rs, src/moonlink/src/storage/mooncake_table/snapshot_read_output.rs, src/moonlink/src/union_read/read_state.rs
No need for `mutable` to acquire / release mutex.
=> [storage] Remove useless mutable specifier

src/moonlink/src/storage/cache/metadata/base_cache.rs
Remove unnecessary TODO items on static lifecycle annotation, since it's required by `moka` cache library.
Closes #1797
=> chore: remove unnecessary TODO on static lifecycle annotaiton

src/moonlink_backend/tests/test_backend.rs, src/moonlink_connectors/src/pg_replicate.rs, src/moonlink_connectors/src/pg_replicate/postgres_source.rs
Allows respawning of the replication task in the event we lost our connection stream to PG. Retires the connection with backoff. 
We do this by wrapping our replication task in an outer supervisor loop. In the event the connection breaks we copy out any state we need from the existing stream (schemas) and then reinitialize with a new stream and rehydrate with the saved schemas.
When reconnecting the stream we will start from `last_confirmed_flush_lsn`. In this case dedup is tricky since there is in memory state we are holding in addition to the state that is already written. This means we will have dups between the in memory data and the initial data sent in the stream on restart. 
We dedup by tracking the last LSN we pulled off the stream for each frame (using …
=> Replication task supervisor

src/moonlink_backend/src/lib.rs, src/moonlink_connectors/src/rest_ingest/event_request.rs, src/moonlink_connectors/src/rest_ingest/moonlink_rest_sink.rs, src/moonlink_connectors/src/rest_ingest/rest_event.rs, src/moonlink_connectors/src/rest_ingest/rest_source.rs, src/moonlink_service/src/rest_api.rs, src/moonlink_service/src/test.rs
This PR supports flush table in a blocking manner, which meets the requirement for kafka connector, who periodically explicitly requests to flush and commit.
Flushed WAL will be later used for recovery purpose.
=> [REST] Support flush table

src/moonlink_service/src/otel/metrics_handler.rs, src/moonlink_service/src/otel/otel_state.rs, src/moonlink_service/src/otel/service.rs
The bug is:
- axum copies shared state for each request, so the created tables state inside of `OtelState` recreated every time, which breaks the precondition that one table should be created at most once
- It failed with existing unit test, but the error is not propagated to client side, it's **by otel design**
I rerun the test again with the fix, and confirmed there're no duplicated tables created.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1949
=> [otel] Fix multiple otel data ingestion

src/moonlink_connectors/src/replication_manager.rs, src/moonlink_service/src/test.rs
Current implementation doesn't remove table id from table info struct:
- We have different logic branch for pg and rest
- Pg has its own unique cleanup, not sure why
Closes https://github.com/Mooncake-Labs/moonlink/issues/1951
=> [REST] Fix rest table recreation

src/moonlink/src/storage/iceberg/tests.rs
Add more unit tests for different ordering of async flush, with mooncake and iceberg snapshot checked.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1955
=> Add async flush test with iceberg snapshot

src/moonlink/src/storage/compaction/table_compaction.rs, src/moonlink/src/storage/compaction/test_utils.rs, src/moonlink/src/storage/iceberg/iceberg_table_loader.rs, src/moonlink/src/storage/iceberg/iceberg_table_syncer.rs, src/moonlink/src/storage/iceberg/puffin_utils.rs, src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/delete_vector.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs, src/moonlink/src/storage/mooncake_table/snapshot_maintenance.rs, src/moonlink/src/storage/mooncake_table/snapshot_read.rs, src/moonlink/src/storage/mooncake_table/snapshot_validation.rs, src/moonlink/src/table_handler.rs
There're two performance issues with the current implementation:
- On snapshot read, when get committed deletion records, we iterate through all deleted rows and compare the difference between persisted deletion records and all committed ones: https://github.com/Mooncake-Labs/moonlink/blob/f1d6ead03cf505824e739be189751b39a5b017a7/src/moonlink/src/storage/mooncake_table/snapshot_read.rs#L115-L130
- To get the batch deletion vector difference, we make a copy for batch deletion vector
The fix here is to keep committed deletion records, which are being compacted.
There're two types of logs to prune then:
- Those being used in compaction will get dropped naturally after compaction
- Those not being used will be remapped to a new record location
This PR is a no-op change, existing unit tests …
=> [storage] No prune compacted committed deletion records

Cargo.lock, Cargo.toml, src/moonlink/src/storage/iceberg/rest_catalog.rs, src/moonlink/src/storage/iceberg/rest_catalog_test.rs
The bug is: when we perform schema evolution, new schema needs to have unique schema id, otherwise update table is a no-op operation.
Also upgrade iceberg-rust package.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1983
=> [storage] Fix rest catalog update schema

src/moonlink/src/storage/iceberg.rs, src/moonlink/src/storage/iceberg/iceberg_rest_catalog_test.rs, src/moonlink/src/storage/iceberg/rest_catalog_test_guard.rs, src/moonlink/src/storage/iceberg/rest_catalog_test_utils.rs
This PR adds the basic unit test for iceberg rest catalog. 
To me, most of the rest catalog functionality should be fairly straightforward, since it's directly delegating to internal rest catalog without any additional logic; there're a few key things I'm concerned about:
- table creation
- schema setting (at table creation) and evolution
- table update / transaction commmit
These three items are the places we do our own hack. In this PR, I added least unit tests which cover these topics.
The ideal state for catalog test is to share the same testing logic with file catalog and maybe glue in the future, but there're certain blockers:
- file catalog unit tests use temporary directories, which are naturally isolated with each other; no extra test guard needed, no random table and namespace …
=> [storage] Add basic unit test for iceberg rest

.github/workflows/ci.yml, src/moonlink/src/table_handler/chaos_test.rs
This PR adds a simple replay into chaos test; the reason being, replay system does more thorough checking than chaos test, since it contains all the information (I record all table snapshots for all LSNs).
The biggest use case is, it could detect data inconsistency for iceberg snapshot persistence.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1984
=> [chaos] Add replay system to chaos test

.devcontainer/docker-compose.yml
Devcontainer needs to depend rest-catalog container to start first.
=> Add missing depend on devcontainer

src/moonlink/src/storage/filesystem/accessor/operator_utils.rs
```rs
if self.config.disable_config_load {
cred_loader = cred_loader
.with_disable_env()
.with_disable_well_known_location();
}
```
config load is used for two purpose:
- consider config env variables
- consider config files
For moonlink, we always use HMAC key in the foreseeable future, simply disable the config load for all object storage access.
=> [storage] Disable config load for S3 access

src/moonlink_service/src/rest_api.rs, src/moonlink_service/src/test.rs
We are currently mixing "table" (mooncake table concept) and "src table name" (similar to pg table source table concept) which is really bad, this PR tries to unify the naming style for all APIs:
- Use src table name for HTTP endpoints
- Use database and table name in the request and response payload
=> [REST] Fix improper naming

src/moonlink_metadata_store/src/config_utils.rs, src/moonlink_metadata_store/src/postgres/pg_metadata_store.rs, src/moonlink_metadata_store/src/postgres/sql/create_secrets.sql, src/moonlink_metadata_store/src/sqlite/sql/create_secrets.sql, src/moonlink_metadata_store/src/sqlite/sqlite_metadata_store.rs
Currently table config is implemented as follows:
- Table config in use contains config and secret, but metadata storage split them into two tables
- Persisted config is a subset of table config
For (1) the design motivation was:
- (major) Initial design and implementation is, metadata was stored at source postgres (aka, users' postgres), so have to do extra security mechanism
+ PR for reference: https://github.com/Mooncake-Labs/moonlink/pull/856
- It provides moonlink a way to get secret based on bucket and path
+ One good use case (unimplemented yet) is https://github.com/Mooncake-Labs/moonlink/blob/df49bc298280dd15deb49514928e1986f97f5866/src/moonlink_backend/src/lib.rs#L277-L295
- (minor) It provides clear responsibility separation and inspection for secrets
When I'm re-reviewing the …
=> [storage] [1/N] Rework metadata storage and config

Cargo.lock, src/moonlink_error/Cargo.toml, src/moonlink_error/src/error.rs
Closes https://github.com/Mooncake-Labs/moonlink/issues/2023
The bincode module uses a binary bit to indicate whether Option<String> is None or Some(value), which the original implementation did not support.
- [✓] Tests have been added or updated
=> Fix ErrorStruct source serialization

src/moonlink/src/storage/iceberg/file_catalog.rs, src/moonlink/src/storage/iceberg/glue_catalog.rs, src/moonlink/src/storage/iceberg/iceberg_table_manager.rs, src/moonlink/src/storage/iceberg/iceberg_table_syncer.rs, src/moonlink/src/storage/iceberg/moonlink_catalog.rs, src/moonlink/src/storage/iceberg/rest_catalog.rs, src/moonlink/src/storage/iceberg/utils.rs
Current all IO operations (including file indices upload, manifest file write, etc) are all blocking and sequential IO, which means IO latency simply accumulates. 
It's a known issue, this PR parallelize the upload.
Closes https://github.com/Mooncake-Labs/moonlink/issues/2047
=> [storage] Parallelize index import at iceberg snapshot

src/moonlink/src/storage/iceberg/tests.rs, src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/transaction_stream.rs
The bug is:
- Before streaming transaction commit, there're already completed async flush
- For the current implementation, it leaks for mooncake snapshot disk files
- But largest flush LSN is not updated, leading able to create iceberg snapshot
- Now the iceberg snapshot contains the completed flushed disk slice, which leads to data inconsistency for iceberg
Closes https://github.com/Mooncake-Labs/moonlink/issues/2049
=> [storage] Fix async flush with streaming commit

src/moonlink_backend/tests/test_postgres_source.rs, src/moonlink_connectors/src/pg_replicate.rs
When running standalone its possible our Moonlink instance crashes while Postgres stays up. If postgres doesn't drop the replication backend before a new instance comes up, Moonlink will error out: https://github.com/Mooncake-Labs/moonlink/issues/2003
We can preemptively kill any moonlink backends before creating our new postgres connection to avoid colliding with any stale Moonlinks that Postgres has yet to drop. 
Closes https://github.com/Mooncake-Labs/moonlink/issues/2006
- 
- 
-
=> Preemptively kill stale backend

src/moonlink/src/storage/iceberg/index.rs
add serde default & rename annotatinos to IndexBlock & FileIndex, ensuring that struct field modifications maintain backward compatibility for serialization and deserialization.
https://github.com/Mooncake-Labs/moonlink/issues/1573
- add serde default & rename annotatinos to IndexBlock & FileIndex
- 
-
=> [storage] Apply schema evolution mechanisms to iceberg index data structure

.github/workflows/ci.yml, src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/tests.rs, src/moonlink/src/table_handler.rs, src/moonlink/src/table_handler/table_handler_state.rs, src/moonlink_service/Cargo.toml, src/moonlink_service/src/test.rs
change the force_snapshot logic, very simple now:
if existing flush lsn is not enough for force_snapshot, and current commit lsn is enough, flush.
Also add a long running kafka simulation test.
- 
- 
-
=> fix_force_flush_logic

src/moonlink/Cargo.toml, src/moonlink/src/bin/profile_test.rs, src/moonlink/src/lib.rs, src/moonlink/src/table_handler/profile_test.rs
Add another profile test for append-only table, exactly the same CPU bottleneck as https://github.com/Mooncake-Labs/moonlink/issues/2089
=> Add profile test for append-only table

src/moonlink/src/storage/iceberg/catalog_utils.rs, src/moonlink/src/storage/iceberg/file_catalog.rs, src/moonlink/src/storage/iceberg/glue_catalog.rs, src/moonlink/src/storage/iceberg/iceberg_table_syncer.rs, src/moonlink/src/storage/iceberg/moonlink_catalog.rs, src/moonlink/src/storage/iceberg/rest_catalog.rs
Refactor deletion-vector sync workflow
- Merged `write_deletion_vector` into `sync_deletion_vector`.
- Introduced `prepare_deletion_vector_blob` and `finalize_deletion_vector`
to enable parallel execution.
I only tested the code using `cargo test -p moonlink`.
https://github.com/Mooncake-Labs/moonlink/issues/2046
=> Parallelize deletion vector sync

src/moonlink/src/bin/profile_test.rs, src/moonlink/src/lib.rs, src/moonlink/src/table_handler/profile_test.rs
This PR does a few things:
- Add a profile test which does no iceberg persistence, found most of the CPU is burnt on WAL entries serialization
- Log out the destination for profile file, and allow multiple flame graphs output
=> Add profile test with no persistence

src/moonlink/src/storage/index/persisted_bucket_hash_map.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs
Doing some random hunting on flame graph; found stable sorting takes ~1.59% CPU, switch to unstable ones seems to contribute ~0.6% reduction. A minor low-hanging fruit anyway.
=> [minor] Switch to unstable sort

src/moonlink/src/row/moonlink_row.rs, src/moonlink/src/storage/mooncake_table/batch_ingestion.rs
When reading the parquet for index build during batch ingestion we project only identity columns via `ProjectionMask`, but then compute the key using the generic `get_lookup_key` which assumes original column positions when indexing. This causes an out of bounds for any table that does not have the first column as a primary key. 
Added `get_lookup_key_from_identity_row` which assumes the row is already projected and contains only identity columns in identity order.
Closes https://github.com/Mooncake-Labs/moonlink/issues/2105
- Add `get_lookup_key_from_identity_row`
- Add regression test
-
=> Fix batch index build

src/moonlink/src/storage/iceberg/iceberg_table_manager.rs, src/moonlink/src/storage/iceberg/iceberg_table_syncer.rs, src/moonlink/src/storage/iceberg/table_manager.rs, src/moonlink/src/storage/iceberg/tests.rs, src/moonlink/src/storage/mooncake_table.rs, src/moonlink/src/storage/mooncake_table/persisted_records.rs, src/moonlink/src/storage/mooncake_table/persistence_buffer.rs, src/moonlink/src/storage/mooncake_table/replay/replay_events.rs, src/moonlink/src/storage/mooncake_table/snapshot.rs, src/moonlink/src/storage/mooncake_table/snapshot_persistence.rs, src/moonlink/src/storage/mooncake_table/table_creation_test_utils.rs, src/moonlink/src/storage/mooncake_table/table_operation_test_utils.rs, src/moonlink/src/storage/mooncake_table/table_snapshot.rs, src/moonlink/src/storage/mooncake_table/tests.rs, src/moonlink/src/storage/wal.rs, src/moonlink/src/storage/wal/test_utils.rs, src/moonlink/src/table_handler.rs, src/moonlink/src/table_handler/chaos_replay.rs, src/moonlink/src/table_handler/failure_tests.rs, src/moonlink/src/table_handler/table_handler_state.rs, src/moonlink/src/table_handler/test_utils.rs, src/moonlink/src/table_handler/tests.rs, src/moonlink/src/table_notify.rs, src/moonlink_connectors/src/pg_replicate.rs, src/moonlink_connectors/src/pg_replicate/table_init.rs
Iceberg acts as storage layer in moonlink, which is irrelevant from mooncake core concepts, like mooncake table and snapshot; current implementation is not coupled with iceberg, but concept leaked everywhere.
This PR updates most of naming in moonlink, left ones will be followup later.
=> Rename iceberg types and variables

Cargo.lock, Cargo.toml, src/moonlink/Cargo.toml, src/moonlink/src/error.rs, src/moonlink/src/storage.rs, src/moonlink/src/storage/deltalake.rs, src/moonlink/src/storage/deltalake/deltalake_table_config.rs, src/moonlink/src/storage/deltalake/deltalake_table_loader.rs, src/moonlink/src/storage/deltalake/deltalake_table_manager.rs, src/moonlink/src/storage/deltalake/deltalake_table_syncer.rs, src/moonlink/src/storage/deltalake/io_utils.rs, src/moonlink/src/storage/deltalake/test.rs, src/moonlink/src/storage/deltalake/utils.rs, src/moonlink/src/storage/iceberg/iceberg_table_manager.rs, src/moonlink/src/storage/iceberg/parquet_utils.rs, src/moonlink/src/storage/mooncake_table/table_creation_test_utils.rs, src/moonlink/src/storage/mooncake_table/table_operation_test_utils.rs, src/moonlink/src/storage/mooncake_table/test_utils_commons.rs
There're a few items for delta support MVP.
- Support data files sync and load
- Support deletion vector sync and load
- Support deletion vector upload for a data file
- Support index store and load
+ There's no puffin blob concept in delta as in iceberg, I will check further; in the worst case we could make assumption on its location, or record index file location in customized user-filled metadata.
- Support data files, deletion vectors and file indices removal (due to data compaction and index merge)
- Continue cleanup iceberg/delta concepts in mooncake and snapshot layer, extract common utils for them
- Integrate delta into mooncake table, snapshot, backend and metadata store
This PR does the first item: only data file store and load.
=> [1/N] Basic delta store and load for data files
