Mooncake-Labs/moonlink

src/moonlink/src/storage/index/persisted_bucket_hash_map.rs

This PR fixes hash index merge, which should consider file id remapping when merge.

[storage] Fix hash index merge

---

src/moonlink/src/storage/mooncake_table/snapshot.rs

This is something I miss in my prev PR, should reduce overall lines of code in the `update_snapshot` for easier understanding (it's already long enough).
I tested with pg_mooncake large batch of insertion and deletion:
```sql
pg_mooncake (pid: 5665) =# DROP EXTENSION IF EXISTS pg_mooncake CASCADE;
INSERT INTO r SELECT a, 'val_' || a FROM generate_series(1, 2000000) AS a;
SELECT count(*) FROM c;
DELETE FROM r WHERE a % 1 = 0;
SELECT COUNT(*) FROM c LIMIT 10;
NOTICE:  drop cascades to table c
DROP EXTENSION
DROP TABLE
CREATE TABLE
CALL
INSERT 0 2000000
count  
---------
2000000
(1 row)
DELETE 2000000
count 
-------
0
(1 row)
```

[minor] Clean up mooncake snapshot creation

---

README.md

Current link is broken, place code reference for now, could have a separate doc page for connections.
CC @paurora17

[readme] Fix broken connector link

---

Cargo.lock
Cargo.toml

Regular upgrade iceberg-rust to avoid pain points to do large upgrade leaps.

[deps] Regular upgrade for iceberg-rust

---

.github/workflows/ci.yml
deny.toml

I plan to integrate dependabot into our repo, which automatically submit PRs when stale dependency detected;
before that we need to ensure dependencies are properly checked in CI.
I have intentionally made bad changes to our dependency and verify the cargo check works.
https://github.com/dentiny/moonlink/actions/runs/15477562386/job/43576574619

[CI] Add dependency check into CI

---

README.md

edits to readme.

---

src/moonlink_connectors/src/pg_replicate/moonlink_sink.rs
src/moonlink_connectors/src/pg_replicate/replication_state.rs
src/moonlink_connectors/src/replication_connection.rs

There are a number of silent failures in replication and sink. We should just panic for now until we have support for better error propagation. 
- 
- 
-

Panic on any replication or sink errors

---

src/moonlink/src/storage/cache/object_storage.rs
src/moonlink/src/storage/cache/object_storage/base_cache.rs
src/moonlink/src/storage/cache/object_storage/cache_handle.rs
src/moonlink/src/storage/cache/object_storage/object_storage_cache.rs
src/moonlink/src/storage/cache/object_storage/state_tests.rs
src/moonlink/src/storage/cache/object_storage/test_utils.rs

I revisited the cache usage and sightly updated the interface; this time I use state-machine based test to check all possible state transitions.

[storage] Update cache interface and add state-based tests

---

Cargo.lock
Cargo.toml

Regular upgrade, to manually fix dependabot PRs.
Closes https://github.com/Mooncake-Labs/moonlink/pull/463
Closes https://github.com/Mooncake-Labs/moonlink/pull/462

Dependency upgrade

---

Cargo.lock
Cargo.toml
src/moonlink/src/storage/iceberg/file_catalog.rs
src/moonlink/src/storage/iceberg/iceberg_table_manager.rs

Sync iceberg-rust upstream code and fix interface usage.
Closes https://github.com/Mooncake-Labs/moonlink/issues/466

[storage] Sync iceberg-rust to upstream and fix compilation

---

src/moonlink_backend/tests/test_backend.rs

Clean up integration tests to be consistent with setup and tear down
- add `cleanup_test` to be called after each test
- make sure all tests use `setup_backend ` 
-

Clean up integration tests

---

Cargo.lock
Cargo.toml

Pin all `rust-postgres` crates to use latest revision. 
- 
- 
-

Pin rust postgres

---

src/moonlink_backend/tests/test_backend.rs
src/moonlink_connectors/src/replication_connection.rs

Test 1M rows insert in integration test to catch any hangs/perf issues early.
- 
- 
-

1M row insert integration test

---

src/moonlink_backend/tests/test_backend.rs

Move test guard to test utils section. Forgot to do this previously. 
- 
- 
-

Move test guard to test utils

---

src/moonlink/src/storage/mooncake_table/data_file_state_tests.rs

Add missing unit test for data file and file indices generated by streaming write.
Closes https://github.com/Mooncake-Labs/moonlink/issues/521

[storage] Add unit test for stream write and data file cache

---

src/moonlink_backend/src/lib.rs

Tested by pg_mooncake
```sql
pg_mooncake (pid: 89795) =# DROP TABLE IF EXISTS r;
INSERT INTO r VALUES (1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e'), (6, 'f');
CALL mooncake.create_snapshot('c');
UPDATE r SET b = a + 1 WHERE a = 3 or a = 5;
CALL mooncake.create_snapshot('c');
SELECT * FROM c;
DROP TABLE
NOTICE:  drop cascades to table c
DROP EXTENSION
CREATE TABLE
CALL
INSERT 0 6
CALL
UPDATE 2
CALL
a | b 
---+---
3 | 4
5 | 6
1 | a
2 | b
4 | d
6 | f
(6 rows)
```
Closes https://github.com/Mooncake-Labs/moonlink/issues/549

[minor] Address unused variable clippy warning

---

src/moonlink/src/storage/index.rs
src/moonlink/src/storage/index/cache_utils.rs
src/moonlink/src/storage/mooncake_table/disk_slice.rs
src/moonlink/src/storage/mooncake_table/snapshot.rs
src/moonlink/src/storage/mooncake_table/transaction_stream.rs

This is something I missed in the previous PR, I should extract file index cache import into a separate common util function.

[minor] Extract util functions to import file index

---

src/moonlink/src/storage/mooncake_table.rs
src/moonlink/src/table_handler.rs
src/moonlink/src/table_handler/test_utils.rs
src/moonlink/src/table_handler/tests.rs

This PR deletes mooncake table directory on drop table event.
Closes https://github.com/Mooncake-Labs/moonlink/issues/573

[storage] Delete mooncake table directory on drop table

---

src/moonlink/src/storage/mooncake_table/deletion_vector_puffin_state_tests.rs

As titled, this PR adds unit test for deletion vector tests with local filesystem optimization.
Most of the state machine behavior is the same with or without optimization enabled, but those involving deletion are not.
Test statements (with slight modification on moonlink code):
```sql
pg_mooncake (pid: 195154) =# DROP EXTENSION IF EXISTS pg_mooncake CASCADE;
INSERT INTO r SELECT a, 'val_' || a FROM generate_series(1, 10) AS a;
SELECT count(*) FROM c;
NOTICE:  drop cascades to table c
DROP EXTENSION
DROP TABLE
CREATE TABLE
CALL
INSERT 0 10
^[[A count 
-------
10
(1 row)
pg_mooncake (pid: 195154) =# CALL mooncake.create_snapshot('c');
CALL …
```

[storage] [2/N] Add unit test for puffin file state test with local fs optimization

---

src/moonlink/src/storage/mooncake_table.rs

A minor change to add logging message, at least we're able to know what's the flush LSN.
Closes https://github.com/Mooncake-Labs/moonlink/issues/587

[minor] Add logging message for assertion failure

---

src/moonlink_backend/src/lib.rs

`base_path` passed in should be respected.

[storage] Base mooncake directory upon mooncake directory

---

src/moonlink/src/storage/mooncake_table/data_file_state_tests.rs

Current unit test implementation doesn't align with the intended state transfer testing scenario.

[storage] Fix data file state test

---

src/moonlink/src/storage/mooncake_table/data_file_state_tests.rs
src/moonlink/src/storage/mooncake_table/deletion_vector_puffin_state_tests.rs

When debugging mooncake table bug, I found I almost have zero test coverage for stream write.
State transfer is the same, and we expect the same output for each state, so use parameterized tests everywhere.

[storage] Add unit tests with stream write

---

src/moonlink/src/storage/iceberg.rs
src/moonlink/src/storage/iceberg/file_catalog.rs
src/moonlink/src/storage/iceberg/file_catalog_test_utils.rs

An easy change to apply table update requirements at commit.
Closes https://github.com/Mooncake-Labs/moonlink/issues/608

[storage] Apply requirement at iceberg table commit

---

src/moonlink_metadata_store/src/error.rs
src/moonlink_metadata_store/src/postgres/pg_metadata_store.rs
src/moonlink_metadata_store/src/postgres/sql/create_tables.sql
src/moonlink_metadata_store/tests/common/test_environment.rs

Fix a few issues:
- Place metadata table under `mooncake` schema, instead of default `public` schema
- Put table creation schema in a separate file for schema evolution
Closes https://github.com/Mooncake-Labs/moonlink/issues/613

[storage] Fix table metadata store schema

---

Cargo.lock
Cargo.toml
src/moonlink/src/storage/iceberg/file_catalog.rs

I need to check how iceberg table retry property works.

Regular upgrade iceberg-rust

---

src/moonlink/src/lib.rs
src/moonlink/src/storage.rs
src/moonlink/src/storage/iceberg.rs
src/moonlink/src/storage/iceberg/table_event_manager.rs
src/moonlink/src/storage/iceberg/test_utils.rs
src/moonlink/src/storage/mooncake_table.rs
src/moonlink/src/storage/mooncake_table/data_file_state_tests.rs
src/moonlink/src/storage/mooncake_table/deletion_vector_puffin_state_tests.rs
src/moonlink/src/storage/mooncake_table/file_index_state_tests.rs
src/moonlink/src/storage/mooncake_table/snapshot.rs
src/moonlink/src/storage/mooncake_table/snapshot_read_output.rs
src/moonlink/src/storage/mooncake_table/state_test_utils.rs
src/moonlink/src/storage/mooncake_table/table_snapshot.rs
src/moonlink/src/storage/mooncake_table/test_utils.rs
src/moonlink/src/table_handler.rs
src/moonlink/src/table_handler/test_utils.rs
src/moonlink/src/table_handler/tests.rs
src/moonlink/src/table_notify.rs
src/moonlink/src/union_read/read_state.rs
src/moonlink_backend/src/lib.rs
src/moonlink_connectors/src/pg_replicate/table_init.rs
src/moonlink_connectors/src/replication_connection.rs
src/moonlink_connectors/src/replication_manager.rs

This PR combines table notification and table events into one in the eventloop.
Closes https://github.com/Mooncake-Labs/moonlink/issues/635

[storage] Combine table events in eventloop

---

Cargo.lock
Cargo.toml

I upstream a change for transaction commit retry.

Upgrade iceberg-rust

---

src/moonlink_backend/src/columnstore_table_id.rs
src/moonlink_backend/src/lib.rs
src/moonlink_backend/tests/test_backend.rs
src/moonlink_connectors/src/replication_manager.rs

Split table id and database id for access inside moonlink.

[backend] Update table id and database id

---

src/moonlink/src/storage/mooncake_table/persistence_buffer.rs
src/moonlink/src/storage/mooncake_table/snapshot.rs

A minor no-op change, I would like to simplify the `update_snapshot`, which is most important control plane logic.

[minor] Simplify update_snapshot function

---

src/moonlink_backend/tests/test_backend.rs

Replace bad sleep-based integration test with proper synchronization with WAL LSN.
(It's easier than I thought, I should combine it with the previous PR...)
Closes https://github.com/Mooncake-Labs/moonlink/issues/669

[backend] Remove all sleep in backend test

---

src/moonlink_backend/src/file_utils.rs
src/moonlink_backend/src/lib.rs
src/moonlink_backend/src/recovery_utils.rs
src/moonlink_backend/tests/common.rs
src/moonlink_backend/tests/test_backend.rs

- Update `MoonlinkBackend::new` with uris, which is required for recovery
- Extract file and recovery related functions / commons into a separate file
I tested manually with the sql documented here: https://docs.google.com/document/d/1Go02j9Nv2HrhABM-GBpBA4lPACJG3twC58J8pnKHAmA/edit?usp=sharing
Closes https://github.com/Mooncake-Labs/moonlink/issues/678

[backend] Update backend interface with recovery

---

src/moonlink/src/storage/mooncake_table.rs

This PR triggers mooncake snapshot after a successful iceberg snapshot.
I tested with the following SQL:
```sql
INSERT INTO r SELECT g, 'val_' || g FROM generate_series(1, 1000000) g;
CALL mooncake.create_snapshot('c');
```
and confirm all persisted files are deleted, thus no double storage on local filesystem.
Closes https://github.com/Mooncake-Labs/moonlink/issues/713

[storage] Perform mooncake snapshot after iceberg persistence

---

src/moonlink/src/storage/iceberg/table_event_manager.rs
src/moonlink/src/table_handler.rs
src/moonlink/src/table_handler/tests.rs
src/moonlink/src/table_notify.rs

This PR performs force snapshot based on time interval.
The overall implementation is largely based on existing infra, like force snapshot table events and timer events.
I manually checked in pg_mooncake, and confirmed iceberg snapshot does gets created.
Closes https://github.com/Mooncake-Labs/moonlink/issues/472

[storage] Periodical force snapshot

---

src/moonlink/benches/benchmark.md
src/moonlink/benches/microbench_index_stress.rs
src/moonlink/benches/microbench_write_mooncake_table.rs
src/moonlink/src/storage/index/persisted_bucket_hash_map.rs

improve benchmarks and add instruction for flamegraph
- 
- 
-

improve benchmarks and add instruction for flamegraph

---

src/moonlink_backend/src/lib.rs
src/moonlink_backend/src/recovery_utils.rs

Use correct src uri for replciation start. 
- 
- 
-

Use correct uri

---

.github/ISSUE_TEMPLATE/bug_report.md

chatgpt told me title and description is necessary for templates, our current setup seems to be broken.
Unfortunately I don't have a way to test, since forked repo doesn't allow creating issues :(

Add bug report title

---

src/moonlink/src/storage/iceberg/file_catalog.rs
src/moonlink/src/storage/iceberg/file_catalog_test.rs
src/moonlink/src/storage/iceberg/state_tests.rs
src/moonlink/src/storage/iceberg/tests.rs
src/moonlink/src/storage/mooncake_table/table_creation_test_utils.rs
src/moonlink/src/storage/mooncake_table/table_snapshot.rs
src/moonlink/src/storage/mooncake_table/validation_test_utils.rs
src/moonlink/src/table_handler.rs

This PR updates iceberg-related tests (except state-based ones) to leverage object storage, also delete a few unnecessary.
Closes https://github.com/Mooncake-Labs/moonlink/issues/772

[storage] Update test cases to interact with object storage

---

src/moonlink/src/storage/mooncake_table/data_file_state_tests.rs

This PR is the first part of state-machine-based unit test refactoring, which aims to extract common functions to (1) prepare initial state, and (2) validate end state.
To reduce change set (it's already a non-trivial PR), I start with the largest test file, and this PR include half of the tests.
I will try to put separate PRs to refactor tests by tests.

[storage] [1/N] Refactor state machine tests

---

src/moonlink/src/storage/mooncake_table/data_file_state_tests.rs

Followup for https://github.com/Mooncake-Labs/moonlink/pull/793

[storage] [2/N] Refactor data file cache state machine test

---

src/moonlink/src/storage/filesystem/accessor/filesystem_accessor.rs
src/moonlink/src/storage/filesystem/filesystem_config.rs
src/moonlink/src/storage/filesystem/s3/s3_test_utils.rs
src/moonlink/src/storage/iceberg/utils.rs
src/moonlink_connectors/src/pg_replicate/table_init.rs
src/moonlink_metadata_store/src/postgres/config_utils.rs

This PR updates moonlink integration with S3, and verified it works.
Result see https://github.com/Mooncake-Labs/moonlink/issues/791#issuecomment-3058321244
Closes https://github.com/Mooncake-Labs/moonlink/issues/791

[storage] Object storage S3 integration

---

src/moonlink/src/storage/iceberg/tokio_retry_utils.rs

otherwise we loss observability for the system.
Closes https://github.com/Mooncake-Labs/moonlink/issues/840

[minor] Add error logging for iceberg error

---

src/moonlink/src/table_handler.rs

In the current implementation, when a table is dropped, eventloop exits, but timer events still keep alive.
The reason is: at destruction of join handle, it doesn't explicit join the task, instead the task will get detached.
The most authentic fix would be explicit synchronization via oneshot channel, but here I take the easy fix:
sending to a channel only fails when receiver has been dropped, so it doesn't make sense to keep the timer, ignore and exit is the proper fix.
Closes https://github.com/Mooncake-Labs/moonlink/issues/829

[storage] Exit timer events if send failure

---

src/moonlink/src/storage/mooncake_table.rs
src/moonlink/src/storage/mooncake_table/transaction_stream.rs
src/moonlink/src/table_handler.rs
src/moonlink/src/table_handler/tests.rs
src/moonlink/src/table_notify.rs
src/moonlink_connectors/src/pg_replicate/initial_copy.rs
src/moonlink_connectors/src/pg_replicate/moonlink_sink.rs
src/moonlink_connectors/src/replication_connection.rs

TableHandler refactoring before enabling alter table 

---

Cargo.lock
Cargo.toml

There's a dependency leak issue for iceberg-rust, I put a PR for it and got merged.

Fix test dependency leak

---

src/moonlink/src/storage/iceberg/iceberg_table_loader.rs
src/moonlink/src/storage/iceberg/iceberg_table_syncer.rs
src/moonlink/src/storage/iceberg/index.rs
src/moonlink/src/storage/io_utils.rs
src/moonlink/src/storage/mooncake_table/table_operation_test_utils.rs
src/moonlink/src/table_handler.rs

As titled, this PR is a trivial change to avoid unnecessary copies.
Closes https://github.com/Mooncake-Labs/moonlink/issues/853

[minor] Avoid copy on file deletion

---

src/moonlink/src/storage/iceberg/table_event_manager.rs
src/moonlink/src/storage/iceberg/tests.rs
src/moonlink/src/storage/mooncake_table.rs
src/moonlink/src/storage/mooncake_table/snapshot.rs
src/moonlink/src/storage/mooncake_table/table_operation_test_utils.rs
src/moonlink/src/table_handler.rs
src/moonlink/src/table_handler/test_utils.rs
src/moonlink/src/table_handler/tests.rs
src/moonlink/src/table_notify.rs
src/moonlink_backend/src/lib.rs
src/moonlink_connectors/src/pg_replicate/table_init.rs

This PR implement force index merge; but it's worth noticing the function returns right after index merge completes, rather change persisted to iceberg table, worth a second thought.
Closes https://github.com/Mooncake-Labs/moonlink/issues/447

[storage] Implement force index merge

---

src/moonlink/src/storage/iceberg/table_event_manager.rs
src/moonlink/src/table_handler.rs
src/moonlink/src/table_handler/test_utils.rs
src/moonlink/src/table_handler/tests.rs
src/moonlink/src/table_notify.rs
src/moonlink_backend/src/lib.rs
src/moonlink_connectors/src/pg_replicate/table_init.rs

Add a command to force data compaction, so we could test on pg_mooncake side.
Closes https://github.com/Mooncake-Labs/moonlink/issues/448

[storage] Implement force data compaction

---

src/moonlink_backend/src/error.rs
src/moonlink_backend/src/lib.rs

Discussed offline, the unified interface will be used for pg_mooncake and other use cases.

[backend] Provide a unified interface to optimize table

---

src/moonlink_connectors/Cargo.toml

The same feature applies to all crates, otherwise they're completely independency for different crates.

Fix connector features

---

src/moonlink_metadata_store/src/sqlite/sqlite_metadata_store.rs
src/moonlink_metadata_store/src/sqlite/tests.rs

This PR implements metadata deletion for sqlite metadata store, next PR would be integration.
Related to https://github.com/Mooncake-Labs/moonlink/issues/884

[storage] [2/N] Implement deletion for sqlite metadata store

---

src/moonlink_connectors/src/replication_manager.rs

Fix confusing naming. We have clear definition and naming convention:
- mooncake table id: database id + mooncake table id
- src table id: id of table which we replicate from
- table id: mooncake table id

[minor] Fix confusing table id naming

---

src/moonlink/src/storage/iceberg/file_catalog_test.rs

Minor improvement to use RAII-style testing guard.

[minor] Use test guard for iceberg catalog test

---

src/moonlink/src/storage/iceberg/iceberg_table_loader.rs
src/moonlink/src/storage/iceberg/iceberg_table_syncer.rs
src/moonlink/src/storage/iceberg/schema_utils.rs

This PR validates on store and load operation, whether iceberg table schema matches mooncake metadata one.
Closes https://github.com/Mooncake-Labs/moonlink/issues/938

[storage] Validate iceberg table schema consistency

---

src/moonlink/src/storage/iceberg.rs
src/moonlink/src/storage/iceberg/file_catalog.rs
src/moonlink/src/storage/iceberg/file_catalog_test.rs
src/moonlink/src/storage/iceberg/file_catalog_test_utils.rs
src/moonlink/src/storage/iceberg/iceberg_schema_manager.rs
src/moonlink/src/storage/iceberg/iceberg_table_manager.rs
src/moonlink/src/storage/iceberg/moonlink_catalog.rs
src/moonlink/src/storage/iceberg/schema_utils.rs
src/moonlink/src/storage/iceberg/table_commit_proxy.rs
src/moonlink/src/storage/iceberg/table_manager.rs
src/moonlink/src/storage/iceberg/tests.rs
src/moonlink/src/storage/mooncake_table.rs
src/moonlink/src/storage/mooncake_table/table_creation_test_utils.rs

This PR implements schema evolution for iceberg. 
Since iceberg-rust doesn't support schema interface in transaction yet, I wrap everything into self-owned file catalog.
Closes https://github.com/Mooncake-Labs/moonlink/issues/928

[storage] Iceberg schema evolution

---

Cargo.lock
Cargo.toml
src/moonlink/src/storage/iceberg.rs
src/moonlink/src/storage/iceberg/iceberg_table_syncer.rs
src/moonlink/src/storage/iceberg/schema_utils.rs

This PR validates iceberg table schema id has been properly assigned.

[storage] Assert iceberg schema id

---

src/moonlink/src/storage/mooncake_table.rs
src/moonlink/src/storage/mooncake_table/snapshot.rs

Followup for https://github.com/Mooncake-Labs/moonlink/pull/935, to provide interface for WAL -> iceberg snapshot.
CC @lohpaul9

[storage] Provide interface to set WAL metadata

---

src/moonlink/src/storage/compaction/compactor.rs

A minor improvement to avoid string copy.

[minor] Avoid one copy for data file

---

src/moonlink_connectors/src/pg_replicate/clients/postgres.rs

Currently we error when attempting to add a table that is already part of the publication. We should ignore the error in this case since we want to support the use case where a single rowstore replicates to multiple moonlink tables. 
We should first query the publication to see if the table is already added, and only add the table if not already present. 
This allows us to do something like 
`CALL mooncake.create_table('c', 'r');`
`CALL mooncake.create_table('d', 'r');`
`CALL mooncake.create_table('e', 'r');`
Closes https://github.com/Mooncake-Labs/moonlink/issues/944
- 
- 
-

Support multiple moonlink tables for single rowstore

---

src/moonlink_connectors/src/pg_replicate/clients/postgres.rs

Reverts Mooncake-Labs/moonlink#948

Revert "Support multiple moonlink tables for single rowstore"

---

src/moonlink_connectors/src/replication_manager.rs

Trivial no-op change to extract a common util function.

[minor] [pg] Extract util to get replication connection

---

src/moonlink/src/table_handler.rs
src/moonlink/src/table_handler/tests.rs

Index merge state doesn't need to be set on force full compaction
Closes https://github.com/Mooncake-Labs/moonlink/issues/952

[storage] Fix index merge request state

---

src/moonlink/src/storage/iceberg/iceberg_table_loader.rs
src/moonlink/src/storage/iceberg/schema_utils.rs
src/moonlink/src/storage/mooncake_table.rs
src/moonlink/src/storage/mooncake_table/persistence_buffer.rs
src/moonlink/src/storage/mooncake_table/snapshot.rs
src/moonlink/src/storage/mooncake_table/snapshot_validation.rs

Enable more expensive assertions in debug build.
Closes https://github.com/Mooncake-Labs/moonlink/issues/979

[minor] Lift assertions to debug build

---

src/moonlink/src/storage/mooncake_table/table_snapshot.rs

Payload debugging format is too spammy and verbose, which accounts for my whole screen.
Not a regression because it's only used in chaos test which I added this morning.
Closes https://github.com/Mooncake-Labs/moonlink/issues/986

[minor] Trim a few table payload debug format

---

src/moonlink/src/table_handler.rs
src/moonlink/src/table_handler/table_handler_state.rs

This PR fixes three issues:
- (tech debt) we have two states indicating the state that "there's ongoing table maintenance events", one for `maintenance_ongoing`, another for `maintenance_process_status`
- (bug) related to the above issue, we use `maintenance_ongoing` to decide whether could trigger a new maintenance event, but assert on the later; in one word, they're not kept in sync
- (bug) not all completion sender has corresponding receiver assigned, so ignore send result in a few places
I have checked with chaos test.
Closes https://github.com/Mooncake-Labs/moonlink/issues/985
Closes https://github.com/Mooncake-Labs/moonlink/issues/971

[storage] Fix table maintenance state

---

.github/workflows/ci.yml

As titled.
Closes https://github.com/Mooncake-Labs/moonlink/issues/989

[CI] Add chaos test to CI

---

src/moonlink/src/error.rs
src/moonlink/src/row/moonlink_row.rs
src/moonlink/src/row/moonlink_type.rs
src/moonlink/src/storage.rs
src/moonlink/src/storage/filesystem/accessor/filesystem_accessor.rs
src/moonlink/src/storage/iceberg/table_manager.rs
src/moonlink/src/storage/wal.rs
src/moonlink/src/storage/wal/test_utils.rs
src/moonlink/src/storage/wal/tests.rs

Adds WAL class, currently only enabled for local disk storage.
#968 
- Introduces new WAL events and WAL logic for inserting, flushing, deletion
- Converts between WAL events and supported TableEvents 
- [ X] Code builds correctly
- [ X] Tests have been added or updated

Wal prototype

---

src/moonlink_connectors/src/pg_replicate/conversions/text.rs

Remove trailing space in char column

---

src/moonlink/src/storage/mooncake_table/test_utils.rs
src/moonlink/src/table_handler/chaos_test.rs
src/moonlink/src/table_handler/test_utils.rs

This PR fixes how chaos test decided rows to delete: in non-streaming case, it should be committed and undeleted ones.

[chaos] Validate snapshot read

---

src/moonlink/src/storage/iceberg/iceberg_table_syncer.rs
src/moonlink/src/table_handler.rs
src/moonlink/src/table_handler/chaos_test.rs
src/moonlink/src/table_handler/table_handler_state.rs

- Add foreground force snapshot into chaos test;
- Fix a few bugs related to force snapshot.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1014
Closes https://github.com/Mooncake-Labs/moonlink/issues/1013

[storage] Fix force snapshot

---

src/moonlink/src/storage/compaction/table_compaction.rs
src/moonlink/src/storage/filesystem/accessor/filesystem_accessor.rs
src/moonlink/src/storage/mooncake_table/table_snapshot.rs

Update formatting, so debugging string won't flood my screen.

[minor] Further trim formatting

---

src/moonlink/src/storage/mooncake_table/snapshot.rs
src/moonlink/src/storage/mooncake_table/snapshot_read.rs

Missed in the previous refactor.
Closes http://github.com/Mooncake-Labs/moonlink/issues/1037

[minor] Move delete log get to a separate file

---

src/moonlink/src/storage/mooncake_table/table_snapshot.rs

Continued formatting refinement. My debugging experience is count number is useful enough.

[minor] Formatting refinement cont

---

src/moonlink/src/storage/mooncake_table/snapshot_persistence.rs

See https://github.com/Mooncake-Labs/moonlink/issues/1033#issuecomment-3116730159 for details.
It's hard to do manual testing, since it requires two concurrent background threads, one for compaction, another for iceberg snapshot, issued and completed at certain timing.
Manual synchronization is also awkward, since if file handle not pinned, files will get deleted after compaction.
So I checked with chaos test.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1033

[storage] Allow puffin blob unfound at persistence

---

src/moonlink_backend/tests/test_backend.rs

Reflect iceberg default namespace change.

[backend] Fix iceberg warehouse test

---

src/moonlink/src/storage/wal.rs
src/moonlink/src/storage/wal/test_utils.rs
src/moonlink/src/storage/wal/tests.rs

Make changes to WAL design to handle streaming transactions
Closes #1055

wal redesign for streaming txn cases

---

src/moonlink/src/storage/mooncake_table/snapshot_maintenance.rs

This PR is a no-op change, which adds validation to compaction payload, and does a minor optimization to avoid copies.

[storage] Validate compaction payload

---

src/moonlink/src/storage/mooncake_table/snapshot_read_output.rs
src/moonlink/src/storage/mooncake_table/table_operation_test_utils.rs
src/moonlink/src/table_handler.rs
src/moonlink/src/table_notify.rs

... otherwise it's painful to see evicted files to delete flooding the whole screen.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1114

[storage] Wrap evicted files to delete

---

src/moonlink/src/storage/mooncake_table.rs
src/moonlink/src/storage/mooncake_table/table_operation_test_utils.rs
src/moonlink/src/table_handler.rs
src/moonlink/src/table_handler/chaos_test.rs
src/moonlink/src/table_notify.rs

otherwise my screen gets flooded by hundreds of evicted files

[minor] Update evicted files formatting

---

src/moonlink/src/storage/filesystem/accessor/filesystem_accessor_chaos_wrapper.rs
src/moonlink/src/storage/filesystem/accessor/operator_utils.rs
src/moonlink/src/storage/filesystem/accessor_config.rs
src/moonlink/src/storage/mooncake_table/table_creation_test_utils.rs

This PR adds timeout to all attempts for all IO operations, with retry attempts included.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1106

[storage] Apply timeout on all IO operations

---

src/moonlink/src/storage/filesystem/accessor_config.rs
src/moonlink/src/storage/filesystem/storage_config.rs

Declare all storage-related configs as (de)serializable, and allow some of them default, so we don't need always fill them.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1137

[storage] Improve storage config serde

---

CONTRIBUTING.md

Add an initial contributing doc on dev env setup, build, test and format.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1141

[doc] Initial contributing doc

---

src/moonlink/src/table_handler/chaos_test.rs

Unconfirmed tentative fix for channel send errors.

[chaos] Drop table in sync fashion

---

src/moonlink/src/storage/mooncake_table.rs
src/moonlink/src/storage/wal.rs
src/moonlink/src/storage/wal/test_utils.rs
src/moonlink/src/table_handler.rs
src/moonlink/src/table_handler/test_utils.rs
src/moonlink/src/table_notify.rs

otherwise it's hard to view replay log
Closes https://github.com/Mooncake-Labs/moonlink/issues/1173

[minor] Attach UUID to table events

---

src/moonlink/src/storage/compaction/compactor.rs

On compaction there're two mapping involved:
- old record location -> new record location, used for index remapping
- new record location -> file index, used to decide `seg_idx` inside of compacted file index
I used two hashmaps in the current implementation, with each of them storing every valid row in the map.
But the second mapping could be calculated easily via simple math, which grows sequentially.
In theory, this PR fix should cut down all hash-related operation latency into half.
Benchmark, same setup as https://github.com/Mooncake-Labs/moonlink/pull/1174
- before: 7 seconds, including 3 sec for data file, 4 sec for file indices
- after: 4.5 seconds, including 2.7 sec for data file, 1.8 sec for file indices

[storage] Fix and optimize file index calculation

---

src/moonlink/src/storage/compaction/tests.rs
src/moonlink/src/storage/iceberg/tests.rs
src/moonlink/src/storage/mooncake_table/delete_vector.rs
src/moonlink/src/storage/mooncake_table/transaction_stream.rs

The return value does indicate problem so we need to check it.

[storage] Mark row deletion return as must use

---

src/moonlink/src/storage/wal.rs

... otherwise the debugging message is too spammy for chaos test.
CC @lohpaul9

[minor] Update persistence update formatting

---

Cargo.lock
src/moonlink_backend/src/lib.rs
src/moonlink_backend/tests/common.rs
src/moonlink_backend/tests/test_backend.rs
src/moonlink_backend/tests/test_initial_copy.rs
src/moonlink_connectors/Cargo.toml
src/moonlink_connectors/src/error.rs
src/moonlink_connectors/src/lib.rs
src/moonlink_connectors/src/pg_replicate/table_init.rs
src/moonlink_connectors/src/replication_connection.rs
src/moonlink_connectors/src/replication_manager.rs
src/moonlink_connectors/src/rest_ingest.rs
src/moonlink_connectors/src/rest_ingest/json_converter.rs
src/moonlink_connectors/src/rest_ingest/moonlink_rest_sink.rs
src/moonlink_connectors/src/rest_ingest/rest_source.rs
src/moonlink_service/Cargo.toml
src/moonlink_service/examples/rest_api_demo.rs
src/moonlink_service/src/lib.rs
src/moonlink_service/src/main.rs
src/moonlink_service/src/rest_api.rs
src/moonlink_service/src/rpc_server.rs

Implement RestApi for directly ingesting into moonlink

---

src/moonlink/src/error.rs

As titled
Follow up on https://github.com/Mooncake-Labs/moonlink/pull/1242#discussion_r2260261360
- 
- 
-

[Fix] debug_assert to assert in moonlink error

---

src/moonlink/src/lib.rs
src/moonlink/src/storage.rs
src/moonlink/src/storage/timer.rs
src/moonlink/src/storage/timer/base_timer.rs
src/moonlink/src/storage/timer/fake_timer.rs
src/moonlink/src/storage/timer/tokio_timer.rs
src/moonlink/src/table_handler.rs
src/moonlink/src/table_handler/chaos_test.rs
src/moonlink/src/table_handler/test_utils.rs
src/moonlink/src/table_handler_timer.rs
src/moonlink_connectors/src/pg_replicate/table_init.rs

The first PR to make chaos test 100% deterministic, plan to replace real timer with fake timer from chaos test.

[storage] Table handler takes timer for periodical events

---

src/moonlink_connectors/src/pg_replicate.rs
src/moonlink_connectors/src/pg_replicate/table_init.rs
src/moonlink_connectors/src/replication_connection.rs

Minor code clean up, otherwise function arguments too messy.

[minor] Slight cleanup for table init function

---

src/moonlink_service/Cargo.toml

toml file needs to upgrade as well

[CI] Fix tower http upgrade

---

.github/dependabot.yml

Current config for dependabot only updates lock file but not toml file, which breaks main branch: https://github.com/Mooncake-Labs/moonlink/pull/1337

[CI] Dependabot updates toml file

---

deny.toml

Fix license allow list comment (it's comment upon moonlink license, but not BSL-1.0), also reorder it to be alphabetically sorted.

[minor] Fix license allow list comment

---

src/moonlink/src/row/moonlink_row.rs
src/moonlink_connectors/src/rest_ingest/datetime_utils.rs
src/moonlink_connectors/src/rest_ingest/json_converter.rs

- Fix timestamp with timezone parsing, we need to consider DST change, which leads to multiple possibilities and non-existent timestamp
- Add comments for timezone handling override

[storage] Fix timestamp with timezone parse

---

src/moonlink/src/table_handler/chaos_test.rs

..., which is very common for SQL tests

[chaos] Support update operations for chaos test

---

src/moonlink/src/table_handler/chaos_test.rs

Uncommitted inserted and undeleted rows are valid candidate for update operations.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1398

[chaos] Allow update uncommitted new rows

---

.github/workflows/ci.yml
src/moonlink/src/table_handler/chaos_test.rs

so we could download persisted events to local filesystem and replay.

[CI] Dump chaos test events

---

src/moonlink/src/storage/mooncake_table/transaction_stream.rs

Fix assert after #1412

---

src/moonlink_connectors/src/pg_replicate/util.rs

Add missing test case for nested composite type -> arrow type conversion.

Add type test for pg nested composite type to arrow

---

src/moonlink_connectors/src/pg_replicate/moonlink_sink.rs

For each CDC event, `Sink::process_cdc_event` awaits on `event_sender.send(..).await`, processing rows strictly serially. This prevents batching and propagates table-handler latency back to the replication stream, limiting throughput for append-heavy workloads.
Adds a simple helper to use the non-blocking `try_send` first and fall back to blocking `send` when the channel is full, preserving event order while reducing per-row await overhead. 
- 
- 
-

Use try_send fast path

---

src/moonlink/src/storage/mooncake_table.rs
src/moonlink/src/storage/mooncake_table/disk_slice.rs
src/moonlink/src/storage/mooncake_table/table_operation_test_utils.rs
src/moonlink/src/storage/mooncake_table/transaction_stream.rs
src/moonlink/src/table_handler.rs
src/moonlink/src/table_handler/chaos_replay.rs
src/moonlink/src/table_notify.rs

- Add mooncake snapshot related replay features, and related assertion logic
- Add transaction abort, which is related to the expected disk files
My test event stream:
```
{"config":{"mem_slice_size":18446744073709551615,"snapshot_deletion_record_count":1000,"batch_size":128,"disk_slice_writer_config":{"parquet_file_size":2097152,"chaos_config":null},"persistence_config":{"new_data_file_count":1,"new_committed_deletion_log":1000,"new_compacted_data_file_count":1,"old_compacted_data_file_count":1,"old_merged_file_indices_count":1},"data_compaction_config":{"min_data_file_to_compact":4294967295,"max_data_file_to_compact":4294967295,"data_file_final_size":18446744073709551615,"data_file_deletion_percentage":0},"file_index_config":{"min_file_indices_to_merge":429496729 …
```

[chaos] [2/N] Replay mooncake snapshot and transaction abort

---

src/moonlink_metadata_store/Cargo.toml

[minor] Remove unused feature

---

src/moonlink_metadata_store/src/sqlite/tests.rs

As titled, add a minor missing unit test.

[minor] Test metadata table existence

---

src/moonlink_backend/src/lib.rs
src/moonlink_backend/src/mooncake_table_id.rs
src/moonlink_backend/src/recovery_utils.rs
src/moonlink_backend/src/table_status.rs
src/moonlink_backend/tests/common.rs
src/moonlink_backend/tests/test_backend.rs
src/moonlink_backend/tests/test_initial_copy.rs
src/moonlink_connectors/src/replication_manager.rs
src/moonlink_datafusion/src/schema_provider.rs
src/moonlink_datafusion/src/table_provider.rs
src/moonlink_rpc/src/lib.rs
src/moonlink_service/examples/rest_api_demo.rs
src/moonlink_service/src/rest_api.rs
src/moonlink_service/src/rpc_server.rs

This PR updates all public-facing interfaces from <database-id / table-id> to <schema-name / table-name>.

[3/N] Update all interfaces to from database-id/table-id to schema/table

---

.github/workflows/community_auto_label.yml

Automatically add label "community" to PRs opened.
Not sure how to test it TBH, tentatively merge, will revisit later.

[CI] Auto label community

---

src/moonlink_service/examples/rest_api_demo.rs
src/moonlink_service/src/rest_api.rs

Fix two bugs:
- axum upgrade leads to breaking interface
- create table request payload also changes, needs to update corresponding payload
The issue is we don't have any unit test to guard against bad changes. :(
Closes https://github.com/Mooncake-Labs/moonlink/issues/1477

[REST] Fix rest API demo

---

.github/workflows/ci.yml
Cargo.lock
src/moonlink_connectors/Cargo.toml
src/moonlink_connectors/src/pg_replicate.rs
src/moonlink_connectors/src/pg_replicate/clients/postgres.rs
src/moonlink_connectors/src/pg_replicate/tests/mod.rs
src/moonlink_connectors/src/pg_replicate/tests/pg_type_tests.rs

Composite and Array of Composite Type Support for PG Replication Client
Closes https://github.com/Mooncake-Labs/moonlink/issues/1359
Now support pg client can understand the schema including:
- Composite support
- Array of Composite support
- Nested Array in Composite's field
- Nested Composite
The test covers:
- Composite support
- Array of Composite support
- Nested Composite
Plan to add more type coverage in follow up.
**Notice that the multi-dim array is not supported here**

Composite and Array of Composite Type Support for PG Replication Client

---

.github/workflows/ci.yml
src/moonlink_metadata_store/tests/test_pg_metadata_store.rs
src/moonlink_metadata_store/tests/test_pg_metadata_store_utils.rs

This PR adds postgres metadata store into CI, currently only sqlite metadata store is tested in CI.

[CI] Add pg metadata store integration test

---

src/moonlink/src/error.rs

I met an [error](https://github.com/Mooncake-Labs/moonlink/actions/runs/16979985977/job/48137770236?pr=1473), which loses error source information during propagation; add a hard-coded unit test.

[minor] Add a hard-coded error source test

---

src/moonlink_connectors/src/pg_replicate/util.rs

Introduce from cell to RowValue which handle recursive for cleaner conversion
Closes https://github.com/Mooncake-Labs/moonlink/issues/1461
- Add `impl From<Cell> for RowValue`

refactor: introduce recursive `from cell to RowValue`

---

src/moonlink_backend/tests/test_initial_copy.rs
src/moonlink_connectors/src/pg_replicate.rs

Change initial copy to blocking. 
Closes https://github.com/Mooncake-Labs/moonlink/issues/1238
- 
- 
-

Run init copy in foreground

---

src/moonlink/src/storage/mooncake_table/iceberg_persisted_records.rs
src/moonlink/src/storage/wal.rs

Met some compilation warnings when doing release build.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1504

[minor] Address compilation warnings

---

src/moonlink_backend/Cargo.toml

... otherwise each crate has its own "test-utils" feature.

[minor] Unify test utils feature

---

src/moonlink/src/union_read/read_state_manager.rs

remove redundant error from

---

.github/workflows/ci.yml
src/moonlink/src/table_handler/chaos_test.rs

Before we actually develop append-only feature, add related chaos test.

[chaos] Add append only tests

---

src/moonlink_connectors/src/rest_ingest.rs
src/moonlink_connectors/src/rest_ingest/rest_source.rs

otherwise there's no way to debug

[REST] Bake request in error logging

---

src/moonlink_connectors/src/rest_ingest/json_converter.rs

When json value input is null, and schema field allows null, we should treat it as null inside moonlink.

[REST] Fix null field handle

---

src/moonlink_connectors/src/error.rs
src/moonlink_connectors/src/rest_ingest/moonlink_rest_sink.rs
src/moonlink_connectors/src/rest_ingest/rest_source.rs

This PR handles IO and parquet error properly in file-based upload API.

[storage] Error handling for file-based upload

---

.github/workflows/ci.yml
src/moonlink_service/src/test.rs

Add moonlink service test to CI
Closes #1552
- Setup nginx in CI for running `moonlink_service` standalone test

deployment: setup CI for standalone deployment

---

src/moonlink_backend/src/lib.rs
src/moonlink_service/src/rpc_server.rs
src/moonlink_service/src/test.rs

As titled, add a dummy unit test for load table to prevent stupid mistakes.

[backend] Fix typo and add unit test

---

src/moonlink_service/src/test.rs

Add failure cases to make sure service don't crash.

[service] Add error case for invalid operation

---

src/moonlink_service/src/rpc_server.rs

It's crashing moonlink service; this PR is just a band-aid fix, the better solution is to populate error back, but it's strictly better than unwrap directly.

[service] No crash service for backend error

---

.github/postgres-init/10-replication.sql
.github/workflows/ci.yml
src/moonlink_connectors/src/pg_replicate/tests/cdc_event_test.rs
src/moonlink_connectors/src/pg_replicate/tests/mod.rs
src/moonlink_connectors/src/pg_replicate/tests/pg_type_tests.rs
src/moonlink_connectors/src/pg_replicate/tests/test_utils.rs

Add integration tests for CDC event conversion from logical replication stream with composite types
Closes https://github.com/Mooncake-Labs/moonlink/issues/1524
- Add pg cdc event IT skeleton and one `test_composite_types_in_cdc_stream` test case to test   **composite**, **array of composite**, **nested composite** and **nested array in composite**
- Add a `TestResources` struct with drop implemented to release pg resource
- Correct pg wal level config correctly in github ci file
```
Event 14: XLogData(XLogDataBody { wal_start: 54529448, wal_end: 54529448, timestamp: 808677494744232, data: Update(UpdateBody { xid: None, rel_id: 28017, old_tuple: None, key_tuple: None, new_tuple: Tuple([Text(b"1"), Text(b"(\"Updated St\",\"Updated City\",54321)"), Text(b"(Home,\"(40.7,-74)\")"), …
```

Add integration tests for CDC event conversion from logical replication stream with composite types

---

src/moonlink/src/storage/io_utils.rs

Before REST file upload API, there're only two types of files in mooncake snapshot: write-through caches and iceberg files.
The former will be deleted if (1) they get uploaded to iceberg table; (2) iceberg table lives on local filesystem; (3) unpinned.
After we introduce file upload API, we have third type of file: user uploaded files, which serves as the counterpart for write-through cache and will attempted to be deleted if the above three requirements met.
This PR only attempts deletion only if they're local files.

[storage] Fix file deletion for file upload

---

src/moonlink_backend/src/error.rs
src/moonlink_backend/src/lib.rs

Closes #1629  
- implemented invalid_argument method with ErrorStruct

Moonlink backend invalid argument error type

---

src/moonlink/src/storage/mooncake_table.rs
src/moonlink/src/storage/mooncake_table/data_batches.rs
src/moonlink/src/storage/mooncake_table/snapshot_read.rs
src/moonlink/src/storage/mooncake_table/table_status.rs
src/moonlink/src/storage/mooncake_table/table_status_reader.rs
src/moonlink_backend/src/lib.rs
src/moonlink_backend/src/table_status.rs
src/moonlink_backend/tests/test_backend.rs
src/moonlink_rpc/src/lib.rs
src/moonlink_service/src/rpc_server.rs

This PR exposes cardinality to table status, so we could leverage to optimize.
Return rows count includes:
- all row counts, it's worth noting deleted rows are not accounted
- all committed records, even not persisted, is accounted

[storage] Get table cardinality

---

src/moonlink_backend/src/table_status.rs
src/moonlink_service/src/lib.rs
src/moonlink_service/src/rest_api.rs
src/moonlink_service/src/test.rs

Expose list tables to REST API
Closes #1650
- service: implement GET /tables
- tests: add REST integration test

[REST] Expose list tables to REST API

---

src/moonlink_connectors/src/rest_ingest/decimal_utils.rs

https://github.com/Mooncake-Labs/moonlink/pull/1666 has some bad comment, this PR is to improve comment for better readability comment and add TODO for nan cases
Closes https://github.com/Mooncake-Labs/moonlink/issues/1565
- improve comment for better readability comment and add TODO for nan cases

chore: improve comment for better readability comment and add TODO for nan cases

---

src/moonlink/src/union_read/read_state_manager.rs
src/moonlink_connectors/src/rest_ingest.rs
src/moonlink_connectors/src/rest_ingest/moonlink_rest_sink.rs

This PR fixes replication LSN and commit LSN propagation on rest table recovery; 
also add assertion on read side which fails before the fix.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1703

[REST] Fix LSN propagation on recovery

---

src/moonlink_connectors/src/pg_replicate.rs
src/moonlink_connectors/src/pg_replicate/moonlink_sink.rs

Invariants: iceberg snapshot LSN <= mooncake snapshot LSN <= commit LSN <= replication LSN

Update replication LSN on commit

---

src/moonlink/src/storage/mooncake_table.rs
src/moonlink/src/storage/mooncake_table/table_operation_test_utils.rs
src/moonlink/src/table_handler.rs
src/moonlink/src/table_handler/chaos_replay.rs
src/moonlink/src/table_notify.rs

- index merge result should align with other event, e.g. [Data compaction](https://github.com/Mooncake-Labs/moonlink/blob/868fed105ea66ad6520a9ba16d165e210366c02a/src/moonlink/src/table_handler.rs#L654-L676)
Closes https://github.com/Mooncake-Labs/moonlink/issues/1721
- index merge result refactor

chore: index merge result refactor

---

src/moonlink_service/src/rest_api.rs
src/moonlink_service/src/test.rs

add endpoints to optimize table
- Closes #1651.
- 
- 
-

REST: expose endpoints to optimize table

---

Cargo.lock
src/moonlink_backend/Cargo.toml
src/moonlink_backend/src/lib.rs
src/moonlink_backend/src/parquet_utils.rs
src/moonlink_rpc/src/lib.rs
src/moonlink_service/src/rpc_server.rs

Update parquet metadata single fetch into batch style for performance.

[backend] Batch fetch parquet metadata

---

src/moonlink/src/storage/mooncake_table/transaction_stream.rs
src/moonlink_connectors/src/pg_replicate/tests/test_utils.rs

We need `format` to format the content, otherwise it's just raw text.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1766

Fix expect logging

---

src/moonlink/src/row/column_array_builder.rs
src/moonlink/src/storage/mooncake_table/data_batches.rs

Ditto.
Closes #1752.
- Fix Int32 -> Int16 cast at ColumnArrayBuilder::finish
- Add test_create_batch_from_rows_smallint_type ensuring Int16 array and value

fix: ensure Int16 cast in ColumnArrayBuilder::finish

---

.github/workflows/ci.yml
src/moonlink/src/table_handler/chaos_test.rs

Followup for https://github.com/Mooncake-Labs/moonlink/pull/1776

[chaos] Add upsert table to chaos test and CI

---

src/moonlink/src/storage/mooncake_table/snapshot_validation.rs

Add an assertion on deleted row count.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1774

[storage] Add assertion on deletion vector count

---

src/moonlink_connectors/src/replication_manager.rs

A minor update to add validation when adding rest table.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1805

[minor] Add validation on rest table creation

---

.github/workflows/ci.yml
src/moonlink_backend/tests/common.rs
src/moonlink_backend/tests/control_plane_retry.rs
src/moonlink_backend/tests/test_backend.rs
src/moonlink_backend/tests/test_initial_copy.rs

Add backend integration test into CI
- Closes #1739.

[CI] Integrate Backend tests into CI

---

.github/workflows/ci.yml
src/moonlink/Cargo.toml
src/moonlink/src/storage/iceberg.rs
src/moonlink/src/storage/iceberg/iceberg_table_config.rs
src/moonlink/src/storage/iceberg/rest_catalog.rs
src/moonlink/src/storage/iceberg/rest_catalog_test.rs

Some followups for https://github.com/Mooncake-Labs/moonlink/pull/1725

[storage] Followup PR for rest catalog

---

Cargo.lock
Cargo.toml

Regularly bump up the iceberg-rust dependency version.

Regular upgrade iceberg rust

---

.github/workflows/ci.yml

Ditto.
Closes #1818.
- If a service fails to start after all retries, the job exits with an explicit error message.

[CI] connectivity failure should fail the pipeline

---

src/moonlink_service/src/rest_api.rs
src/moonlink_service/src/test.rs
src/moonlink_service/src/test_utils.rs

expose endpoints to create snapshot
- Closes Part of #1646.
- 
- 
-

[REST-API]: expose endpoints to create snapshot

---

.github/workflows/ci.yml
src/moonlink_service/src/rest_api.rs
src/moonlink_service/src/test.rs

fix the Moonlink Service Integration Tests on **CI**
- Closes Part of #1818.
- 
- 
-

[CI]: fix the Moonlink Service Integration Tests

---

src/moonlink/src/storage/mooncake_table/snapshot_read.rs

A no-op change and a perf improvement: when no deletion vector persisted in iceberg, we don't need to create a deletion vector to get committed unpersisted rows.

[storage] Avoid unnecessary deletion vector creation

---

src/moonlink_backend/tests/test_backend.rs

For flakiness details, refer to https://github.com/Mooncake-Labs/moonlink/issues/1831#issuecomment-3243112509
The fix here is simply return until the event has been sent to table handler, so later snapshot creation requests doesn't return immediately before any events coming to the table.
Closes https://github.com/Mooncake-Labs/moonlink/issues/1831

[REST] Fix rest server recovery test

---

src/moonlink/src/table_handler/chaos_test.rs

[chaos] Increase event count

---

deny.toml

- Fix error in deny check.
- The next PR will clean up these repeated and unmaintained dependencies.
- 
- 
-

[chore]: fix deny check error

---

Cargo.lock
Cargo.toml
src/moonlink/src/storage/iceberg/iceberg_table_manager.rs
src/moonlink/src/storage/iceberg/io_utils.rs

Upgrade iceberg-rust and fix breaking API changes.

[minor] Sync iceberg rust breaking API changes

---

src/moonlink/src/storage/mooncake_table/snapshot_validation.rs

Should be straightforward, all index block files are unique.

[storage] Validate index blocks are unique

---

src/moonlink/src/storage/index/persisted_bucket_hash_map.rs

A minor no-op change, useful for debugging. For example, I could write some ad-hoc debugging code to filter events by file id during construction.

[minor] Record file id at construction

---

Cargo.lock
Cargo.toml
src/moonlink/Cargo.toml
src/moonlink/src/row.rs
src/moonlink/src/row/proto_converter.rs
src/moonlink_backend/src/lib.rs
src/moonlink_backend/tests/test_backend.rs
src/moonlink_connectors/Cargo.toml
src/moonlink_connectors/src/rest_ingest/event_request.rs
src/moonlink_connectors/src/rest_ingest/rest_source.rs
src/moonlink_proto/Cargo.toml
src/moonlink_proto/build.rs
src/moonlink_proto/proto/row.proto
src/moonlink_proto/src/lib.rs
src/moonlink_service/Cargo.toml
src/moonlink_service/src/rest_api.rs
src/moonlink_service/src/test.rs

Adds option to serialize a moonlink row as a protobuf in REST API, as a preparation for Kafka Connector. 
Closes #1872

REST API moonlink row protobuf

---

src/moonlink/src/row/column_array_builder.rs

Added map type to ColumnBuilder, just a simple wrapper around ListBuilder.
Will add it to event api in separate diff (Postgres don't have the type natively).
- 
- 
-

support map type in ColumnBuilder

---

Cargo.toml
src/moonlink_service/src/rest_api.rs
src/moonlink_service/src/test.rs

This PR adds a new REST endpoint to get mooncake table schema.

[REST] Get mooncake table schema

---

Cargo.lock
Cargo.toml
src/moonlink_service/Cargo.toml
src/moonlink_service/src/otel_to_moonlink_pb.rs

Notice there's a later version when debugging.

Upgrade pb

---

src/moonlink/src/storage/mooncake_table/data_batches.rs

We shouldn't panic when schema doesn't match row

[minor] Propagate row append error

---

src/moonlink_connectors/src/pg_replicate/moonlink_sink.rs

`more_assertion` automatically prints out value if assertion fails, no need for verbose logging ourselves.

[minor] Use more-assertion to improve

---

src/moonlink/src/storage/iceberg.rs
src/moonlink/src/storage/iceberg/catalog_test_impl.rs
src/moonlink/src/storage/iceberg/file_catalog.rs
src/moonlink/src/storage/iceberg/file_catalog_test.rs
src/moonlink/src/storage/iceberg/moonlink_catalog.rs

Refactor file catalog test, so test cases could be reused among all catalogs (i.e., rest, glue).

[storage] Refactor file catalog test

---

src/moonlink/src/storage/mooncake_table/table_operation_test_utils.rs
src/moonlink/src/storage/mooncake_table/tests.rs

Currently, MooncakeTable layer tests lack a convenient way to verify
snapshot consistency, requiring verbose manual setup of snapshot reading,
state conversion, and validation logic. This PR adds the `check_mooncake_table_snapshot` 
test utility to address the gap in snapshot validation tests noted in issue #1842.
It provides comprehensive checks—including data files, deletion vectors, and row ID
consistency—while simplifying test code and reducing duplication across
the test suite.
Closes #1842
- Add check_mooncake_table_snapshot function to
table_operation_test_utils.rs
- Add necessary imports: verify_files_and_deletions and
decode_read_state_for_testing
- Add basic test case in tests.rs to verify function works correctly
- Function provides equivalent functionality to …

Add test util function to get current snapshot from mooncake table

---

Cargo.toml
deny.toml
src/moonlink/Cargo.toml
src/moonlink_backend/Cargo.toml
src/moonlink_connectors/Cargo.toml
src/moonlink_datafusion/Cargo.toml
src/moonlink_metadata_store/Cargo.toml
src/moonlink_rpc/Cargo.toml
src/moonlink_service/Cargo.toml

Refactor project structure by extracting common dependencies to the workspace level and ensuring all workspace members are properly included.
I also tried to understand why so many duplicate checks need to be skipped in `deny.toml`. At first, I thought it was due to some unnecessary default features being declared. However, I later realized it was because we explicitly [enabled the all-features check](https://github.com/Mooncake-Labs/moonlink/blob/main/deny.toml#L2C1-L2C13). Therefore, I only suppressed these warnings.
_None_
- Extracted common dependencies to the workspace level.
- Improved imports of workspace members.
- Suppressed `cargo-deny` warnings.
I tested with the following commands:
```shell
cargo test --features storage-gcs
cargo test --features storage-s3
```
> I also tried …

[Chore] Restructure workspace 

---

.github/workflows/ci.yml

Current setup only formats but not checks.

[CI] Validate cargo format

---

Cargo.toml
src/moonlink/Cargo.toml
src/moonlink_backend/Cargo.toml
src/moonlink_connectors/Cargo.toml
src/moonlink_datafusion/Cargo.toml
src/moonlink_metadata_store/Cargo.toml
src/moonlink_rpc/Cargo.toml
src/moonlink_service/Cargo.toml

cargo-sort has been added to the pre-commit hooks, but the main branch does not align with the rules
run `pre-commit run --all-files` on main branch
- 
- 
-

[refactor] Refactor with cargo-sort

---

src/moonlink_error/src/error.rs
src/moonlink_service/src/rpc_server.rs

No need for error trait for ErrorStruct

---

src/moonlink_service/examples/rest_api_demo.rs

Request and response has been changed since a month ago, and we didn't consider backward compatibility before release.
Result after fix:
```sh
[/workspaces/moonlink] (main) 
vscode@695b943761f4$ cargo run --example rest_api_demo --features rest_api_demo
Compiling moonlink_service v0.0.1 (/workspaces/moonlink/src/moonlink_service)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 9.25s
Running `target/debug/examples/rest_api_demo`
🚀 Moonlink REST API Demo
🔧 Starting Moonlink service...
⏳ Waiting for service to be ready...
2025-09-10 04:44:54+00:00  INFO src/moonlink_service/src/lib.rs:176: Moonlink service started successfully
2025-09-10 04:44:54+00:00  INFO src/moonlink_service/src/rpc_server.rs:56: Moonlink RPC server listening on Unix socket: …
```

Fix rest api demo

---

.devcontainer/docker-compose.yml

Port 5000 is occupied by Mac airplay.

Change iceberg-glue port from 5000 to 5001

---

src/moonlink_error/src/error.rs

Followup for https://github.com/Mooncake-Labs/moonlink/pull/2042 to refactor error serde unit tests.

Update error serde test case

---

src/moonlink/src/storage/iceberg/catalog_utils.rs
src/moonlink/src/storage/iceberg/file_catalog.rs
src/moonlink/src/storage/iceberg/glue_catalog.rs
src/moonlink/src/storage/iceberg/rest_catalog.rs

Extract common functions for all catalog implementations.

[minor] Extract puffin write function

---

src/moonlink/src/storage.rs

otherwise cannot use iceberg config outside

[storage] Expose iceberg module

---

src/moonlink/src/storage/iceberg/tests.rs
src/moonlink/src/storage/mooncake_table/validation_test_utils.rs

Test code cleanup, no op change.

[minor] Extract test utils

---

src/moonlink_connectors/src/pg_replicate.rs

Avoid direct interpolation when crafting SQL queries as this is susceptible to SQL injection. Adds quoted literals/identifiers.
- 
- 
-

Use safe sql

---

Cargo.lock
src/moonlink_connectors/Cargo.toml
src/moonlink_connectors/src/pg_replicate/table_init.rs
src/moonlink_connectors/src/rest_ingest.rs
src/moonlink_connectors/src/rest_ingest/rest_source.rs

Allow async process of API ingest events
- 
- 
-

async event process

---

src/moonlink/src/storage/iceberg/iceberg_table_syncer.rs

flame graph shows 12% of the CPU time is spent on checking duplicate files, which involves loading manifest files, parsing and checking.

storage: Avoid expensive duplicate file check at release

---

.github/workflows/ci.yml

This PR parallelize REST server CI integration and stress tests, which should be embarrassingly parallizable.

[CI] Parallelize server test

---

.github/workflows/ci.yml

A random find: we're granting over-permission to testing directory.

[minor] Shrink test directory permission

---

Cargo.lock
Cargo.toml
src/moonlink_service/Cargo.toml

As titled, these packages should be upgraded together.

Upgrade opentelemetry and protobuf

---

.github/workflows/ci.yml

This PR add missing steps for ci workflows:
- setup request rust toolchain
- enable rust cache (including build targets, dependencies, etc)
- use mold as default linker

[CI] Add missing CI steps

---

src/moonlink/src/observability/iceberg_persistence.rs
src/moonlink/src/storage/iceberg/iceberg_table_manager.rs
src/moonlink/src/storage/iceberg/iceberg_table_syncer.rs

Simplify the iceberg persistence stats.

Simplify iceberg persistence stats.

---

src/moonlink_connectors/src/pg_replicate/table_init.rs

This PR fixes commit LSN and replication LSN at recovery.
We have such system invariant: iceberg snapshot LSN <= mooncake snapshot LSN <= commit LSN <= replication LSN
At recovery when we have iceberg snapshot it should be reflected to commit and replication LSN.
The unit test linked in the ticket is flaky because it depends on whether iceberg snapshot is made before recovery.
How I tested:
- I wrote a script to repeatedly run the flaky test, before the fix it fails every 20-30 times
- After the fix it runs for 100 times with no issues 
Closes https://github.com/Mooncake-Labs/moonlink/issues/2126

Fix LSN at recovery

---

src/moonlink/src/storage/table/deltalake/deltalake_table_manager.rs
src/moonlink/src/storage/table/deltalake/test.rs
src/moonlink/src/storage/table/iceberg/iceberg_table_manager.rs

- Implement drop delta table
- Unset all data members on table drop for both delta and iceberg tables

[storage] [3/N] Drop delta table
